Adjust followed channels on home page to meet design requirements
Joystream/atlas pull request #1012
Opened 2021-07-19 20:55 UTC by wyrdrender

2021-07-20 10:53 UTC, kdembler requested changes
Opening the homepage produces an error

2021-07-21 13:25 UTC, drillprop approved these changes
Looks good to me!

2021-07-21 13:25 UTC, drillprop commented on src/views/viewer/HomeView.tsx
> +          {!loading && followedChannelsVideosCount ? (
we don't need loading here, aren't we?

2021-07-22 11:49 UTC, kdembler approved these changes

2021-07-22 12:16 UTC, merged