Add ranking number to carousel
Joystream/atlas pull request #1046
Opened 2021-07-26 13:05 UTC by wyrdrender

2021-07-27 09:45 UTC, kdembler requested changes
Seems the placement of the number could be improved on some screen sizes:
<img width="360" alt="Screenshot 2021-07-26 at 15 42 41" src="https://user-images.githubusercontent.com/12646744/127133344-37d6cdb1-8f16-4a21-b977-76e25cc6467a.png">
Could we make the overlap fixed and instead add some spacing to the left if needed?

Also, if we get to 10, it doesn't look good:
<img width="194" alt="Screenshot 2021-07-26 at 15 42 33" src="https://user-images.githubusercontent.com/12646744/127133419-9ecb47a3-dde7-426b-8ffc-9bef663d394e.png">

2021-07-27 09:45 UTC, kdembler commented on src/components/VideoGallery.tsx
> +      if (breakpoint <= 688 && hasRanking) {
What is this `688`?

2021-07-28 09:54 UTC, wyrdrender commented on src/components/VideoGallery.tsx
> +      if (breakpoint <= 688 && hasRanking) {
This value comes from this function. 
```
364
688
1012
1336
1660
1984
```

2021-07-28 09:58 UTC, wyrdrender commented
@kdembler About values above 10, this is because `letter-spacing: -0.25em;` which comes from figma. I've talked to Kuba about this, and he asked to make it overlap like this. I'll try to spread it out a little bit.

2021-07-28 10:22 UTC, kdembler commented on src/components/VideoGallery.tsx
> +      if (breakpoint <= 688 && hasRanking) {
This doesn't tell me anything at all :P

2021-07-30 07:32 UTC, kdembler approved these changes
Looking good!

2021-07-30 11:21 UTC, drillprop reviewed
I think we should change letter-spacing a bit. It's still not looking great: 
![image](https://user-images.githubusercontent.com/51168865/127645779-0221132f-0ea3-4398-a24e-08e62736316e.png)

`-0.1em` maybe?

2021-08-02 08:30 UTC, merged