Rename components
Joystream/atlas pull request #1098
Opened 2021-08-03 07:28 UTC by eldiegod

fixes: #1089

2021-08-04 07:43 UTC, drillprop commented on src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
>  } from './EditVideoForm.style'
We have a warning here! ⚠️

2021-08-04 09:04 UTC, eldiegod commented on src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
>  } from './EditVideoForm.style'
fixed

2021-08-06 08:51 UTC, kdembler requested changes

2021-08-06 08:51 UTC, kdembler commented on src/shared/components/TitleArea/TitleArea.stories.tsx
> +  title: 'Shared/H/TitleArea',
```suggestion
  title: 'Shared/T/TitleArea',
```

2021-08-06 08:51 UTC, kdembler commented on src/shared/components/VideoTileBase/VideoTileBase.styles.tsx
> +export const VideoHeroPublishingStateOverlay = styled.div`
I don't think this is a desired change, this doesn't have anything to do with the `VideoHero` component

2021-08-06 08:51 UTC, kdembler commented on src/shared/components/ProgressDrawer/ProgressDrawer.stories.tsx
> +  title: 'Shared/C/ProgressDrawer',
```suggestion
  title: 'Shared/P/ProgressDrawer',
```

2021-08-06 10:55 UTC, kdembler approved these changes

2021-08-06 11:34 UTC, merged