Skeleton holder visual update
Joystream/atlas pull request #1106
Opened 2021-08-04 09:19 UTC by eldiegod

fixes: #941

2021-08-04 09:46 UTC, kdembler requested changes
There seems to be some issue in the Video Tile, with the bottom 2 placeholders. It seems like only one vertical half of them is animated:

https://user-images.githubusercontent.com/12646744/128160143-26f1562e-22b0-4a44-adce-1d95200ea662.mov

2021-08-04 12:09 UTC, eldiegod commented
Avatar on channel view doesnt show wave also on studio view my uploads circle to the right doesn't show a wave

Also remove pulsing anim on the hero video from homepage

2021-08-06 08:54 UTC, kdembler reviewed
Needs cleanup, otherwise ready to go

2021-08-06 08:54 UTC, kdembler commented on src/components/CoverVideo/CoverVideo.style.ts
> -const pulse = keyframes`
Unused imports left on top of this file

2021-08-06 13:22 UTC, kdembler approved these changes

2021-08-06 13:22 UTC, merged