Video content pages
Joystream/atlas pull request #1130
Opened 2021-08-09 10:41 UTC by wyrdrender

2021-08-16 09:58 UTC, kdembler requested changes
Let's fix those in a separate PR to not have any direct commits to this branch

2021-08-16 09:58 UTC, kdembler commented on .env
> +REACT_APP_DEVELOPMENT_OFFICIAL_JOYSTREAM_CHANNEL=12
Let's add `_ID` at the end

2021-08-16 09:58 UTC, kdembler commented on src/api/hooks/video.ts
> +  }, [mostViewedVideos])
Let's get rid of `useMemo` here

2021-08-16 09:58 UTC, kdembler commented on src/api/hooks/languages.ts
> +}
This is used for the language select right? I'm wondering what's the benefit of getting this data from the query node. Query node will only return list of languages that have been used in some way (as a channel or video language), but that doesn't guarantee that they will have any public videos to be displayed in the app. So this list will have kind of random entries and there's no guarantee that those will have any videos. So maybe instead let's just use the list we have defined in the app (`config/languages.ts`) and skip the fetch?

2021-08-16 09:58 UTC, kdembler commented on src/views/viewer/ChannelsView/ChannelsView.tsx
> +export const ChannelsView = () => {
Should have `: React.FC`

2021-08-17 08:25 UTC, wyrdrender commented on src/api/hooks/languages.ts
> +}
I added this query because I needed id of each language. Question is, is to ok to hard code those ids in `languages.ts`

2021-08-19 12:05 UTC, kdembler commented
I think we haven't added the `categoryId` when adding a video view, right @wyrdrender ?

2021-08-19 12:08 UTC, wyrdrender commented
> I think we haven't added the `categoryId` when adding a video view, right @wyrdrender ?

Yes, you are right. But on the other hand I just realized we lost "Most popular categories" section because of changes in design. I think we can remove this query from orion. WDYT?

2021-08-19 12:14 UTC, kdembler commented
Yeah I think we can delete the queries, just let's do that in a separate PR so it's easy to rollback if needed

2021-08-19 12:14 UTC, kdembler commented
Also, let's keep the `categoryId` for `addVideoView` so we collect the data anyway

2021-08-20 18:06 UTC, kdembler approved these changes

2021-08-20 18:08 UTC, merged