Fix layout shift on popular page
Joystream/atlas pull request #1188
Opened 2021-08-17 07:01 UTC by drillprop

Fix #1187
Also: 
- fix the skeleton loader in InfiniteVideoGrid
- fix the follow button on ChannelWithVideos(the app was navigating to channel when user clicks follow/unfollow)

2021-08-17 09:04 UTC, kdembler commented on src/components/InfiniteGrids/InfiniteVideoGrid.tsx
> +            {loading || !displayedItems.length ? (
We're ignoring the `ready` props now. Was that the plan?

2021-08-17 16:24 UTC, kdembler requested changes
Unfortunately there are still some issues with jumping. Take a look at this (New view):

https://user-images.githubusercontent.com/12646744/129763714-93e54b93-e5c5-4c61-81fc-4d41caa02080.mov

You can see 2 jumps here:
1. The placeholder jumps down and back up a bit (not a biggie, we can skip if hard to fix)
2. The border under the title jumps down significantly after the skeleton disappears, we need to improve that

2021-08-17 18:40 UTC, drillprop commented
Fixed, It should be good now

2021-08-18 09:12 UTC, kdembler approved these changes

2021-08-18 09:12 UTC, merged