Wrap all video content pages into single template
Joystream/atlas pull request #1248
Opened 2021-08-24 13:07 UTC by wyrdrender

2021-08-25 12:31 UTC, kdembler requested changes

2021-08-25 12:31 UTC, kdembler commented on src/components/templates/VideoContentTemplate.tsx
> +  )
We don't need this `useMemo`, let's get rid of it. This component will re-render very rarely (most likely never) so optimization isn't needed

2021-08-25 12:31 UTC, kdembler commented on src/components/templates/VideoContentTemplate.tsx
> +const StyledViewWrapper = styled(ViewWrapper)`
Why do we need this `ViewWrapper`? I think it's something quite old, it contains only `position: relative;`. We should use `LimitedWidthContainer` instead to make sure the pages don't exceed their max width

2021-08-25 12:31 UTC, kdembler commented on src/components/templates/index.ts
> +export * from './VideoContentTemplate'
Let's not use `index.ts` here and import directly, like with the rest of the components

2021-08-26 08:18 UTC, kdembler requested changes

2021-08-26 08:18 UTC, kdembler commented on src/components/templates/VideoContentTemplate.tsx
> +  const renderCta =
This shouldn't be called `renderCta` as this isn't a render function, it's just an already computed value. Something like `ctaContent` or alike would be a better name

2021-08-26 08:18 UTC, kdembler commented on src/components/templates/VideoContentTemplate.tsx
> +    margin: ${sizes(16)} 0 ${sizes(17)};
margins aren't correct here, design specifies constant `margin: 64px 0;`

2021-08-26 08:18 UTC, kdembler commented on src/components/templates/VideoContentTemplate.tsx
> +const Header = styled(Text)`
This is missing some of necessary typography styles

2021-08-26 09:09 UTC, rafalpawlow commented on src/components/templates/VideoContentTemplate.tsx
> +    margin: ${sizes(16)} 0 ${sizes(17)};
Did I select wrong layer?
![Zrzut ekranu 2021-08-26 o 10 57 57](https://user-images.githubusercontent.com/13706246/130935598-95af9441-d16b-415d-8454-bbac42fc7ff0.png)
![Zrzut ekranu 2021-08-26 o 10 58 04](https://user-images.githubusercontent.com/13706246/130935600-ef976957-79b0-43b1-9bbb-f0c24dae89cc.png)

2021-08-26 09:10 UTC, kdembler commented on src/components/templates/VideoContentTemplate.tsx
> +    margin: ${sizes(16)} 0 ${sizes(17)};
You're measuring it a bit incorrectly. You're trying to find distance between two text nodes, but in reality `Top 10 channels` actually has also some container around it so if you take 68/72 and apply it as margin, the padding around `Top 10 channels` will cause the distance between the text nodes to be more like 80 or something.

2 tips for measuring in Figma:
1. You can always use the nodes list on the left to make sure you have a proper container selected instead of a child of it.
2. If you hold Cmd (on Mac, I guess it's Ctrl for others), Figma will instead measure distance to the closest container it can find along the way, not to the node you're hovering above.

You can see those in this video (in the second part I'm pressing Cmd):

https://user-images.githubusercontent.com/12646744/130935411-6ca32013-3429-421d-b7a7-ea5284874d29.mov

2021-08-26 10:01 UTC, kdembler approved these changes

2021-08-26 10:01 UTC, merged