Add new video tile
Joystream/atlas pull request #1313
Opened 2021-09-01 15:32 UTC by drillprop

Fix #1269

2021-09-02 14:51 UTC, wyrdrender commented
It's a 2px too long on desktop. `padding-bottom: 55.47%;` works a little bit better for desktop
![Zrzut ekranu 2021-09-2 o 16 48 48](https://user-images.githubusercontent.com/13706246/131865988-9bed2d7b-70e9-4848-81fd-00567456329f.png)

2021-09-03 06:24 UTC, drillprop commented
> It's a 2px too long on desktop. `padding-bottom: 55.47%;` works a little bit better for desktop
> ![Zrzut ekranu 2021-09-2 o 16 48 48](https://user-images.githubusercontent.com/13706246/131865988-9bed2d7b-70e9-4848-81fd-00567456329f.png)

Good catch! Should be fixed now

2021-09-03 09:43 UTC, wyrdrender approved these changes

2021-09-03 10:41 UTC, kdembler requested changes

2021-09-03 10:41 UTC, kdembler commented on src/views/studio/MyVideosView/MyVideos.styles.ts
> +    ${() => StyledText} {
If we can, let's avoid this type of selectors. In this case I think you can just move `StyledIcon` and `StyledText` above this declaration, right?

2021-09-03 10:41 UTC, kdembler commented on src/views/studio/MyVideosView/MyVideosView.tsx
> +              )}
This should likely handle loading state in some way. Currently this is clickable once other items are in loading state. For uniformity I would display some kind of placeholder for it as well

2021-09-03 10:41 UTC, kdembler commented on src/views/studio/MyVideosView/MyVideosView.tsx
> +                <NewVideoTile to={absoluteRoutes.studio.editVideo()}>
This kind of breaks the pagination on this page - now the first page will have items for 4 rows + 1 item in 5th row

2021-09-07 11:33 UTC, kdembler requested changes
I'm pretty sure we should still use the current empty states when there are no items to display for a tab. After this PR we show:

<img width="962" alt="Screenshot 2021-09-07 at 13 30 11" src="https://user-images.githubusercontent.com/12646744/132337740-6ce3d537-02ce-4f20-8f26-5272b0f016f0.png">

2021-09-07 11:33 UTC, kdembler commented on src/views/studio/MyVideosView/MyVideosView.tsx
> +                totalCount={isDraftTab ? drafts.length + 1 : (totalCount || 0) + 1}
But `drafts.length` already includes that item so this will not be correct

2021-09-07 11:33 UTC, kdembler commented on src/views/studio/MyVideosView/MyVideosView.tsx
> +}
Let's move this to a separate file, along with its styles. It can be here or in one of the `components` folders

2021-09-07 12:27 UTC, drillprop commented
> I'm pretty sure we should still use the current empty states when there are no items to display for a tab. After this PR we show:
> 

Updated. I decided to not show `NewVideoTile` when there are no videos/drafts. Not sure if you meant that. I just think it looks odd with `EmptyFallback` together.

2021-09-07 12:53 UTC, kdembler approved these changes

2021-09-07 12:53 UTC, merged

2021-09-09 13:20 UTC, KubaMikolajczyk commented
Love the implementation! And yes I wouldn't use it on pages like empty for drafts and empty for unlisted - those should container only empty fallback - so thats perfect!
One minor thing:
![image](https://user-images.githubusercontent.com/31144205/132693253-2070c0c5-7c49-4c17-b22f-f95fc9c8ac54.png)
On the screen above I added 48px margin to this new tile - as it looks really cluttered when those are squished together currently theyre 24px apart and its tight

Great job!