Add RadioCardButton component
Joystream/atlas pull request #1330
Opened 2021-09-06 10:48 UTC by drillprop

fix #1273 
design: https://www.figma.com/file/mMGcjK0usOHzKXAwcBdwiv/[-10]-Upload-flow-improvements?node-id=3%3A7236

2021-09-07 12:56 UTC, kdembler commented
@KubaMikolajczyk shouldn't this have some kind of hover state specified? I don't see anything in the design

2021-09-07 13:06 UTC, kdembler requested changes

2021-09-07 13:06 UTC, kdembler commented on src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
>  import { FileErrorType, ImageInputFile, VideoInputFile } from '@/shared/components/MultiFileSelect/MultiFileSelect'
😅 

```suggestion
import { FileErrorType, ImageInputFile, VideoInputFile } from '@/shared/components/MultiFileSelect'
```

2021-09-07 13:06 UTC, kdembler commented on src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
> +                        helperText={'Visible with link only'}
Let's use regular `"` here

2021-09-07 13:06 UTC, kdembler commented on src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
> +                        ref={ref}
Why do we pass the `ref` here?

2021-09-07 13:06 UTC, kdembler commented on src/shared/components/RadioButton/RadioButton.style.ts
>    --radio-button-container-size: ${sizes(6)};
`--radio-button-size` isn't used anymore, let's remove it

`--radio-button-container-size` is used for `RadioButtonContainer` but I don't think we really need it? Tbh we shouldn't need `RadioButtonContainer` at all

2021-09-07 13:06 UTC, kdembler commented on src/shared/components/RadioButton/RadioButton.tsx
> +import { RadioInput } from '../RadioInput/RadioInput'
```suggestion
import { RadioInput } from '../RadioInput'
```

2021-09-07 13:06 UTC, kdembler commented on src/shared/components/RadioCardButton/RadioCardButton.styles.ts
> +  border: 1px solid ${({ selected, disabled, error }) => getRadioCardBorderColor({ selected, disabled, error })};
You can just pass the function, it should get called with the props:
```suggestion
  border: 1px solid ${getRadioCardBorderColor};
```

2021-09-09 08:54 UTC, drillprop commented
> @KubaMikolajczyk shouldn't this have some kind of hover state specified? I don't see anything in the design

Found it: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=750%3A90714

2021-09-09 09:27 UTC, drillprop commented
@kdembler In the design, this component is called `option card`, but I'm not sure if we should add this. I think we could just stick to RadioCardButton for now. I don't see the usage of the checkbox with this card yet. Let me know what you think

2021-09-09 11:42 UTC, kdembler commented
I think here it makes sense to use the name from the design - our name clearly works only for radio buttons while the design allows for checkboxes inside as well. I wouldn't want us to need to change the component name later when we add checkboxes

2021-09-09 12:21 UTC, KubaMikolajczyk commented
The way those option cards work is flawless - only issues I spotted are in their responsiveness:
![image](https://user-images.githubusercontent.com/31144205/132684468-d887353e-9ba6-4d2f-9a77-1138efd6883c.png)
Somehow they stop filling the container after 865px breakpoint 
![image](https://user-images.githubusercontent.com/31144205/132684611-e0fe7e63-fa74-4d7c-9ad2-099f5493595f.png)
And on mobile those should use a vertical layout

Everything is explained here: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Page-Video-workspace?node-id=314%3A6148

2021-09-10 06:41 UTC, kdembler reviewed
All looks good but I think we still have a bit of inconsistency with the hover state. Design says that on card hover, the radio button should also have its hover state triggered. However it seems to me this may be complicated. Do you have any idea on how to achieve that?

2021-09-10 07:55 UTC, drillprop commented
> All looks good but I think we still have a bit of inconsistency with the hover state. Design says that on card hover, the radio button should also have its hover state triggered. However it seems to me this may be complicated. Do you have any idea on how to achieve that?
Check now.
I think it's relatively clean. I mean I kinda don't like that we need to import `CustomRadioInput` in `OptionCard`, but didn't find a cleaner solution.

2021-09-10 08:16 UTC, kdembler approved these changes

2021-09-10 08:16 UTC, merged