Add upload button to my videos view, various Select fixes
Joystream/atlas pull request #1395
Opened 2021-09-22 18:24 UTC by drillprop

Fix #1270 

Also: 
- brought back forwardRef to Select component(saw some errors in the console earlier, focus on error didn't work correctly)
- some smaller size input and button size adjustments

2021-09-23 06:05 UTC, drillprop commented on src/shared/components/ButtonBase/ButtonBase.style.ts
> +  margin-bottom: ${({ textOnly }) => textOnly && '-0.5px'};
just for clarification, the buttons had some weird heights. Large buttons had 47px, medium 39px and small 31. These lines should fix that, all the sizes should be divisible by 4 now.

2021-09-23 12:55 UTC, wyrdrender commented
Something is wrong with button width
![Zrzut ekranu 2021-09-23 o 14 54 06](https://user-images.githubusercontent.com/13706246/134510435-9619aea1-0f08-41e5-9ea4-1d4f9e3615a0.png)
![Zrzut ekranu 2021-09-23 o 14 54 18](https://user-images.githubusercontent.com/13706246/134510438-f72e3297-1c31-4ba4-b48c-c71cc57a4542.png)

2021-09-23 12:56 UTC, wyrdrender requested changes

2021-09-23 12:56 UTC, wyrdrender commented on src/shared/components/InputBase/InputBase.styles.ts
> +    line-height: 30px;
```suggestion
    line-height: ${typography.lineHeights.body1}
```

2021-09-23 12:56 UTC, wyrdrender commented on src/views/studio/MyVideosView/MyVideosView.tsx
> +              <Button to={absoluteRoutes.studio.editVideo()} icon={<SvgGlyphUpload />}>
On designs there is different icon: `SvgGlyphAddVideo`

2021-09-23 12:59 UTC, wyrdrender approved these changes

2021-09-23 12:59 UTC, rafalpawlow commented on src/views/studio/MyVideosView/MyVideosView.tsx
> +      helperText={null}
This is not needed since we changed `helperText`
```suggestion
```

2021-09-23 12:59 UTC, wyrdrender requested changes

2021-09-23 12:59 UTC, wyrdrender commented on src/views/studio/MyVideosView/MyVideosView.tsx
> +        <MobileButton to={absoluteRoutes.studio.editVideo()} icon={<SvgGlyphUpload />}>
On designs there is different icon: `SvgGlyphAddVideo`

2021-09-23 14:09 UTC, drillprop commented
> Something is wrong with button width
> ![Zrzut ekranu 2021-09-23 o 14 54 06](https://user-images.githubusercontent.com/13706246/134510435-9619aea1-0f08-41e5-9ea4-1d4f9e3615a0.png)
> ![Zrzut ekranu 2021-09-23 o 14 54 18](https://user-images.githubusercontent.com/13706246/134510438-f72e3297-1c31-4ba4-b48c-c71cc57a4542.png)

I think it's a mistake in the design and I shouldn't change it. Normally medium-size button has 16px horizontal padding. In this view for some reason, it has only 12px. 
My videos: 
![image](https://user-images.githubusercontent.com/51168865/134522456-e9058fa7-a012-4a49-bc51-f6943fcc9c66.png)
Web components: 
![image](https://user-images.githubusercontent.com/51168865/134522558-03f98575-b402-403b-83d4-859e9b789360.png)

2021-09-23 14:28 UTC, wyrdrender approved these changes

2021-09-24 11:43 UTC, kdembler requested changes
1. On 1024px the button wraps and creates bad visuals. Could we improve that?
<img width="746" alt="Screenshot 2021-09-24 at 13 24 45" src="https://user-images.githubusercontent.com/12646744/134667081-f4dce345-0b41-4655-8333-ac574abc9ef7.png">

2. I've noticed that the tabs and `sort by` aren't aligned properly. That's because our implementation of Tabs differs slightly from the design. That is, we use a border which will make the tab label not centred inside its container. I guess you could change the border inside the tab to an inner box-shadow to achieve the same effect but without the misalignment?
<img width="330" alt="Screenshot 2021-09-24 at 13 26 13" src="https://user-images.githubusercontent.com/12646744/134667611-569a3709-0d6e-4865-a552-8666bba1e04a.png">

2021-09-24 11:43 UTC, kdembler commented on src/views/studio/MyVideosView/MyVideosView.tsx
> +                Upload Video
```suggestion
                Upload video
```

2021-09-24 11:43 UTC, kdembler commented on src/views/studio/MyVideosView/MyVideosView.tsx
> +          Upload Video
```suggestion
          Upload video
```

2021-09-27 10:58 UTC, kdembler approved these changes

2021-09-27 11:31 UTC, merged