Fix scrollbar behind action bar
Joystream/atlas pull request #1412
Opened 2021-09-27 11:52 UTC by wyrdrender

2021-09-27 12:00 UTC, kdembler commented
Doesn't really work: the action bar is visible at the bottom of the screen even when not needed:

https://user-images.githubusercontent.com/12646744/134903916-64599a4d-da7a-4142-bc5a-c05fb18cbe48.mov

2021-09-27 14:04 UTC, drillprop requested changes

2021-09-27 14:04 UTC, drillprop commented on src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.style.ts
> +const EDIT_VIDEO_TABS_BAR_HEIGHT = '56px'
You should import this from `EditVideoTabsBar`

2021-09-28 09:17 UTC, drillprop approved these changes

2021-09-28 13:16 UTC, kdembler approved these changes

2021-09-28 13:16 UTC, merged