Create BackgroundVideoPlayer component
Joystream/atlas pull request #1430
Opened 2021-09-28 16:11 UTC by drillprop

Fix #1383

2021-09-29 06:42 UTC, drillprop commented
Draft, needs some tweaks

2021-09-29 16:01 UTC, kdembler requested changes

2021-09-29 16:01 UTC, kdembler commented on src/components/BackgroundVideoPlayer.tsx
> +  }, [autoPlay, playing])
This hook has a dependency for `autoPlay` but doesn't use it. If this is intentional then let's add a comment with explanation

2021-09-29 16:01 UTC, kdembler commented on src/components/VideoHero/VideoHero.tsx
> +                {videoPlaying ? 'Pause' : 'Play'}
The current behaviour is correct, the goal of the Play button is to navigate to the full video, not control the background playback

2021-09-29 16:01 UTC, kdembler commented on src/components/BackgroundVideoPlayer.tsx
> +export default BackgroundVideoPlayer
Let's use a named export ;)

2021-09-29 17:33 UTC, drillprop commented on src/components/BackgroundVideoPlayer.tsx
> +  }, [autoPlay, playing])
not intentional, fixed

2021-09-30 08:08 UTC, kdembler approved these changes

2021-09-30 08:08 UTC, merged