Category infinite grid
Joystream/atlas pull request #1490
Opened 2021-10-14 17:15 UTC by eldiegod

Useful figma links:
https://www.figma.com/file/3uFQ2y1jlS6fbp7Ac0yIpv/%5B%2312%5D-Video-category-page-flows?node-id=304%3A39876
https://www.figma.com/file/UdBMxrLspjcf6IVYYJS8YP/%5BPage%5D-Discover-%26-Video-category?node-id=252%3A93224

Fixes: #1380

2021-10-15 11:33 UTC, kdembler submitted a review, later dismissed
We need to improve z indexes:
<img width="516" alt="Screenshot 2021-10-15 at 13 26 45" src="https://user-images.githubusercontent.com/12646744/137479894-a01c3285-0006-4161-9657-b4407c9c8788.png">
<img width="374" alt="Screenshot 2021-10-15 at 13 26 48" src="https://user-images.githubusercontent.com/12646744/137479905-ee77635d-9511-4ffc-9fd7-a873fdbbc63e.png">

2021-10-15 11:33 UTC, kdembler commented on src/components/CategoryVideos/CategoryVideos.styles.tsx
> +  margin-top: ${sizes(32)};
What's going on here?

2021-10-15 11:33 UTC, kdembler commented on src/components/CategoryVideos/CategoryVideos.tsx
> +import React, { useEffect, useState } from 'react'
I think this file should be inside `views/` not inside `components/`?

2021-10-15 11:33 UTC, kdembler commented on src/components/CategoryVideos/CategoryVideos.tsx
>            <Text variant={mdMatch ? 'h4' : 'h5'}>All videos (441)</Text>
What about number in this header?

2021-10-15 11:33 UTC, kdembler commented on src/components/CategoryVideos/CategoryVideos.tsx
> +  const { id } = useParams()
Let's make the parent view pass this here, without direct access

2021-10-15 11:33 UTC, kdembler commented on src/components/CategoryVideos/CategoryVideos.tsx
> +  const [selectedLanguage, setSelectedLanguage] = useState<string | null | undefined>('en')
Let's keep the default language in a single variable so we can change it if needed

2021-10-15 11:34 UTC, kdembler commented on src/components/CategoryVideos/CategoryVideos.tsx
> +  const [selectedLanguage, setSelectedLanguage] = useState<string | null | undefined>('en')
Actually after giving it second thought, I'm pretty sure that by default not language should be selected

2021-10-18 07:21 UTC, eldiegod commented on src/components/CategoryVideos/CategoryVideos.tsx
> +  const [selectedLanguage, setSelectedLanguage] = useState<string | null | undefined>('en')
problem is once a language is selected one cannot unselect languages, but this is a problem in every language selector that we have

2021-10-18 07:22 UTC, eldiegod commented on src/components/CategoryVideos/CategoryVideos.styles.tsx
> +  margin-top: ${sizes(32)};
These are temp margins in the meanwhile the other components missing are added otherwise it doesn't look good with the hero

2021-10-19 09:44 UTC, rafalpawlow requested changes

2021-10-19 09:44 UTC, wyrdrender commented on src/views/viewer/CategoryView/CategoryVideos.tsx
> +          helperText={null}
As far as I remember, few weeks ago we allowed `helperText` to be undefined, so I think we can safely get rid of this.

2021-10-19 10:35 UTC, rafalpawlow approved these changes

2021-10-19 10:37 UTC, merged