Dynamic featured content
Joystream/atlas pull request #1516
Opened 2021-10-26 13:28 UTC by eldiegod

Add dynamic content from orion to:

- Featured category cards in /discover
- Featured videos section in /category/id
- Category video hero in /category/id

2021-10-27 12:56 UTC, kdembler reviewed
Additionally, like discussed over RocketChat, let's make sure the new views work properly on all deployments, even when the category list is different

2021-10-27 12:56 UTC, kdembler commented on src/views/viewer/CategoryView/CategoryView.tsx
> +}
Couple of notes:
1. I think we should filter `featuredVideos` first to make sure we operate only on videos that have `videoCutUrl` defined.
2. We must remember that this component doesn't have to work with 3 videos at all times. We should try displaying 3 but we must handle the case when for example only 2 or 1 video has `videoCutUrl` defined. I'm not saying the current code doesn't work in this case because I didn't test it yet, but a note to you.
3. I think we may need to update video hero in category view to work without full-size thumbnails. As discussed in some other places, soon thumbnails will be only lowres so will not work well in full width context. I think we will require custom image only for main video hero on home page. For those I think we could figure out something else. For example, we can force the video player to show the first frame when the video is still loading. Can you make sure this will work fine with lowres images?

2021-10-27 12:56 UTC, kdembler commented on src/views/viewer/DiscoverView/DiscoverView.tsx
> +    categoriesFeaturedVideos?.[category.id]
We don't need this statement

2021-11-02 10:25 UTC, kdembler requested changes
Opening https://deploy-preview-1516--atlas-dev.netlify.app/discover with the mainnet produces quite a broken screen

2021-11-02 10:25 UTC, kdembler commented on src/views/viewer/CategoryView/CategoryView.tsx
> +      {(featuredVideos?.length ?? 0) > 0 && (
Let's just do `data?.[id] ?? []` in line 30 and then we can get rid of all the optional chaining

2021-11-02 10:25 UTC, kdembler commented on src/views/viewer/CategoryView/CategoryView.tsx
> +            {[...(featuredVideos ?? [])]?.map((video, idx) => (
Why do we need to expand this array here?

2021-11-02 10:25 UTC, kdembler commented on src/views/viewer/DiscoverView/DiscoverView.tsx
> +  const videoCategoriesArray = Object.values(videoCategories)
Is the key in the `videoCategories` object used in any way now? If not, maybe let's just the `id` be the key instead and then we don't need `Object.values` and later `find`, we could just do `videoCategories[category.id]`

2021-11-02 10:59 UTC, eldiegod commented on src/views/viewer/DiscoverView/DiscoverView.tsx
> +  const videoCategoriesArray = Object.values(videoCategories)
true

2021-11-03 14:48 UTC, kdembler approved these changes

2021-11-03 15:13 UTC, merged