Remove shared folder
Joystream/atlas pull request #1569
Opened 2021-11-08 22:54 UTC by eldiegod

fixes:  #1541

Removes shared folder, fixes components file structure inconsistencies and adds folders like forms, overalys, icons and illustrations into the components folder

2021-11-09 10:42 UTC, kdembler commented
We have this entry in `.prettierignore`:
```
# don't prettify minified animation JSONs
src/shared/assets/animations
```
It needs to be updated because your PR prettifies all the animations causing this massive diff. They should be left as they are, minified

2021-11-09 11:46 UTC, eldiegod commented
@kdembler  fixed

2021-11-09 13:10 UTC, drillprop commented
My suggestions/feedback:
- I think we could move some components to views, especialy the ones which have name with suffix Studio/Viewer for example SidenavStudio, SidenavViewer
- we could group Buttons together. Keep Button, ButtonBase, IconButton in one directory
- Select should go to forms
- Maybe we could move TransactionModal also to views/studio?
- let's move TermsOfService to views/legal

2021-11-09 13:14 UTC, eldiegod commented
> My suggestions/feedback:
> 
>     * I think we could move some components to views, especialy the ones which have name with suffix Studio/Viewer for example SidenavStudio, SidenavViewer
> 
>     * we could group Buttons together. Keep Button, ButtonBase, IconButton in one directory
> 
>     * Select should go to forms
> 
>     * Maybe we could move TransactionModal also to views/studio?
> 
>     * let's move TermsOfService to views/legal

- ButtonBase should just be under Button imo and we should get rid of IconButton idk why we maintain it when Button can have icon only prop
- Maybe rename `forms` to `inputs`
- TransactionModal is not to clear to me where it should go
- agree with the rest

2021-11-09 13:15 UTC, kdembler commented
There's ongoing discussion in RocketChat on what the structure should be.

Other than that, my suggestions:
- `InputBase`, `OptionCard`, `Select` should be in `forms` (I would vote for also moving `FileSelect` and `MultiFileSelect` here) (possibly rename to `inputs`?)
- `Popover`, `ContextMenu`, `StepperModal`, `TransactionModal` should be in `overlays`
- Create `navigation` category that would contain all topbar/sidenav/bottomnav components
- Create `channel` category for all channel related stuff
- Create `video` category for all video related stuff
- Create `content` (possibly could use a better name) to keep all the content sections - `TopTenThisWeek`, `DiscoverChannels`, etc.

Reply to @drillprop feedback:
- I think `buttons` category works as well
- If possible I wouldn't want to move too many components to `views`/. `TransactionModal` will be soon used by viewer as well
- `TermsOfService` is used by studio as well, in sign in so needs to stay a generic component

2021-11-10 19:35 UTC, eldiegod commented
Added the folders mentioned; Button is an input so figured I'd put it in `_inputs` along with select and also avoided moving components to views for now

2021-11-15 10:48 UTC, kdembler commented
Personally, I'd move `Button` out of `_inputs`, doesn't feel like the right place for it for me. I suggest moving it to `_buttons` along with other button-like components that are currently uncategorized. This isn't a strong opinion though, if there's an agreement it should be in `_inputs`, I'm fine with that

2021-11-15 11:32 UTC, drillprop reviewed
- agree with Klaudiusz regarding buttons
- I think, we could create `_loaders` directory, where we could keep SkeletonLoader, Loader and Spinner. Not sure if everyone agrees with me.
- DatePicker should be in inputs
- Don't like `_content` directory, because I'm not really sure what we should put there. For example - why you didn't put there for instance `PromisingChannels` or `OfficialJoystreamUpdate`? These two components look very similar to those inside `_content` directory. 
- There are still some of components that are very specific to some views, and Im wondering where we should put them (for example SigninSteps or StudioEntrypoint). I would consider move them to views maybe, but not sure what others think about.

2021-11-15 11:35 UTC, wyrdrender requested changes

2021-11-15 11:35 UTC, rafalpawlow commented on src/components/Badge/Badge.styles.tsx
>  import { css } from '@emotion/react'
Can we get rid of `.tsx` extension as part of this PR?

2021-11-15 11:35 UTC, wyrdrender commented on src/components/CircularProgress/CircularProgress.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/FiltersBar/FiltersBar.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/GlobalStyles/transitionStyles.tsx
>  import { css } from '@emotion/react'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/Pagination/Pagination.styles.tsx
>  import { css } from '@emotion/react'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/ProgressDrawer/ProgressDrawer.styles.tsx
>  import isPropValid from '@emotion/is-prop-valid'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/Searchbar/Searchbar.styles.tsx
>  import isPropValid from '@emotion/is-prop-valid'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/ShortcutIndicator/ShortcutIndicator.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/SignInSteps/TermsStep.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/Tabs/Tabs.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/_inputs/Checkbox/Checkbox.styles.tsx
>  import { css } from '@emotion/react'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/_inputs/TitleArea/TitleArea.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/_navigation/TopbarBase/TopbarBase.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/_navigation/TopbarStudio/TopbarStudio.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/_navigation/TopbarViewer/TopbarViewer.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/_video/VideoPlayer/VideoPlayer.styles.tsx
>  import { css } from '@emotion/react'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/components/_video/VideoTileBase/VideoTileBase.styles.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/CreateEditChannelView/CreateEditChannelView.style.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension, also let's rename it to `CreateEditChannelView.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/CreateMemberView/CreateMemberView.style.ts
>  import styled from '@emotion/styled'
Let's rename it to `CreateMemberView.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/MyUploadsView/MyUploadsView.style.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension, also let's rename it to `MyUploadsView.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/MyUploadsView/UploadStatus/UploadStatus.style.tsx
>  import { css } from '@emotion/react'
Get rid of `.tsx` extension, also let's rename it to `UploadStatus.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/MyUploadsView/UploadStatusGroup/UploadStatusGroup.style.tsx
>  import { css } from '@emotion/react'
Get rid of `.tsx` extension, also let's rename it to `UploadStatusGroup.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/MyVideosView/NewVideoTile/NewVideoTile.style.ts
>  import styled from '@emotion/styled'
Let's rename it to `NewVideoTile.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/SignInJoinView/SignInMainView/SignInMainView.style.ts
>  import { Link } from 'react-router-dom'
Let's rename it to `SignInMainView.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/SignInJoinView/SignInProcessView/SignInProcessView.style.ts
>  import styled from '@emotion/styled'
Let's rename it to `SignInProcessView.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/SignInView/SignInView.style.ts
>  import styled from '@emotion/styled'
Let's rename it to `SignInView.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/VideoWorkspace/VideoWorkspace.style.ts
>  import styled from '@emotion/styled'
Let's rename it to `VideoWorkspace.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/studio/VideoWorkspace/VideoWorkspaceTabsBar/VideoWorkspaceTabsBar.style.ts
>  import styled from '@emotion/styled'
Let's rename it to `VideoWorkspaceTabsBar.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/viewer/ChannelView/ChannelAbout.style.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension, also let's rename it to `ChannelAbout.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/viewer/ChannelView/ChannelView.style.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension, also let's rename it to `ChannelView.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/viewer/SearchView/SearchResults/SearchResults.style.ts
>  import styled from '@emotion/styled'
Let's rename it to `SearchResults.styles.ts`

2021-11-15 11:35 UTC, wyrdrender commented on src/views/viewer/VideoView/VideoView.style.tsx
>  import styled from '@emotion/styled'
Get rid of `.tsx` extension, also let's rename it to `VideoView.styles.ts`

2021-11-15 15:20 UTC, eldiegod commented
- Buttons in to _buttons folder
- _loaders folder
- TSX to ts style files and style to styles

Not moving components into views yet I think is better to create another ticket to keep scope somewhat focused

Also not sure what to do with the _content folder

2021-11-16 11:45 UTC, drillprop commented
> Also not clear what to do with the _content folder

I'd just remove it, because it's unclear to me what we should keep here, but maybe someone have better idea.

2021-11-16 12:40 UTC, kdembler commented
Personally, I'd keep it and add the other components you mentioned to it. Maybe we could also move Gallery and other associated components in there?

2021-11-22 12:15 UTC, kdembler approved these changes

2021-11-22 17:49 UTC, wyrdrender approved these changes

2021-11-22 19:32 UTC, merged