Storybook housekeep
Joystream/atlas pull request #1592
Opened 2021-11-16 08:32 UTC by eldiegod

fixes: #1333

2021-11-16 14:22 UTC, kdembler requested changes
Okay, we will need to make changes here. It's hard for me to tell what exactly is the issue (I guess the new docgen plugin), but the build process is broken. Some stats to compare:
- Build time: ~40s -> ~2min
- RAM usage: 2.7GB -> 7GB 🤯
- `dist` size after build: 6MB -> 30MB 🤯

This is not acceptable just to make Storybook props work. So we either need to figure out what the issue is and fix it (there should be no build regression) or just use something different.

2021-11-17 16:29 UTC, drillprop commented
I don't think it works as it should. For instance, we still need to provide some default text, when the prop type is a `string`. You could try it yourself by removing `arg.title` from `src/shared/components/ChannelCardBase/ChannelCardBase.stories.tsx`.  You'll get something like this:
![image](https://user-images.githubusercontent.com/51168865/142235415-d09e2b0c-af76-42a7-b023-08882ff8d755.png)



Ideally, it should work just out of the box i.e. you shouldn't need to set args by yourself, and you should see here just text input.
I mean, It worked like that before when we had `create-react-app`.  To prove my words I just move back to the commit when we had CRA and this is how `TextArea` controls looked: 
![image](https://user-images.githubusercontent.com/51168865/142239472-86a0015f-be06-4a20-9436-48681b7814ee.png)
And we didn't need to provide `args` and `argTypes`, every control input was just automatically added. 

Not sure what to do with this. I'm a little worried that there is no solution to resolve this for now.

2021-11-17 16:30 UTC, kdembler commented
I just asked Diego to skip this part of the PR and we'll try to solve it at some later time

2021-11-18 15:18 UTC, drillprop commented on src/shared/components/OptionCard/OptionCard.stories.tsx
> +  title: 'other/OptionCard',
let's move this to `inputs`

2021-11-18 15:18 UTC, drillprop commented on src/shared/components/HelperText/HelperText.stories.tsx
> +  title: 'other/HelperText',
I think this one is used only for inputs. We could move it there

2021-11-18 15:18 UTC, drillprop commented on src/components/NoConnectionIndicator/NoConnectionIndicator.stories.tsx
> +  title: 'other/NoConnectionIndicator',
Maybe we should move it to overlays? I mean, it basically behaves like a modal

2021-11-18 15:18 UTC, drillprop commented on .storybook/main.ts
>      )
Just a suggestion: 
```tsx
    const ignoredPlugins = ['vite:react-babel', 'vite:react-refresh', 'vite:react-jsx', 'vite-plugin-checker']
    const filteredVitePlugins = vitePlugins.filter(
      (plugin) =>
        // @ts-ignore totally justified ignore
        !ignoredPlugins.includes(plugin.name)
    )
```

2021-11-19 08:28 UTC, drillprop approved these changes
Looks good to me, too bad we didn't bring back inferring arguments. I hope that future releases of storybook/storybook-vite-builder will resolve this.

2021-11-19 09:55 UTC, kdembler commented
Yeah I think it's just too much trouble to fix it ourselves at this point, hopefully support comes soon

2021-11-19 09:58 UTC, kdembler approved these changes

2021-11-19 09:58 UTC, merged