WIP Remove data stiching
Joystream/atlas pull request #1665
Opened 2021-11-26 12:36 UTC by drillprop

Fix #1632

2021-12-03 14:14 UTC, wyrdrender requested changes
Except those 2 comments, looks and workd really great. I really like this change!

2021-12-03 14:14 UTC, rafalpawlow commented on src/api/hooks/categoriesFeaturedVideos.ts
> +  id: string,
Nothing super important, but could we change arguments to be more meaningful? In this case `categoryId`

2021-12-03 14:14 UTC, rafalpawlow commented on src/views/viewer/HomeView.tsx
> +      <VideoHero videoHeroData={videoHero || null} withMuteButton />
Let's set default value in `useVideoHeroData`. WDYT?

2021-12-09 15:12 UTC, kdembler commented on src/api/queries/videos.graphql
> +    ...BasicVideoFields
We need to get the full fields here. Currently this query will not return all the details needed and then separate `GetVideo` will be executed for each of videos returned

2021-12-09 15:12 UTC, kdembler commented on src/api/hooks/video.ts
>  ) => {
Cannot comment on it, but there's a `useMostViewedVideosIds` function above that doesn't make sense anymore

2021-12-20 12:06 UTC, kdembler commented
Let's add a script to do a GraphQL introspection without the extension

2021-12-20 15:11 UTC, rafalpawlow approved these changes

2021-12-20 17:51 UTC, eldiegod approved these changes
added some small comments and looks good overall

2021-12-20 17:51 UTC, eldiegod commented on src/api/hooks/channel.ts
> +      },
I would put `...variables?.where` after public and censored flags so we can override them easily if necessary

2021-12-20 17:51 UTC, eldiegod commented on src/components/InfiniteGrids/InfiniteVideoGrid.tsx
> +  limit?: number
I suggest adding small comments on these to clarify what they do exactly

2021-12-20 17:51 UTC, eldiegod commented on src/components/InfiniteGrids/InfiniteVideoGrid.tsx
> +  excludeId?: string
also here; as this component gets more complex will serve as documentation

2021-12-20 17:51 UTC, eldiegod commented on src/components/_channel/ExpandableChannelsList/ExpandableChannelsList.tsx
> +  }
Maybe a switch statement would solve the issue?

2021-12-20 18:02 UTC, kdembler commented on src/components/_channel/ExpandableChannelsList/ExpandableChannelsList.tsx
> +  }
Switch is a conditional as well, it's the same issue

2021-12-20 18:20 UTC, eldiegod commented
Right

On Mon, Dec 20, 2021, 19:02 Klaudiusz Dembler ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> src/components/_channel/ExpandableChannelsList/ExpandableChannelsList.tsx
> <https://github.com/Joystream/atlas/pull/1665#discussion_r772568630>:
>
> > +  if (queryType === 'discover') {
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
> +    return useDiscoverChannels({}, commonOpts)
> +  } else if (queryType === 'popular') {
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
> +    return usePopularChannels({}, commonOpts)
> +  } else if (queryType === 'promising') {
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
> +    return usePromisingChannels({}, commonOpts)
> +  } else {
> +    // regular channels query needs explicit limit and sorting as it's not defined by Orion
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
> +    return useChannels({ limit: 15, orderBy: ChannelOrderByInput.CreatedAtAsc }, commonOpts)
> +  }
>
> Switch is a conditional as well, it's the same issue
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Joystream/atlas/pull/1665#discussion_r772568630>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACQ7TX432MAAOMXNPKMDFADUR5VUBANCNFSM5I2SIEEQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2021-12-20 18:54 UTC, merged