Fix wrong button order in dialogs
Joystream/atlas pull request #1706
Opened 2021-12-03 08:05 UTC by drillprop

Fix #1601 

I'm not sure, what's was the reason for using `order` here. Please double-check if removing this property breaks anything

2021-12-06 13:10 UTC, kdembler requested changes
The problem I was trying to solve with this `order` style was this: on mobile the order of the buttons should be primary on top, but on desktop the primary button should be on the right. If you open this PR in the storybook and take a look at dialog modal on small screen, you will see that the order of the buttons is incorrect

2021-12-07 08:48 UTC, drillprop commented
This is a little hacky, but it works. I used [direction](https://developer.mozilla.org/pl/docs/Web/CSS/direction) property, which is [well-supported](https://caniuse.com/?search=direction)

2021-12-07 10:28 UTC, kdembler commented on src/components/_overlays/Dialog/Dialog.styles.ts
> +    direction: rtl;
`direction` has a quite specific meaning and it supposed to be used only for different languages that use` rtl`. Let's find something else for styling

2021-12-08 10:52 UTC, kdembler approved these changes

2021-12-08 10:52 UTC, merged