Fix issue with showing connection indicator when refreshing
Joystream/atlas pull request #1708
Opened 2021-12-03 11:43 UTC by drillprop

Fix #761

2021-12-06 11:00 UTC, wyrdrender approved these changes

2021-12-06 11:28 UTC, kdembler requested changes
With this change if node looses connection, we will run `joystream?.destroy()` which hasn't happened before. I'm not sure if this is desired and I think testing it would be outside of scope of this issue. Can we instead just add a visual delay of the banner showing of like `1s`?

2021-12-07 10:17 UTC, drillprop commented
I don't think one second is enough, I set this to two and a half seconds. I reverted previous changes as well.

2021-12-07 21:30 UTC, kdembler approved these changes

2021-12-07 21:30 UTC, merged