Update top bar
Joystream/atlas pull request #1771
Opened 2021-12-08 13:28 UTC by wyrdrender

User / channel icons are not in scope
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3173%3A135755

2021-12-10 15:54 UTC, drillprop requested changes

2021-12-10 15:54 UTC, drillprop commented on src/components/_navigation/TopbarBase/TopbarBase.styles.ts
> +    grid-template-columns: auto 480px 146px;
What if we change this to `1fr 480px 1fr`? I really don't like this 146px

2021-12-10 15:54 UTC, drillprop commented on src/components/_navigation/TopbarViewer/TopbarViewer.tsx
> +          </>
```suggestion
          <StyledIconButton onClick={handleLogging}>Sign up</StyledIconButton>
```
You don't need fragment here

2021-12-10 16:14 UTC, drillprop approved these changes
LGTM!

2021-12-13 09:31 UTC, kdembler commented on src/components/_icons/Bulb.tsx
> +export const SvgBulb = React.memo((props: React.SVGProps<SVGSVGElement>) => (
The icons need to be re-generated because this uses some incorrect namings

2021-12-13 11:29 UTC, kdembler commented on package.json
> +    "rimraf": "^3.0.2",
Let's move this to dev dependencies

2021-12-13 11:29 UTC, kdembler commented on package.json
> +    "svgs:icons-generate": "rimraf src/components/_icons/*.tsx && svgr --config-file svgr.config.js -d src/components/_icons src/components/_icons/svgs && prettier --write src/components/_icons",
This removed `icons.stories` unfortunately

2021-12-13 13:35 UTC, kdembler approved these changes

2021-12-13 13:36 UTC, merged