Vitest testing set up
Joystream/atlas pull request #1832
Opened 2021-12-21 18:26 UTC by eldiegod

POC: Introduce basic unit tests

 Fixes: #1765

There are some improvements to be done on the test watching and
some annoying eslint warnings appear too but the rest looks good; 
should be a matter of tweaking the vite config

2021-12-22 09:38 UTC, kdembler requested changes
Main app build is failing

2022-01-11 15:29 UTC, rafalpawlow commented
Good job, works really good! However I think we should add this to github actions. @kdembler WDYT?

2022-01-11 15:29 UTC, rafalpawlow approved these changes

2022-01-11 15:33 UTC, rafalpawlow commented on package.json
> +    "test": "vitest -w"
I wonder if we should add also non-watching script with `--run` flag. For the purposes of CI/CD pipeplines. But not sure if this is needed.

2022-01-13 10:07 UTC, kdembler reviewed
Looks all good, really cool that you found a solution based on Vite. I think we should go with Rafał's suggestion and add it as part of Github action checks

2022-01-13 10:07 UTC, kdembler commented on package.json
> +    "test": "vitest -w"
Yes, we should have something like that as well. I propose `test:run` and `test:watch`

2022-01-13 18:49 UTC, eldiegod commented
Apparently we don't need to specify watch or run for CI environment as it is handled automatically:

![imagen](https://user-images.githubusercontent.com/10615263/149325143-1d014e03-e24e-4456-8fb3-315f4fafe562.png)

So `test` command should work for CI and as `--watch` locally, I did add dev mode command as `test:dev` thought I'm not 100% sure what the difference is from `--watch`

2022-01-14 08:40 UTC, kdembler commented on .github/workflows/checks.yml
> +  test:
I think we could just add a single step to the job we already have? We would save quite some time because we don't have to run `yarn install` 2 times

2022-01-14 09:35 UTC, kdembler approved these changes

2022-01-14 09:35 UTC, merged