Avatar group
Joystream/atlas pull request #1837
Opened 2021-12-24 08:50 UTC by drillprop

Fix #1778

2021-12-28 19:42 UTC, rafalpawlow requested changes
I think they have an incorrect offset e.g In figma `40px` variant has `8px` offset but you added only `4px`. Or I don't understand figma measurements correctly
![Zrzut ekranu 2021-12-28 o 20 41 38](https://user-images.githubusercontent.com/13706246/147601436-55423d91-ac9b-449d-9b89-b3288bfe349e.png)

2021-12-28 19:49 UTC, rafalpawlow commented
Also labels are not centered correctly
![Zrzut ekranu 2021-12-28 o 20 44 54](https://user-images.githubusercontent.com/13706246/147601895-238a5f83-49aa-4794-a0c7-99ef416f9580.png)

2021-12-29 10:11 UTC, rafalpawlow requested changes

2021-12-29 10:11 UTC, rafalpawlow commented on src/components/Avatar/AvatarGroup.stories.tsx
> +    clickable: {
```suggestion
    clickable: { type: 'boolean', defaultValue: true }
```

2021-12-30 12:01 UTC, rafalpawlow approved these changes

2021-12-30 12:03 UTC, rafalpawlow commented on src/components/Avatar/AvatarGroup.styles.ts
> +  background-color: black;
I think this black should come from variable

2022-01-03 13:38 UTC, toiletgranny commented
Everything seems to be fine, hurray! 🎉 Just two quick questions/notes:
1. Is my understanding correct that the color of the outline of each avatar is meant to be a variable that can be easily overridden?
2. Is it just me, or the size labels on Storybook are broken? 😅 `default`, `bid`, `small`?

2022-01-03 13:39 UTC, toiletgranny approved these changes

2022-01-04 10:50 UTC, merged