Update OptionCard component
Joystream/atlas pull request #1896
Opened 2022-01-11 14:17 UTC by eldiegod

fixes: #1676

figma: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4118%3A144975

2022-01-13 17:51 UTC, rafalpawlow requested changes
In figma, radio component doesn't inherit error state
![Zrzut ekranu 2022-01-13 o 18 49 39](https://user-images.githubusercontent.com/13706246/149382755-55cb7247-999f-422d-8301-a2f4e12dd459.png)

Another thing is, in figma we have two types of option card `Radio` and `Checkbox`. Second one is missing in your PR.

2022-01-13 18:02 UTC, rafalpawlow commented
Figma says: `In the Option card component, the display limit for both the main label is set to 1 line of text. Upon exceeding this limit, the text should be trimmed and ended with an ellipsis.`. But current implementation allows 2 lines of text
![Zrzut ekranu 2022-01-13 o 19 00 47](https://user-images.githubusercontent.com/13706246/149384390-91608566-06f6-4797-baf6-8953faf9c9eb.png)

2022-01-13 18:06 UTC, rafalpawlow requested changes

2022-01-13 18:06 UTC, rafalpawlow commented on src/components/_inputs/OptionCard/OptionCard.stories.tsx
> +    <div style={{ display: 'grid', gridTemplateColumns: 'auto auto auto', gap: '16px' }}>
In figma we have 2 gaps depending on the breakpoint `16px` and `24px`. Also I think we should move `Option card group` as a separate component.

2022-01-13 18:11 UTC, rafalpawlow commented
I'm not sure about spacing between text and hovered input. @toiletgranny is that fine?
![Zrzut ekranu 2022-01-13 o 19 09 48](https://user-images.githubusercontent.com/13706246/149385456-b4e3b0de-7cb5-484f-8da6-070cd2cfb584.png)

2022-01-13 18:34 UTC, rafalpawlow commented
Border colors are wrong
we should use the following:

**white**
default: `colorBorderAlpha`
hover: `colorBorderStrongAlpha`
pressed: `colorBorderMutedAlpha`

**error**
hover: `colorCoreRed300`
default: `colorCoreRed500`
pressed: `colorCoreRed700`

currently we use `colorCoreRed400` for all variants

**blue**
hover: `colorCoreBlue300`
pressed: `colorCoreBlue700`

2022-01-14 08:36 UTC, toiletgranny commented
I agree with everything @rafalpawlow pointed out here, and to answer/comment on some of the points he brought up:
1. Yes, the spacing between the label and the Radio button/Checkbox should be `16px`, awesome catch! This can be inspected in Figma, though it might be tricky.
2. It's great to see text & icon colors using our new design tokens, but @rafalpawlow is right that we forgot about borders. Especially in "the error state". In case that's helpful, @eldiegod I put up this quick prototype for you as a quick reference on how border colors are changing upon hovering and pressing the Option card component.


https://www.figma.com/proto/Pf31tuYpozYmpq163U2ho8/Web-Components?page-id=4645%3A137109&node-id=4645%3A137110&viewport=396%2C48%2C1&scaling=min-zoom&starting-point-node-id=4645%3A137110

2022-01-17 14:16 UTC, eldiegod commented
@rafalpawlow @toiletgranny I think I have addressed all the comments except for the optionCardGroup components as I'm not sure it should be done here or it's a matter for another ticket.

Saying it because the initial complexity scope for this ticket was a 2 but it has gotten a bit intricate so not sure if we just missed that or we are doing more than planned

2022-01-17 14:27 UTC, rafalpawlow commented
@eldiegod component still allows for 2 lines of title

2022-01-17 14:54 UTC, rafalpawlow commented
Something is wrong with input when there is a lot of text ant card is in `active` state
![Zrzut ekranu 2022-01-17 o 15 53 11](https://user-images.githubusercontent.com/13706246/149791781-446f3ea6-d65f-4dda-ba99-6d175a31fad9.png)

2022-01-17 15:47 UTC, eldiegod commented
> Something is wrong with input when there is a lot of text ant card is in `active` state

Can you tell me exactly what you mean with wrong?

2022-01-17 15:49 UTC, rafalpawlow commented
@eldiegod Look at the screenshot, radio button is not round, it is egg-shaped

2022-01-17 15:51 UTC, eldiegod commented
> @eldiegod Look at the screenshot, radio button is not round, it is egg-shaped

wanted to make sure, I think I fixed it now @rafalpawlow

2022-01-18 12:05 UTC, rafalpawlow approved these changes
Looks good! However I found one more thing which we probably should tackle in another issue. Pressed radio component looks a little bit different in figma:

![Zrzut ekranu 2022-01-18 o 13 04 19](https://user-images.githubusercontent.com/13706246/149934320-a88d31cc-28ec-474f-baf3-f46c218a6545.png)
![Zrzut ekranu 2022-01-18 o 13 04 57](https://user-images.githubusercontent.com/13706246/149934322-597c744f-5de2-419a-826d-95f2f0d391b0.png)

2022-01-18 13:12 UTC, eldiegod commented
> Looks good! However I found one more thing which we probably should tackle in another issue. Pressed radio component looks a little bit different in figma:
> 
> ![Zrzut ekranu 2022-01-18 o 13 04 19](https://user-images.githubusercontent.com/13706246/149934320-a88d31cc-28ec-474f-baf3-f46c218a6545.png) ![Zrzut ekranu 2022-01-18 o 13 04 57](https://user-images.githubusercontent.com/13706246/149934322-597c744f-5de2-419a-826d-95f2f0d391b0.png)

@rafalpawlow Awesome! Yep that's right, that would be more of an existing issue with the `RadioInput` component itself

2022-01-18 15:12 UTC, kdembler commented
@eldiegod Could you please create an issue for this difference? We may have missed that

2022-01-18 15:12 UTC, merged