1710 - update side navigation
Joystream/atlas pull request #2026
Opened 2022-01-28 09:39 UTC by lcoenengithub

**What is this?**

This update sign up flow to include direct link to signing in in the main view.

**Issue**

https://github.com/Joystream/atlas/issues/1710

**Illustration**

![image](https://user-images.githubusercontent.com/96242244/151013282-e0157147-33f1-4188-a9c1-78132137fc79.png)
![image](https://user-images.githubusercontent.com/96242244/151016637-b148745a-c979-4fb5-a767-3822e83b8cfa.png)
![image](https://user-images.githubusercontent.com/96242244/151016904-6dec5774-5ed3-487a-9287-292212a75d85.png)

2022-01-28 09:53 UTC, kdembler requested changes
Couple points:
1. There are some unneeded comments left in the codebase

2. The colors of icons in inactive nav items are wrong

3. Logo position in sidenav is incorrect
<img width="349" alt="Screenshot 2022-01-28 at 10 48 12" src="https://user-images.githubusercontent.com/12646744/151525260-84395002-2463-4e9d-9dfb-d542dc80d63a.png">

4. Typography for items at the bottom (`Terms of Service`, etc) is incorrect

5. Spacing of the bottom section (links and buttons) is incorrect

6. We're missing one border in the bottom section and one is incorrect color

7. The sidenav expand animation looks worse than it did previously. There are a number of layout shifts happening during expanding. See:

https://user-images.githubusercontent.com/12646744/151525537-89f2f687-2fca-4718-9946-22a1ab87d720.mov

Compare with production version:

https://user-images.githubusercontent.com/12646744/151525611-d65662c7-8ebb-4f7e-a87b-5f47d82713f2.mov

2022-01-28 10:34 UTC, rafalpawlow requested changes

2022-01-28 10:34 UTC, rafalpawlow commented on packages/atlas/src/components/_channel/ChannelLink/ChannelLink.styles.ts
>  const secondaryTextCss = `
I guess we can remove it since it's not needed anymore

2022-01-31 14:51 UTC, lcoenengithub commented
@kdembler I think I'm done, it took me a bit of time to understand where the animation issue came from.

2022-02-01 15:44 UTC, closed without merging