drop support for multiple tabs in VideoWorkspace
Joystream/atlas pull request #2060
Opened 2022-02-01 18:40 UTC by rafalpawlow

2022-02-02 07:59 UTC, drillprop requested changes
In terms of functionality works pretty well. Found some small issues!
Also:
![image](https://user-images.githubusercontent.com/51168865/152114805-6d70a460-ae61-41fc-8b94-352e4469f3a0.png)
This feels good in VideoWorkspace!
![image](https://user-images.githubusercontent.com/51168865/152114923-a73336d4-4a7c-4a2f-9b1f-13061add5848.png)

2022-02-02 07:59 UTC, drillprop commented on packages/atlas/src/components/DrawerHeader/DrawerHeader.tsx
> +type TabsBarProps = {
```suggestion
type DrawerHeaderProps = {
```

2022-02-02 07:59 UTC, drillprop commented on packages/atlas/src/components/DrawerHeader/DrawerHeader.tsx
> +export const DrawerHeader: React.FC<TabsBarProps> = React.memo(({ onCloseClick, title, label }) => {
```suggestion
export const DrawerHeader: React.FC<DrawerHeaderProps> = React.memo(({ onCloseClick, title, label }) => {
```

2022-02-02 07:59 UTC, drillprop commented on packages/atlas/src/components/DrawerHeader/DrawerHeader.tsx
> +    <Topbar>
Let's name this differently, maybe `Tabbar`?

2022-02-02 07:59 UTC, drillprop commented on packages/atlas/src/components/DrawerHeader/DrawerHeader.tsx
> +      <TabsContainer ref={tabsContainerRef}>
Do we really need three wrappers here? We have here TabsContainer, TabWrapper and Tab. Just asking out of curiosity. 
Also, I think it should be named TabContainer, not Tab**s**Container(without plural form)

2022-02-02 07:59 UTC, drillprop commented on packages/atlas/src/components/DrawerHeader/DrawerHeader.tsx
> +      <ButtonsContainer>
Again, do we need a wrapper here? I think we could easily create `StyledIconButton`

2022-02-02 09:16 UTC, rafalpawlow commented on packages/atlas/src/components/DrawerHeader/DrawerHeader.tsx
> +type TabsBarProps = {
Not copy paste at all 😬

2022-02-02 10:37 UTC, drillprop reviewed
You missed those

2022-02-02 10:37 UTC, drillprop commented on packages/atlas/src/components/DrawerHeader/DrawerHeader.tsx
> +  const tabsContainerRef = useRef<HTMLDivElement>(null)
```suggestion
  const tabContainerRef = useRef<HTMLDivElement>(null)
```

2022-02-02 10:37 UTC, drillprop commented on packages/atlas/src/components/DrawerHeader/DrawerHeader.tsx
> +      <TabContainer ref={tabsContainerRef}>
```suggestion
      <TabContainer ref={tabContainerRef}>
```

2022-02-02 13:22 UTC, drillprop approved these changes

2022-02-03 11:50 UTC, eldiegod commented
Looks great with no tabs 🤓

2022-02-04 21:30 UTC, kdembler commented
Will take a look at this once we release new sign in flow so `dev` is "clear"

2022-02-09 15:58 UTC, kdembler approved these changes

2022-02-09 17:14 UTC, merged