video page cinematic view
Joystream/atlas pull request #2081
Opened 2022-02-08 13:54 UTC by rafalpawlow

closes #1959 

https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1211%3A87658

2022-02-09 12:40 UTC, drillprop requested changes
In terms of functionality works pretty well. I think we could also add a hotkey for the cinema view.  On youtube, if you want to enable cinema view, you can press  `T` key.
I see one visual issue though. The space between the top bar and the `More from channel` section is way too small. Not sure how we should tackle this, in the design there is a different section here. I think you'll need to consult this with a designer.
![image](https://user-images.githubusercontent.com/51168865/153202208-d2f56182-9aae-4ee6-b82b-16d897713b69.png)

As for the code, I'll look later at when the PR will be ready for review.

2022-02-09 12:45 UTC, drillprop commented
Wait, I didn't spot this earlier. The space between the top bar and video needs to be changed when we're not in cinema mode: 
Look: 
![image](https://user-images.githubusercontent.com/51168865/153203554-160bee0b-9fa9-467f-a1df-33efa20649c0.png)

![image](https://user-images.githubusercontent.com/51168865/153203638-3a979cc6-caf0-4bc2-8652-eccfa444a548.png)

2022-02-14 12:32 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/VideoView.styles.ts
> +import { LayoutGrid } from '@/components/LayoutGrid'
Take a look at https://github.com/Joystream/atlas/pull/2115

2022-02-14 12:54 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/VideoView.styles.ts
> +export const PlyerGridWrapper = styled(LimitedWidthContainer)<CinematicView>`
typo in the component name

2022-02-14 12:54 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/VideoView.styles.ts
> +  margin-bottom: ${({ cinematicView }) => cinematicView && sizes(8)};
Let's use separate css block for cinematic view styles, as per styleguide

2022-02-14 12:54 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/VideoView.styles.ts
> +    padding-top: ${({ cinematicView }) => !cinematicView && sizes(16)};
Same here, let's move all conditional styles to a single block to avoid all of those conditions

2022-02-14 12:54 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/VideoView.styles.ts
> +    margin-bottom: ${({ cinematicView }) => !cinematicView && sizes(8)};
Same here

2022-02-14 12:54 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/VideoView.tsx
> +    return (pixelHeight || 0) / (pixelWidth || 0)
0 may not be the best default when it comes to division 😅 Maybe just default to `DEFAULT_ASPECT_RATIO` if any of the values is missing?

2022-02-15 12:21 UTC, drillprop requested changes
1. I think we missed one thing when you worked on the `More videos section`. It seems that it's showing videos that are supposed to be private. You can see it yourself by going to  `/channel/6?tab=Videos` and clicking the first video. Could you fix this in this PR or create an issue? 
2. I can't watch videos on mobile anymore. Not sure where it comes from. Look: 
![image](https://user-images.githubusercontent.com/51168865/154055380-e4dcb4ab-c9ba-492b-a66a-6da0ab7f6059.png)

2022-02-15 12:21 UTC, drillprop commented on packages/atlas/src/components/_video/VideoPlayer/utils.ts
> +      break
let's just `return` here, as I did above.

2022-02-15 12:44 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/MoreVideos.tsx
> +    where: { ...where, isPublic_eq: true },
We need couple more conditions here, let's add them directly in the hook implementation. You can find necessary conditions in other hooks in the same file, for example `useTop10VideosThisWeek`

2022-02-15 13:05 UTC, drillprop approved these changes

2022-02-15 14:47 UTC, kdembler approved these changes

2022-02-15 14:47 UTC, merged