Issue NFT view
Joystream/atlas pull request #2088
Opened 2022-02-09 10:45 UTC by drillprop

Fix #1925

Designs: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=844%3A18760

FYI Adding a form is not in the scope of this task.

2022-02-10 12:15 UTC, drillprop commented
I need to convert this to a draft. I see some issues with ActionBar

2022-02-16 13:10 UTC, rafalpawlow requested changes

2022-02-16 13:10 UTC, rafalpawlow commented on packages/atlas/src/components/ActionBar/ActionBar.stories.tsx
>      fee: 1,
let's remove it, we don't have `fee` prop in `ActionBar`

2022-02-16 15:17 UTC, rafalpawlow approved these changes

2022-02-18 11:21 UTC, kdembler approved these changes

2022-02-18 11:35 UTC, merged