feat: add snackbar on URL copy
Joystream/atlas pull request #2183
Opened 2022-02-23 15:49 UTC by lcoenengithub

**What is this?**

This adds a snackbar message at video URL copy

**Illustration**

2022-02-24 13:55 UTC, drillprop requested changes
Couple things:
- we should use `dev` as a base branch.
- snackbar should have an icon: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=792%3A31187 
- snackbar should be displayed also when you copy the URL in VideoTilePublisher. You missed this.
- I would add a snack bar also in MembershipInfo. We're copying the address there.  Maybe we could create a hook(`useCopyToClipboard`) that will be handling copying to the clipboard and displaying the snack bar. @kdembler wdyt?

2022-02-24 13:55 UTC, drillprop commented on packages/atlas/src/components/_video/VideoTileViewer/VideoTileViewer.tsx
> +import { useSnackbar } from '../../../providers/snackbars/snackbar'
you should use: 
```
import { useSnackbar } from '@/providers/snackbars'
```

2022-02-24 14:01 UTC, drillprop commented
Also, I have one more request. Maybe it's just oversight, but please add the link to the issue and to the design(if it's available) in your PRs.

2022-02-24 14:54 UTC, kdembler commented
> I would add a snack bar also in MembershipInfo. We're copying the address there. Maybe we could create a hook(useCopyToClipboard) that will be handling copying to the clipboard and displaying the snack bar. @kdembler wdyt?

Very good point, agreed

2022-02-24 17:08 UTC, lcoenengithub commented
@drillprop @kdembler thanks! I applied your points.

2022-02-25 13:04 UTC, drillprop requested changes
Works well 👍🏻 , just one thing left

2022-02-25 13:04 UTC, drillprop commented on packages/atlas/src/providers/clipboard/hooks.ts
> +    },
Firstly, I think, this should be "Video URL copied to clipboard". 

Secondly, when you click the copy button on the member page, you're copying the account address, not the video URL.
![image](https://user-images.githubusercontent.com/51168865/155718808-7c445558-a63e-48f2-ab56-0f1d38527b89.png)
You need to add one more parameter to `copyToClipboard` function to display the correct information. Something like: 
```tsx
copyToClipboard: (text: string, snackbarText: string) => {
      copyToClipboard(text)
      displaySnackbar({ title: snackbarText, iconType: 'info' })
    },
```

2022-02-28 12:39 UTC, lcoenengithub commented on packages/atlas/src/providers/clipboard/hooks.ts
> +    },
Thanks @drillprops, I fixed it (I added some args with default values).

2022-02-28 15:02 UTC, drillprop requested changes

2022-02-28 15:02 UTC, drillprop commented on packages/atlas/src/providers/clipboard/hooks.ts
> +    copyToClipboard: (text: string, title = 'Video URL copied to clipboard', iconType: SnackbarIconType = 'info') => {
hmm, I don't think we need to add `iconType` as a parameter - this should be always an informational snack bar.  I don't see the reason why we would change that. 

I also don't agree that we should set the default title.

2022-02-28 15:02 UTC, drillprop commented on packages/atlas/src/components/MembershipInfo/MembershipInfo.tsx
> +  const { copyToClipboard } = useClipboard()
we need to pass suitable snackbarText on line 57 i.e: `Account address copied to clipboard`

2022-03-01 11:25 UTC, drillprop commented
@lcoenengithub I'm confused,  you requested my review, but I don't see any new commits or comments.  That was a misclick or did you forget to push your changes?

2022-03-01 16:33 UTC, lcoenengithub commented
> @lcoenengithub I'm confused, you requested my review, but I don't see any new commits or comments. That was a misclick or did you forget to push your changes?

Hey! Sorry, I forgot to push indeed :)

2022-03-01 16:44 UTC, drillprop requested changes

2022-03-01 16:44 UTC, drillprop commented on packages/atlas/src/components/MembershipInfo/MembershipInfo.tsx
> +    copyToClipboard(address, 'Video URL copied to clipboard')
```suggestion
    copyToClipboard(address, 'Account address copied to clipboard')
```

2022-03-03 09:51 UTC, kdembler commented on packages/atlas/src/providers/clipboard/hooks.ts
> +export const useClipboard = () => {
This isn't a provider though, right? We keep only context providers in `src/providers`, I think this hook makes more sense in `src/hooks`

2022-03-03 09:59 UTC, lcoenengithub commented on packages/atlas/src/providers/clipboard/hooks.ts
> +export const useClipboard = () => {
Good point!

2022-03-03 10:21 UTC, lcoenengithub commented on packages/atlas/src/providers/clipboard/hooks.ts
> +export const useClipboard = () => {
Good point, I moved it there!

2022-03-03 10:29 UTC, drillprop approved these changes

2022-03-03 10:53 UTC, kdembler commented on packages/atlas/src/hooks/clipboard/hooks.ts
> +import { useSnackbar } from '@/providers/snackbars'
It's in `hooks/` now but it doesn't match how we files in that directory, please take a look at other hooks

2022-03-04 13:13 UTC, kdembler approved these changes

2022-03-04 13:48 UTC, merged