Improve numbered carousels
Joystream/atlas pull request #2219
Opened 2022-03-04 15:10 UTC by kdembler

Resolves #1595

2022-03-07 16:47 UTC, toiletgranny commented
_A fly does not sit._ I have nothing more to add, it's just perfect. 

There was this one thing I asked for back in #2148, which was clipping carousels on the edges and if we can do something about it:
> The scrollable contents of carousels are clipped at the edges, not allowing the numbered tile components to reach the edge of the viewport. In the designs, the contents of the carousels span beautifully from one edge of the viewport to another. Can we have that in the implementation since we're revisiting this component? Ideally, the inner padding in the carousel matches the globally applied one, which is 16px up until the MD breakpoint, and then 32px going forward.

Do you reckon it's something we could tackle while we are here?

2022-03-07 16:51 UTC, kdembler commented
The issue you mentioned has actually been with us since the very beginning of Atlas I think, solving this may be outside of the scope of this specific problem

2022-03-08 08:30 UTC, toiletgranny approved these changes
>The issue you mentioned has actually been with us since the very beginning of Atlas I think, solving this may be outside of the scope of this specific problem

Ah, of course, I understand. In my head, as I was experimenting with this myself, the solution seemed quite straightforward ([see the recording](https://cln.sh/HKSQUU), and the code snippet below), but if there are other implications we need to be careful about, then sure — let's tackle this some other time.

```
margin: 0 calc(var(--size-global-horizontal-padding) * -1);
padding: 0 var(--size-global-horizontal-padding);
```

2022-03-08 10:51 UTC, kdembler commented
I'm not able to replicate what you're showing in the video. Applying the CSS you provided I see that on some breakpoints some of the tiles get cut. This likely interfere with the size calculations the carousel is doing to know how many items to fit and how wide they should be.

2022-03-09 18:14 UTC, rafalpawlow requested changes

2022-03-09 18:14 UTC, rafalpawlow commented on packages/atlas/src/components/Carousel/Carousel.styles.ts
> +  margin-top: 48px;
Didn't we agree for margins and padding we use `sizes`?

2022-03-09 18:48 UTC, kdembler commented on packages/atlas/src/components/Carousel/Carousel.styles.ts
> +  margin-top: 48px;
You're correct, fixed now

2022-03-10 10:13 UTC, rafalpawlow approved these changes

2022-03-10 10:15 UTC, merged