update nft widget timers
Joystream/atlas pull request #2367
Opened 2022-03-28 15:22 UTC by rafalpawlow

Closes #2329

**Design**
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A112135

2022-03-30 11:14 UTC, eldiegod requested changes
The screenshot below is video 46 and it doesn't show a timer even tho is a running English auction.

![Screenshot 2022-03-29 at 21 58 30](https://user-images.githubusercontent.com/10615263/160697191-c36424ab-7b85-4e37-97fa-c2dba092acd4.png)

As you can see in the video below the loading state for the timer is coming in way too late we should be showing a loading state for the timer as soon as we get the Nft data that tells us this is an English auction

https://www.loom.com/share/275127eeb4244bddb414c6a244ef5172

On the screenshot below, the timer, when there are less than 24 hours till the auction starts, is not updating once per second as we would like it to.

I was thinking if we should just move all the logic related to auction expired, running, upcoming.. to the timer component and handle it there.
As it will rerender itself every second like we need it to and will shave off some complexity from the main component.
Wdyt? 
I can explain in a call if needed too

![Screenshot 2022-03-29 at 22 28 22](https://user-images.githubusercontent.com/10615263/160701254-d66c43fc-e812-4583-bab3-7df248decb1d.png)

2022-03-30 11:14 UTC, eldiegod commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +const SMALL_VARIANT_MAXIMUM_SIZE = 340
Why are we changing the sizing breakpoint?

2022-03-30 11:14 UTC, eldiegod commented on packages/atlas/src/hooks/useBlockTimeEstimation.ts
> +      const currentBlockMsTimestamp = getCurrentBlockMsTimestamp()
we need to move away from `getCurrentBlockMsTimestamp()` which doesn;t updates because is a ref and instead use an `useState` just like we do for `currentBlock`

2022-03-30 11:14 UTC, eldiegod commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +                      <Text variant={size === 'medium' ? 'h600' : 'h400'} secondary>
the variant you are looking for is this `contentTextVariant`

2022-03-30 11:14 UTC, eldiegod commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +        : 0
this state you can put directly under the `auction` switch case

2022-03-30 11:14 UTC, eldiegod commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +                      <Text variant={size === 'medium' ? 'h600' : 'h400'} secondary>
same as above use the `contentTextVariant`

2022-03-30 11:14 UTC, eldiegod commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +        : 0
then you can also remove the check `nftStatus?.status === 'auction' &&`

2022-03-30 11:14 UTC, eldiegod commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +    const timerColumnSpan = 2
this has to be `size === 'small' ? 1 : 2` just like the `buttonColumnSpan` otherwise the layout breaks on small variant

2022-03-30 11:19 UTC, rafalpawlow commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +const SMALL_VARIANT_MAXIMUM_SIZE = 340
Yeah, I knew this will concern you. That's because we changed font size of timer and for example this: `5 Mar 2022 at 12:00` is too long for `281`

2022-03-31 18:02 UTC, rafalpawlow commented
> I was thinking if we should just move all the logic related to auction expired, running, upcoming.. to the timer component and handle it there.

@eldiegod I'm not sure if this is a good idea, we don't use `NftTimerItem` component for all time values, for example upcoming uses `NftInfoItem`. BTW, what

2022-04-05 11:45 UTC, eldiegod approved these changes
looks good now !

2022-04-05 11:48 UTC, eldiegod commented
Tho we will probably need to do something in another PR about the action buttons that now also depend on timers, tho we should probably be getting `englishTimerState` from the query node in the first place, wdyt @kdembler ?

2022-04-05 12:04 UTC, kdembler commented
You need to unpack this a bit @eldiegod:

> action buttons that now also depend on timers

what do you mean?

> tho we should probably be getting `englishTimerState` from the query node in the first place

same, what do you mean here? We load timers locally in the app so that state cannot be served by the query node

2022-04-05 12:15 UTC, eldiegod commented
@kdembler 
Check the action buttons on this vid, for example, it will make it clear

https://atlas-lf69rckhh-joystream.vercel.app/video/46

happens because we don't know the state of the English auction from the payload.

Maybe I meant runtime I get confused by both often, but we should be able to know in the payload if an English auction is currently running, expired, or upcoming before we load timers locally.

2022-04-05 13:15 UTC, kdembler commented
Ah I see what you mean now. Query node actually doesn't know when the auction has expired, same for runtime. If you try to place a bid after it has expired, a check will see that `current_block > expire_block` so the runtime will not allow it. But there isn't any state that says "okay this auction is expired now". QN could support that on its own, but it currently doesn't and I don't think it's realistic waiting for yet another feature so we will need to handle this locally. If there's a design issue, can you raise it with Adam @eldiegod?

I'm merging in the meantime since it's approved

2022-04-05 13:15 UTC, merged