Info text about user bids below buttons
Joystream/atlas pull request #2372
Opened 2022-03-28 21:07 UTC by eldiegod

fixes: #2371

2022-03-30 11:26 UTC, drillprop requested changes

2022-03-30 11:26 UTC, drillprop commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +    const WithdrawLastBid = ({ secondary }: { secondary?: boolean }) =>
Can we name this differently? WithdrawBidFromPreviousAuction maybe?

2022-03-30 11:26 UTC, drillprop commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +              {formatDateTime(bidFromPreviousAuction.createdAt)}
The app is breaking and I can't do anything when I go to the video with an open auction with my bid added. I'm getting: 
![image](https://user-images.githubusercontent.com/51168865/160823150-a9f6638b-d5d8-4acf-8d57-c32bd9c206cf.png)
I assume that it comes from here.

2022-03-30 13:17 UTC, eldiegod commented
Added suggestions, removed double settle buttons bug, and added bidlock info text

2022-03-31 06:45 UTC, drillprop approved these changes
I will need your changes in my "withdraw bid" PR, so let's merge this earlier. Looks good to me!

2022-03-31 08:17 UTC, merged