Update purchase view
Joystream/atlas pull request #2377
Opened 2022-03-30 10:31 UTC by drillprop

Fix #2224 

Draft, changing bid flow not included yet

2022-03-31 18:16 UTC, rafalpawlow requested changes
Overall looks good, however I'm not sure about scrolling. Now when we have vertical scroll, it scrolls nft tile with form together, previously only form was scrollable. Did you confirm this behavior with the designers?

2022-03-31 18:16 UTC, rafalpawlow commented on packages/atlas/src/views/global/NftPurchaseBottomDrawer/NftPurchaseBottomDrawer.styles.ts
> +  z-index: 10;
let's use `z-index` from our utils

2022-04-03 14:39 UTC, rafalpawlow requested changes
You are using wrong JoyTokenIcon variant inside input.

2022-04-05 16:26 UTC, rafalpawlow approved these changes

2022-04-06 13:07 UTC, kdembler reviewed
1. There are some alignment issues with the payment split and the Joystream logo:
![Screenshot 2022-04-06 at 14 14 42](https://user-images.githubusercontent.com/12646744/161972543-bfc421ee-0d9b-4e76-a98b-1554af95eb49.jpg)
2. The "Top bid" header uses H100 in the design, we have H300

2022-04-06 16:48 UTC, kdembler approved these changes

2022-04-06 16:48 UTC, merged