disable video form inputs when editing nft
Joystream/atlas pull request #2380
Opened 2022-03-30 13:37 UTC by rafalpawlow

Closes #2297 

**Design**
https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1332%3A97483

2022-03-30 14:22 UTC, kdembler commented on packages/atlas/src/views/studio/VideoWorkspace/VideoForm/VideoForm.styles.ts
> +  opacity: 0.5;
I don't think that's desired?

2022-03-30 14:25 UTC, kdembler commented
Also this scenario doesn't work:
1. I open edit for a video that doesn't have an NFT yet
2. I toggle "Mint an NFT"
3. The form becomes uneditable immediately
This should only happen if the NFT has already been minted in the past

2022-04-01 12:37 UTC, drillprop requested changes
I still can edit the thumbnail. You need to disable also MultifileSelect. 

Besides that, looks good, found only some minor issues.

2022-04-01 12:37 UTC, drillprop commented on packages/atlas/src/views/studio/VideoWorkspace/VideoForm/VideoForm.styles.ts
> +  margin-top: ${({ disabled }) => disabled && '40px'};
let's use `sizes` here. Also if we leave that, we will have `margin-top: false`, which is not great.

2022-04-01 12:37 UTC, drillprop commented on packages/atlas/src/views/studio/VideoWorkspace/VideoForm/VideoForm.tsx
> +                      <YellowText variant="t200">editing options of this video will be disabled</YellowText>
I think this is my code, but I'm pretty sure that we can put YellowText inside Text i.e. `<Text>< YellowText></Text>`. Could you do that?

2022-04-01 12:37 UTC, drillprop commented on packages/atlas/src/views/studio/VideoWorkspace/VideoForm/VideoForm.tsx
> +                      <VideoLink to={absoluteRoutes.viewer.video(editedVideoInfo.id)}>go to it's video page.</VideoLink>
same as above

2022-04-04 14:44 UTC, drillprop approved these changes

2022-04-04 21:35 UTC, merged