Create ReactionStepper component
Joystream/atlas pull request #2411
Opened 2022-04-04 11:20 UTC by drillprop

Fix #2226 

Designs: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A114187
Flows: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2093%3A135230

2022-04-04 11:31 UTC, kdembler commented
@drillprop I requested a review from Adam, could you mention where this can be reviewed in the description?

2022-04-05 10:00 UTC, toiletgranny requested changes
Man, oh, man! Slick, I love it! Just a few minor details I found:

### Reaction stepper
1. In Figma, like and dislike reactions are actually both instances of a Button component. This means that the font used in the label should be `var(--typography-desktop-t200-strong)`.
2. The line animation in the `processing` state feels off, compared to [the Figma prototype](https://www.figma.com/proto/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2093%3A135299&scaling=scale-down&page-id=2093%3A135200&starting-point-node-id=2572%3A456143). Could we try setting the easing to be `ease-in-out` here?
3. Something that was not clear in designs is that ideally when the Reaction popover is displayed, the Reaction stepper component is already in its processing state. The actual transaction, however, should be initiated only upon clicking the "Got it" button. Is this something we can achieve in the implementation?

### Reaction popover
1. Please note, that in Figma the illustration is part of the `Body` section of the `Popover` component. The implication of this is that the illustration should also be included in scrolling. 
4. Also note, because the illustration is placed in that `Body` section, in Figma it has negative top and side margins, and the values correspond to whatever is currently set as padding for the `Body` section of the `Popover` component.
5. The `Learn more` should be a Button component of a `Tertiary` type. Because of this, it should be positioned below the other two buttons below the `SM` breakpoint.

2022-04-07 09:44 UTC, toiletgranny approved these changes
Looking great! Let's goo! 🚀

2022-04-07 10:22 UTC, rafalpawlow approved these changes

2022-04-07 16:11 UTC, merged