Card interactions
Joystream/atlas pull request #2412
Opened 2022-04-04 12:36 UTC by drillprop

Fix #1829

2022-04-05 14:23 UTC, drillprop reviewed
I know that I partly wrote this code but I allowed myself to add two comments 😅

2022-04-05 14:23 UTC, drillprop commented on packages/atlas/src/components/_nft/NftCard/NftCard.tsx
> +        const tp = 50 + (row * 10 - 50) / 1
```suggestion
        const lp = column * 10
        const tp = row * 10
```
I just copied this chunk of code from somewhere and started to tweak and left this not refactored. Let's just simplify these calculations or even move to `ReflectionGridCell`

2022-04-05 14:23 UTC, drillprop commented on packages/atlas/src/components/_nft/NftCard/NftCard.tsx
> +              left: `calc(${column} * 10%)`,
This could be moved inside to `ReflectionGridCell`

2022-04-06 09:11 UTC, rafalpawlow requested changes
Looks and works amazing. However I have a doubt though, it seems to me that there should be some suggestion that the card is interactive. Maybe it should animate itself slightly or be slightly tilted by default? @toiletgranny

2022-04-06 09:11 UTC, rafalpawlow commented on packages/atlas/src/components/_nft/NftCard/NftCard.styles.ts
> +  background-image: url('https://i.imgur.com/AjBArhU.png');
I think we shouldn't take it from external server, it should live in our assets directory.

2022-04-06 09:11 UTC, rafalpawlow commented on packages/atlas/src/components/_nft/NftCard/NftCard.styles.ts
> +  z-index: 2;
Can we use `zIndex` from our utils?

2022-04-06 09:11 UTC, rafalpawlow commented on packages/atlas/src/components/_nft/NftCard/NftCard.styles.ts
> +  z-index: 1;
Same question as above

2022-04-06 09:46 UTC, toiletgranny commented
@rafalpawlow I love this idea, brilliant! How about a subtle attention seeker [like this one](https://jsfiddle.net/toiletgranny/ym5Laujs/93/)? We could have it played only once, with... let's say a 2s delay, to make sure everything's properly loaded. The only question is, @eldiegod, are we going to be able to show all the lights, shines, and patterns in the animation like this one, even though the cursor might not be hovering over the NFT card?

2022-04-07 10:30 UTC, eldiegod commented
>@rafalpawlow I love this idea, brilliant! How about a subtle attention seeker [like this one](https://jsfiddle.net/toiletgranny/ym5Laujs/93/)? We could have it played only once, with... let's say a 2s delay, to make sure everything's properly loaded. The only question is, @eldiegod, are we going to be able to show all the lights, shines, and patterns in the animation like this one, even though the cursor might not be hovering over the NFT card?

@toiletgranny It's possible but it's not that easy because of what you mention, if we want this I think it's best to work on it in a separate ticket/PR

2022-04-08 09:09 UTC, rafalpawlow approved these changes

2022-04-08 09:36 UTC, merged