Drawers should not cover the entire screen
Joystream/atlas pull request #2413
Opened 2022-04-04 15:45 UTC by eldiegod

VideoWorkspace or NftSaleBottomDrawer should leave some space for the top bar

 fix: #2393

2022-04-04 15:57 UTC, drillprop approved these changes

2022-04-04 16:20 UTC, rafalpawlow requested changes
Let's update styles and story also since this will be never used

2022-04-05 10:37 UTC, kdembler commented
Agreed, let's just remove the prop completely

2022-04-05 19:27 UTC, rafalpawlow approved these changes

2022-04-06 10:49 UTC, merged