Notif panel
Joystream/atlas pull request #2430
Opened 2022-04-06 19:57 UTC by eldiegod

fixes: #1738 and by mistake #1737

2022-04-07 08:06 UTC, drillprop commented
If it also fixes #1737 you should assign yourself to this task.  Someone could start working on it by accident. Just saying :P

Anyway, I assigned you and move these issues on zenhub to `review`

2022-04-07 10:33 UTC, eldiegod commented
> If it also fixes #1737 you should assign yourself to this task. Someone could start working on it by accident. Just saying :P
> 
> Anyway, I assigned you and moved these issues on zenhub to `review`

yep u right

2022-04-08 09:05 UTC, rafalpawlow requested changes
1.  something is wrong with dimensions, in figma it has 613px

![Zrzut ekranu 2022-04-8 o 10 58 53](https://user-images.githubusercontent.com/13706246/162402984-2a030cfc-3fd2-4061-8585-ef44cba0f260.png)

![Zrzut ekranu 2022-04-8 o 11 03 24](https://user-images.githubusercontent.com/13706246/162403225-465b90e6-9485-4a5b-8f6b-0e38b7e2de3f.png)

2. This button is egg-shaped
![Zrzut ekranu 2022-04-8 o 10 59 12](https://user-images.githubusercontent.com/13706246/162403397-4d731f61-db72-4f38-a4cd-dfd784a66828.png)

3. You forgot about RWD

2022-04-08 09:05 UTC, rafalpawlow commented on packages/atlas/src/components/_notifications/NotificationsWidget/NotificationsWidget.tsx
> +            onClick={() => markNotificationsAsRead(notifications.map((notif) => notif.id))}
Couldn't we create function for that in `useNotifications` to not repeat this mapping every time?

2022-04-11 13:45 UTC, eldiegod commented on packages/atlas/src/components/_notifications/NotificationsWidget/NotificationsWidget.tsx
> +            onClick={() => markNotificationsAsRead(notifications.map((notif) => notif.id))}
now you can pass notifications obj directly

2022-04-11 13:46 UTC, eldiegod commented
> something is wrong with dimensions, in figma it has 613px

Hey @toiletgranny, could you help out a bit in here, I'm not sure how to get the styles to match the width in figma can you tell me what I'm missing?

2022-04-12 07:51 UTC, toiletgranny commented
As this was prepared by @TCzechowski, Tomek, can you have a look at Diego's question above?

2022-04-12 09:36 UTC, TCzechowski commented
Hi @eldiegod! I don't know what happened in Figma, but the close button in Figma got stretched so the dimensions were off. I fixed it in Figma, but it still didn't match your width. I investigated it a bit and it's probably because you have used the Medium size of the buttons, and I've used Large variant for >MD breakpoints :)

2022-04-12 12:41 UTC, eldiegod commented
> hat happened in Figma, but the close button in Figma got stretched so the dimensions were off. I fixed it in Figma, but it still didn't match your width. I investigated it a bit and it's probably because you have used the Medium size of the buttons, and I've used Large variant for >MD breakpoints :)

yep, that solves it, thanks a lot @TCzechowski ! 

also @rafalpawlow the notification tiles might look a bit off from the design rn but that's because of the other notification PR that got merged today Bartosz is working on a fix for that

2022-04-12 14:22 UTC, drillprop commented
> also @rafalpawlow the notification tiles might look a bit off from the design rn but that's because of the other notification PR that got merged today Bartosz is working on a fix for that

fixed in #2476

2022-04-13 13:12 UTC, kdembler commented
@eldiegod Needs a small rebase. Also what's the status here? Waiting for review from @rafalpawlow?

2022-04-13 14:10 UTC, eldiegod commented
> base. Also what's the status here? Waiting for review

@kdembler yes, pretty much

2022-04-13 16:04 UTC, rafalpawlow requested changes
Looks good, however there is a problem with bottom nav. I think we could do the same I did for cookies banner https://github.com/Joystream/atlas/commit/dc10f63055a2e93b37746dc251dd8dad5d4cf1b0#diff-b2c59b011fdd1a962bf69babef2b7535bb64a75d864f0d921c162c4689246b04R26 but let's confirm this with @TCzechowski 

![Zrzut ekranu 2022-04-13 o 18 03 08](https://user-images.githubusercontent.com/13706246/163222541-2d76d8b8-fcac-4e4c-8d08-8c7b29355e00.png)

2022-04-13 16:04 UTC, rafalpawlow commented on packages/atlas/src/views/notifications/NotificationsView.tsx
> +    <Button variant="tertiary" size="large" onClick={unselectAllNotifications} iconOnly icon={<SvgActionClose />} />
According to figma:
```suggestion
    <Button variant="tertiary" size={smMatch ? 'large' : 'medium'} onClick={unselectAllNotifications} iconOnly icon={<SvgActionClose />} />
```

2022-04-14 08:38 UTC, TCzechowski commented
> Looks good, however there is a problem with bottom nav. I think we could do the same I did for cookies banner [dc10f63#diff-b2c59b011fdd1a962bf69babef2b7535bb64a75d864f0d921c162c4689246b04R26](https://github.com/Joystream/atlas/commit/dc10f63055a2e93b37746dc251dd8dad5d4cf1b0#diff-b2c59b011fdd1a962bf69babef2b7535bb64a75d864f0d921c162c4689246b04R26) but let's confirm this with @TCzechowski
> 
> ![Zrzut ekranu 2022-04-13 o 18 03 08](https://user-images.githubusercontent.com/13706246/163222541-2d76d8b8-fcac-4e4c-8d08-8c7b29355e00.png)

Yes, please do the same treatment here @rafalpawlow :)

2022-04-15 10:54 UTC, eldiegod commented
@rafalpawlow the problem is your PR is merged to dev, we don't have `useBottomNavStore` here, I added the fixes and commented them until either we rebase rhodes or we merge rhodes

2022-04-15 11:06 UTC, rafalpawlow requested changes
Something very bad has happened here 😛

![Zrzut ekranu 2022-04-15 o 13 05 38](https://user-images.githubusercontent.com/13706246/163563903-2946c1ad-81d4-4299-b2b3-619758eada0b.png)

2022-04-15 12:31 UTC, eldiegod commented
> Something very bad has happened here 😛
> 
> ![Zrzut ekranu 2022-04-15 o 13 05 38](https://user-images.githubusercontent.com/13706246/163563903-2946c1ad-81d4-4299-b2b3-619758eada0b.png)

@rafalpawlow oops forgot something, fixed now!

2022-04-15 13:10 UTC, rafalpawlow commented
@eldiegod `useBottomNavStore` is already on `rhodes`

2022-04-15 14:02 UTC, eldiegod commented
> @eldiegod `useBottomNavStore` is already on `rhodes`

@rafalpawlow  its in there

2022-04-15 14:04 UTC, rafalpawlow commented
@eldiegod oh, really sorry I should probably check it before write comment 😅

2022-04-15 14:14 UTC, rafalpawlow approved these changes

2022-04-15 16:32 UTC, merged