Fix vitest types warning (#2386)
Joystream/atlas pull request #2435
Opened 2022-04-07 16:52 UTC by rafalpawlow

Closes #2037  

**Design**
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6511%3A194029

2022-04-11 09:49 UTC, drillprop requested changes
The code looks good. We discussed this on slack already. 
I've noticed some visual discrepancies with the design. 
1. Lack of white space. Yours:
![image](https://user-images.githubusercontent.com/51168865/162712212-7129d596-b857-4df0-a29a-f99ede19249a.png)
Design: 
![image](https://user-images.githubusercontent.com/51168865/162712313-0449726a-4742-442c-bbdc-5e97aa12b552.png)
2. Link should be another paragraph(?). Yours: 
![image](https://user-images.githubusercontent.com/51168865/162712521-2b6ac760-cd0d-43e6-9013-105401f73fb0.png)
Design: 
![image](https://user-images.githubusercontent.com/51168865/162712430-45ff7224-c77a-4838-bea8-11c9443a23a2.png)

3. Decline button is grayed out. I'm not sure if it's a mistake in the design(?). You'll have to confirm this with Tomasz: 
Yours: 
![image](https://user-images.githubusercontent.com/51168865/162712948-a592c050-0444-4348-96d2-a8432e20a27c.png)
Design:
![image](https://user-images.githubusercontent.com/51168865/162712984-1f6256ab-96d3-44cc-8030-1409e37b83b3.png)

2022-04-11 10:19 UTC, rafalpawlow commented
@drillprop 3rd point should be tackled here https://github.com/Joystream/atlas/issues/2463

2022-04-11 12:06 UTC, TCzechowski approved these changes
I hereby accept this beautiful implementation. <3

2022-04-12 07:30 UTC, drillprop requested changes

2022-04-12 07:30 UTC, drillprop commented on packages/atlas/src/providers/snackbars/snackbar.tsx
> +  bottom: ${({ cookiesBannerOpen, bottomNavOpen }) => sizes(cookiesBannerOpen ? (bottomNavOpen ? 89 : 73) : 18)};
I'm a little worried about these magic numbers. These values won't work with smaller screens if Im not mistaken.

2022-04-12 07:30 UTC, drillprop commented on packages/atlas/src/components/_overlays/CookiePopover/CookiePopover.tsx
> +            </p>
When I said that we need a paragraph here I meant that we need to display StyledAnchor as a block and apply margin-top on it 😅   
Because of this paragraph spacing between the `description` and buttons section seems to me too big. It's `30px`( paragraph's margin-bottom + content padding) and it should be `24px`

2022-04-12 07:39 UTC, rafalpawlow commented on packages/atlas/src/providers/snackbars/snackbar.tsx
> +  bottom: ${({ cookiesBannerOpen, bottomNavOpen }) => sizes(cookiesBannerOpen ? (bottomNavOpen ? 89 : 73) : 18)};
But the alternative to this is glitched snackbars. It's just the lesser of two evils + this was discussed with @TCzechowski

2022-04-12 07:48 UTC, drillprop commented on packages/atlas/src/providers/snackbars/snackbar.tsx
> +  bottom: ${({ cookiesBannerOpen, bottomNavOpen }) => sizes(cookiesBannerOpen ? (bottomNavOpen ? 89 : 73) : 18)};
ok, let's leave this as you implemented.

2022-04-12 07:53 UTC, drillprop approved these changes

2022-04-12 09:48 UTC, merged