Update the Dialog (Modal) component
Joystream/atlas pull request #2462
Opened 2022-04-11 09:36 UTC by eldiegod

fixes: #2312

2022-04-12 07:09 UTC, drillprop requested changes
These changes don't work well with the create member modal. This is how it looks on 550px viewport

![image](https://user-images.githubusercontent.com/51168865/162900756-5ef098d6-f636-47db-809d-206dfd59bbfb.png)

I'm also not sure if we should keep this particular dialog on the bottom of the screen. @toiletgranny wdyt?

2022-04-12 07:09 UTC, drillprop commented on packages/atlas/src/components/_overlays/Modal/Modal.tsx
> +      <CSSTransition in={show} timeout={250} classNames={transitions.names.fade} mountOnEnter unmountOnExit>
We should use `cVar` here: `timeout={parseInt(cVar('animationTimingMedium', true))}`

2022-04-12 07:09 UTC, drillprop commented on packages/atlas/src/components/_overlays/Modal/Modal.tsx
> +        timeout={250}
Same as above

2022-04-12 07:09 UTC, drillprop commented on packages/atlas/src/providers/confirmationModal.tsx
> +            }
Hmm, I don't like how it's written, can we create the handler above component? You moved `args || modalProps` to variable anyway. I would also write this little differently i.e: 
```tsx
        const handleClick = () => {
          if (!_args?.onExitClick) {
            return undefined
          }
          _args?.onExitClick?.()
          _closeModal()
        }
```
This is almost the same and in my opinion more readable

2022-04-12 07:09 UTC, drillprop commented on packages/atlas/src/styles/transitions.ts
> +    modal: 'atlas-modal',
Why do we need to change that name? Do we have another "modal" somewhere?

2022-04-12 14:25 UTC, toiletgranny requested changes
I'm so happy to see this coming alive so quickly! ❤️ I did, however, find a few issues that must be addressed.

1. **Modal animations.** I wasn't able to see any desktop-sized dialog appearing on screen with the scale animation. Not in the Storybook, nor in the app. Are you sure the animation was implemented properly? As a reminder, new transition animations are described [in Figma, here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6341%3A146413) (the "Animation" section at the very bottom).
2. **Dialog header.** — Please note, that there should be a `24px` (or `40px` starting with the SM breakpoint) of distance between the close button and the dialog title in the Header section. Currently, there's no gap in between these elements.
3. **Sign in** — This dialog has been left unaffected by our changes, it seems. Would it be a lot of work to have this component inherit the recent changes we made to dialogs and overlays, such as new transitions, new responsive behavior, rounded corners, the styling of the footer, etc.? At the very least, can we make sure it doesn't stop shrinking horizontally when reaching `690px` of width? Of course, ideally, all future updates to the styling/behavior of our dialogs/modals in Atlas are also picked up in this dialog. 
![CleanShot 2022-04-12 at 15 53 16](https://user-images.githubusercontent.com/35307309/162978122-1e58a88f-c727-46d5-887e-7b958bfa9e1d.png)
4. **Create membership** — Same comment as above.
![CleanShot 2022-04-12 at 15 38 14](https://user-images.githubusercontent.com/35307309/162975193-472b8aa2-84b2-4239-bb5f-96e096a3b8d1.png)
5. **Processing and errors** — In the below two examples, both dialogs are — obviously — too wide. As a reminder, from the docs in Figma: "_The width of the modal contents should also be freely customizable, with 480px being a default value and 768px and 1120px being preferable presets for extending._"
![CleanShot 2022-04-12 at 15 43 08](https://user-images.githubusercontent.com/35307309/162976064-08522097-a6aa-47b5-b2fa-2fc52183d2b9.png)
![CleanShot 2022-04-12 at 15 51 30](https://user-images.githubusercontent.com/35307309/162977727-433baae7-4c43-416f-afe0-70094bb7b08b.png)

---

Now, @kdembler, I wasn't able to access Studio in a way that would allow me to inspect dialog components over there. No matter which Polkadot account or chain I tried, I would always get stuck at the "Oops! An error occurred." screen. For this reason, I don't know if there are other issues with dialogs that are a result of these changes. Is there anything else I can try to access Studio in this PR's... _deployment_ (if that's the word 😅 )?

2022-04-25 20:00 UTC, eldiegod commented
@toiletgranny did what I could on the existing dialogs I think most things should be fixed pls take a look again and lmk !

2022-04-26 07:07 UTC, drillprop requested changes
Still doesn't feel right to me:
![image](https://user-images.githubusercontent.com/51168865/165239459-e1a8a3d7-8e4f-4dd0-a972-06a0d1ea1b7e.png)
![image](https://user-images.githubusercontent.com/51168865/165239619-178373f0-5177-4cfd-a69c-109443d09de8.png)

![image](https://user-images.githubusercontent.com/51168865/165239824-bd568ec5-f506-4a45-816e-df5ad1822ab4.png)

@toiletgranny I don't see the answer to my question. I'm not sure if this topic was raised.  Maybe you discussed this with Diego somewhere else, so I'll ask again:
Should we keep the member dialog(only this particular dialog) at the bottom of the page as well on smaller screens? Shouldn't we leave this centered as it was before?

![image](https://user-images.githubusercontent.com/51168865/165241046-b0936ead-a210-4efc-a796-7b30ed4a9a17.png)

2022-04-26 10:07 UTC, toiletgranny commented
Thanks, @eldiegod! I can confirm that the (1) Modal animations and (2) Dialog header issues I've listed in my previous comment are now fixed, thanks!

1. **Max-width** — As @drillprop pointed out, the issue of overly wide dialogs is still present, so for quick reference:
   - The max-width of both the [Transaction dialog](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=5207%3A204082) and [Alert dialog](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6278%3A138198) components, starting on the SM breakpoint, should be both `480px`. In Figma, you'll find out that the max-width of the Transaction dialog component is set to `440px`, but this is due to historic reasons and I'm 100% fine with it following a global rule. 
   - The max-width of both the Sign in and Create membership dialogs should be set to `768px`.
   - For the future, let's keep in mind that `480px` should be the _default_ max-width value for all Dialog components. 
2. **Sign in**
   - The footer in this dialog def looks more aligned with our recent changes now, and the only thing that's still missing is the top border. 
   - Also, notice how the entire window is scrollable when there's not enough vertical space to display it fully in the viewport. Ideally, we're following the same pattern as with all other scrollable Dialog components, which is that only the body part is scrollable.  You can see this very clearly on the screen recording below when I'm switching between the Sign in (incorrect scrolling behavior) dialog and the Create membership dialog (correct scrolling behavior). 

https://user-images.githubusercontent.com/35307309/165274933-d3e97ac4-df90-4a1e-8e53-0f1da4d0543b.mp4

3. **Create membership** — It seems like either not all changes to Dialog component footers have been picked up in the Create membership dialog, or that we might have missed that one change entirely. Namely, the size of Button components inside Dialog footers has changed from Large to Medium. In the Create membership dialog, however, the size of the button in the future is still Large.

---

To answer your question, @drillprop: [following the new designs](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6341%3A146413) ("Positioning, size, marings & overflow" section), all Dialog components (or, if you prefer, all components placed inside of the Modal component) should be placed at the bottom and be stretched to fill the entire width of the viewport. So **yes**, we should keep the member dialog (Sign in dialog) component at the bottom of the page on smaller screens, just like every other Dialog component up until the SM breakpoint.

2022-04-26 17:08 UTC, eldiegod commented
> To answer your question, @drillprop: [following the new designs](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6341%3A146413) ("Positioning, size, marings & overflow" section), all Dialog components (or, if you prefer, all components placed inside of the Modal component) should be placed at the bottom and be stretched to fill the entire width of the viewport. So **yes**, we should keep the member dialog (Sign in dialog) component at the bottom of the page on smaller screens, just like every other Dialog component up until the SM breakpoint.


@toiletgranny ok, I think I covered the bad widths and other stuff this time around, lmk if you find anything else!

2022-04-29 06:36 UTC, drillprop approved these changes
Looked at the code again and tested this visually and LGTM!  🎉

2022-04-29 06:52 UTC, drillprop requested changes
Oh sorry, there is still a warning in the console. This is happening when I'm opening create member modal
![image](https://user-images.githubusercontent.com/51168865/165896993-e9e38093-7fe8-4507-8722-fe054b5336fc.png)

2022-04-29 08:43 UTC, toiletgranny approved these changes
Now it's perfect! Good to go from my perspective!

2022-04-29 09:17 UTC, eldiegod commented
should be fixed

2022-04-29 09:29 UTC, drillprop requested changes

2022-04-29 09:29 UTC, drillprop commented on packages/atlas/src/components/_overlays/Dialog/Dialog.styles.ts
> +  'data-hasadditionalactions'?: boolean
```suggestion
  'data-has-additional-actions'?: boolean
```
This is not really readable

2022-04-29 09:29 UTC, drillprop commented on packages/atlas/src/components/_overlays/Dialog/Dialog.styles.ts
> +  &:not([data-hasadditionalactions]) {
```suggestion
  &[data-has-additional-actions='false'],
  &:not([data-has-additional-actions]) {
```

2022-04-29 09:29 UTC, drillprop commented on packages/atlas/src/components/_overlays/Dialog/Dialog.tsx
> +          data-hasadditionalactions={!!additionalActionsNode}
```suggestion
          data-has-additional-actions={!!additionalActionsNode}
```

2022-04-29 11:27 UTC, eldiegod commented on packages/atlas/src/components/_overlays/Dialog/Dialog.styles.ts
> +  &:not([data-hasadditionalactions]) {
yeah probably better

2022-04-29 12:12 UTC, drillprop approved these changes

2022-04-29 12:13 UTC, merged