alert dialog component
Joystream/atlas pull request #2473
Opened 2022-04-12 12:56 UTC by rafalpawlow

Closes #2313 

**Design**
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6278%3A138198

2022-04-15 18:32 UTC, eldiegod requested changes

2022-04-15 18:32 UTC, eldiegod commented on packages/atlas/src/components/_overlays/Dialog/Dialog.styles.ts
> +  return cVar('colorCoreBlue500')
should add the variant informative with icon color Neutral 100

2022-04-15 18:32 UTC, eldiegod commented on packages/atlas/src/components/_overlays/Dialog/Dialog.tsx
> +      type?: 'destructive' | 'warning' | 'primary'
`informative` instead of `primary`?

2022-04-21 12:21 UTC, eldiegod approved these changes

2022-04-21 18:14 UTC, kdembler reviewed
During grooming we discussed that we wanted to have this as a separate component, that's also what is listed in the AC, what's the reason to keep all this functionality inside `Dialog`?

2022-04-25 07:33 UTC, rafalpawlow commented
@kdembler I misunderstood AC, will fix it

2022-04-25 07:36 UTC, kdembler commented
@rafalpawlow Do you agree it makes sense to extract this into a separate component? I think this way we end up with simpler `Dialog` which we can compose into additional components

2022-04-25 10:09 UTC, rafalpawlow commented
@kdembler yes, I totally agree

2022-04-26 17:11 UTC, eldiegod commented
I'm a bit scared about this PR clashing too hard with mine on https://github.com/Joystream/atlas/pull/2462

2022-05-05 16:02 UTC, kdembler approved these changes

2022-05-05 16:02 UTC, merged