Activity member tab integration
Joystream/atlas pull request #2525
Opened 2022-04-20 14:31 UTC by drillprop

Fix #2472 
Sorting and infinite scrolling aren't in the scope of this PR

2022-04-21 10:41 UTC, eldiegod commented
lets do a rebase on this one

2022-04-21 18:05 UTC, eldiegod approved these changes
looks pretty neat

2022-04-21 18:05 UTC, eldiegod commented on packages/atlas/src/views/viewer/MemberView/MemberActivity.hooks.ts
> +  event: ReturnType<typeof useRawActivities>['activities'][0],
We don't need to grab the first item of the array we can just do: 
```suggestion
  event: ReturnType<typeof useRawActivities>['activities'][number],
```

2022-04-21 18:12 UTC, kdembler requested changes
We're missing price here:
![Screenshot 2022-04-21 at 20 11 40](https://user-images.githubusercontent.com/12646744/164525736-0622960d-919c-4a94-a3c6-9a3e60748a8e.jpg)

Also, what do we do with sorting? The select is still there but has no effect. Making it work is probably super easy since we do sorting client side anyway

2022-04-22 10:13 UTC, kdembler approved these changes

2022-04-22 10:13 UTC, merged