Comments section
Joystream/atlas pull request #2526
Opened 2022-04-20 14:34 UTC by rafalpawlow

Closes #2449 
I didn't implement comment input since it's still in review https://github.com/Joystream/atlas/pull/2558

**Design**
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140537

2022-04-20 14:34 UTC, rafalpawlow commented
Waiting for https://github.com/Joystream/atlas/pull/2474

2022-04-27 11:25 UTC, drillprop requested changes
Found just one minor thing, besides looks and works awesome.

2022-04-27 11:25 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/CommentsSection.tsx
> +      </CommentsSectionHeader>
You didn't add a divider below the header.

![image](https://user-images.githubusercontent.com/51168865/165507739-9470c422-700a-4d56-9b4d-f61a26350c39.png)

2022-04-27 15:32 UTC, drillprop approved these changes

2022-04-28 15:34 UTC, kdembler commented
Nice!

2022-04-28 15:34 UTC, merged