Not found view
Joystream/atlas pull request #2566
Opened 2022-04-27 10:18 UTC by eldiegod

fixes: #2147

2022-04-27 15:04 UTC, rafalpawlow requested changes
You used wrong size of the button

2022-04-29 08:37 UTC, rafalpawlow approved these changes

2022-04-29 08:58 UTC, merged

2022-04-29 16:13 UTC, TCzechowski commented
@eldiegod @kdembler @rafalpawlow 
Hi guys, I've seen the implementation of 404 page, and I have one comment here.

Could we please make the content vertically centered? With current implementation some content (especially the primary button) may remain unnoticed by the users. 

![image](https://user-images.githubusercontent.com/22870059/165982425-76633195-5eb4-427f-b6ec-4aac41a5fb1d.png)

Also @eldiegod please remember to request PR design reviews from the author of the designs in the future 🙏🏻

Thanks!

2022-05-05 07:43 UTC, kdembler commented
@eldiegod Seems like there's some followups here, can you create an issue and put it in the sprint?