update Rhodes app copy
Joystream/atlas pull request #2584
Opened 2022-04-28 19:05 UTC by kdembler

Almost all of the changes were agreed with the design team. Probably still worth taking a quick look to make sure I didn't mess anything up :D

2022-04-29 08:36 UTC, rafalpawlow requested changes
I fell we have a little mess here with the periods at the end of the sentences, in some place we use and in some not. TBH I'm not sure what approach we should take.

2022-04-29 08:36 UTC, rafalpawlow commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +              description: 'This auction has ended and no one placed a bid. You can now remove this NFT from sale.',
```suggestion
              description: 'This auction has ended, and no one placed a bid. You can now remove this NFT from sale.',
```

2022-04-29 08:36 UTC, rafalpawlow commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +                "This auction has ended and no one placed a bid. We're waiting for the NFT owner to remove this NFT from sale.",
```suggestion
                "This auction has ended, and no one placed a bid. We're waiting for the NFT owner to remove this NFT from sale.",
```

2022-04-29 08:36 UTC, rafalpawlow commented on packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/AcceptTerms/AcceptTerms.tsx
> +                ? 'Put it on a timed or open auction. See the bids coming.'
```suggestion
                ? 'Put it on a timed, or open auction. See the bids coming.'
```

2022-04-29 08:36 UTC, rafalpawlow commented on packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/AcceptTerms/AcceptTerms.tsx
> +                  ? 'Bids matching this value will automatically end your auction'
```suggestion
                  ? 'Bids matching this value will automatically end your auction.'
```

2022-04-29 08:36 UTC, rafalpawlow commented on packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/AcceptTerms/AcceptTerms.tsx
> +                  : 'Price for your NFT as shown to your buyers'
```suggestion
                  : 'Price for your NFT as shown to your buyers.'
```

2022-04-29 08:36 UTC, rafalpawlow commented on packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/AcceptTerms/AcceptTerms.tsx
> +              text="The moment in time when your auction becomes active and bids will be accepted"
```suggestion
              text="The moment in time when your auction becomes active, and bids will be accepted."
```

2022-04-29 08:36 UTC, rafalpawlow commented on packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/ListingType/ListingType.tsx
> +          helperText="Put it on a timed or open auction. See the bids coming."
```suggestion
          helperText="Put it on a timed, or open auction. See the bids coming."
```

2022-04-29 08:36 UTC, rafalpawlow commented on packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/SetUp/SetUp.tsx
> +                    helperText="Pick the winning bid or cancel anytime"
```suggestion
                    helperText="Pick the winning bid, or cancel anytime"
```

2022-04-29 10:12 UTC, kdembler commented
This copy has been written by Dima, Adam and me, and we discussed both periods and commas. I would personally skip those commas before or/and. Also, our approach to periods was that we place them only if the message was sentence-like, we tried to be as consistent as possible. I'm gonna disagree with your suggestions 😅

2022-05-05 08:45 UTC, rafalpawlow approved these changes
@kdembler Tbh I was sure that my comma suggestions followed the rules of grammar. But this recommendation I trust 😅
> This copy has been written by Dima, Adam and me

2022-05-05 15:59 UTC, merged