Add comment integration
Joystream/atlas pull request #2632
Opened 2022-05-06 13:07 UTC by drillprop

Fix #2439

2022-05-09 15:16 UTC, kdembler commented
When not logged in :P

![Screenshot 2022-05-09 at 17 16 05](https://user-images.githubusercontent.com/12646744/167441565-9a07cc8c-6bc6-409e-9bb8-2379e50df2ab.jpg)

2022-05-10 09:09 UTC, drillprop commented
> When not logged in :P
> 
> ![Screenshot 2022-05-09 at 17 16 05](https://user-images.githubusercontent.com/12646744/167441565-9a07cc8c-6bc6-409e-9bb8-2379e50df2ab.jpg)

fixed

2022-05-10 12:15 UTC, eldiegod requested changes
Works as expected but there is an issue with focus/blur in CommentInput; I would guess it's either because of the change in the onFocus functions or by the custom placeholder, I remember I thought it was not worth it to have a custom placeholder and think it was because of this.

To reproduce the issue: click on the CommentInput -> don't type -> click multiple times in the container besides the buttons -> it will case the input to close and open flicker and blur/focus flciker

2022-05-10 12:15 UTC, eldiegod commented on packages/atlas/src/components/_comments/Comment/Comment.styles.ts
>    align-items: center;
nice

2022-05-10 12:59 UTC, drillprop commented
> I remember I thought it was not worth it to have a custom placeholder and think it was because of this.

Unfortunately, the design requires a custom placeholder:
![image](https://user-images.githubusercontent.com/51168865/167633091-c881bd9b-502c-49be-ace0-6c703d8a5e60.png)
It's impossible to change the styling of one word(in this case "bedeho") using only `::placeholder` selector. I had to add something custom. 

> To reproduce the issue: click on the CommentInput -> don't type -> click multiple times in the container besides the buttons -> it will case the input to close and open flicker and blur/focus flciker

I think I fixed this. Let me know what you think

2022-05-10 13:34 UTC, eldiegod approved these changes
yeah now it's good

2022-05-10 13:42 UTC, merged