fix closing create member modal without accepting terms
Joystream/atlas pull request #2634
Opened 2022-05-06 17:02 UTC by rafalpawlow

Closes #2608

2022-05-09 07:26 UTC, kdembler commented
Requesting review from @drillprop instead, as he's been touching that piece of code more recently and also he reported the bug

2022-05-09 09:49 UTC, drillprop requested changes
This is not working correctly. If I don't have an account I can't create a membership because the create member dialog never shows up.

2022-05-10 06:59 UTC, drillprop approved these changes

2022-05-10 08:43 UTC, kdembler approved these changes

2022-05-10 08:43 UTC, merged