Show more/show less button on comment
Joystream/atlas pull request #2636
Opened 2022-05-09 12:23 UTC by drillprop

Fix #2564 
Designs: 
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=3677%3A265878

Be aware that the look of the show more button differs from the design. This won't be an issue once https://github.com/Joystream/atlas/issues/2463 is done

I didn't handle [exceeding characters limit story](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/?node-id=3677%3A254185). I'll create a separate issue just for that.

2022-05-10 11:43 UTC, rafalpawlow requested changes
1. there is wrong spacing between author and deleted comment. Can we fix this as part of this PR? We have `8px` but in figma it's `12px`
![Zrzut ekranu 2022-05-10 o 13 37 37](https://user-images.githubusercontent.com/13706246/167620494-1b645fc9-29a9-40b4-9306-3ce3c338d9ba.png)

2. I've noticed that Show more button has wrong color but I assume it will be fixed here https://github.com/Joystream/atlas/pull/2637 .

2022-05-10 11:43 UTC, rafalpawlow commented on packages/atlas/src/components/_comments/CommentBody/CommentBody.tsx
> +export const CommentBody = ({ children }: { children?: string }) => {
Can't we just add proper type here?
```suggestion
export const CommentBody: React.FC = ({ children }) => {
```

2022-05-10 11:48 UTC, drillprop commented on packages/atlas/src/components/_comments/CommentBody/CommentBody.tsx
> +export const CommentBody = ({ children }: { children?: string }) => {
I want to be able to pass **only** string here, not React.ReactNode, that's why I wrote this.

2022-05-11 07:34 UTC, drillprop commented
> 1. there is wrong spacing between author and deleted comment. Can we fix this as part of this PR? We have `8px` but in figma it's `12px`

Fixed

> 2. I've noticed that Show more button has wrong color but I assume it will be fixed here https://github.com/Joystream/atlas/pull/2637 . 

correct

2022-05-11 08:44 UTC, rafalpawlow approved these changes

2022-05-12 09:42 UTC, merged