Button update
Joystream/atlas pull request #2637
Opened 2022-05-09 12:23 UTC by eldiegod

Fixes: #2463

- IconButton component got removed; use the Button component with icon prop and no children.
- iconOnly prop got removed; for a while, this prop did nothing as we calculate this when an icon is passed, and no children are passed.
- I removed the ButtonBase component as it served no purpose.
- removed unused or duplicated styles.
- updated the text only variants

I spent hours trying to find a way around this just with types. Still, due to the text only variants being different from the default variants, in an attempt to properly handle this, I renamed the `textOnly` to `_textOnly` to be used internally only.
I also created the TextButton component, the same as our Button component but with correct typings for text variants.

2022-05-10 12:51 UTC, kdembler requested changes
Good job in general, left some mostly cosmetic comments. From the visual standpoint, I've noticed that all the text buttons have the same height (24px) regardless of the size:
![Screenshot 2022-05-10 at 14 50 09](https://user-images.githubusercontent.com/12646744/167632366-2fe362fa-7bba-4fbe-87ee-e07a2a3fa20f.jpg)

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/Banner/Banner.styles.ts
> +import { Button } from '../_buttons/Button'
I think we should use absolute import path here

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/Carousel/Carousel.styles.ts
> +import { Button } from '../_buttons/Button'
I think we should use absolute import path here

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/DrawerHeader/DrawerHeader.tsx
> +import { Button } from '../_buttons/Button'
I think we should use absolute import path here

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/ProgressDrawer/ProgressDrawer.tsx
> +import { Button } from '../_buttons/Button'
I think we should use absolute import path here

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/Searchbar/Searchbar.styles.ts
> +import { Button } from '../_buttons/Button'
I think we should use absolute import path here

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/Searchbar/Searchbar.tsx
> +import { Button } from '../_buttons/Button'
I think we should use absolute import path here

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/Step/Step.tsx
> +import { Button } from '../_buttons/Button'
I think we should use absolute import path here

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/_buttons/Button/Button.styles.ts
> +const ButtonSizeObj = { large: 'large', medium: 'medium', small: 'small' }
I don't think this object is needed at all?

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/_buttons/Button/Button.styles.ts
> +        ${iconOnly && `border-radius: 50%`};
We agreed to not use this type of "style in a string" as it bypasses stylelint: https://github.com/Joystream/atlas/blob/master/docs/styleguide.md#conditional-styles

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/_buttons/Button/Button.styles.ts
> +const ButtonSizeStyles = ({ size, iconOnly, textOnly }: ButtonBaseStyleProps) => {
This shouldn't be Capitalized since it's not a component

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/_buttons/Button/Button.styles.ts
> +const ButtonVariantStyles = ({ variant, iconOnly }: ButtonBaseStyleProps): SerializedStyles => {
Same here, shouldn't be capitalized

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/_buttons/HamburgerButton/HamburgerButton.styles.ts
> +import { Button } from '../Button'
Should use absolute path

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/_inputs/FileSelect/FileSelect.styles.ts
> +export const DismissButton = styled(Button)`
This component seems to not be used anywhere, let's remove it

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.styles.ts
> +export const OwnerHandle = styled(TextButton)`
Should this be a button actually versus just a regular link?

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +                        <Text variant="t100">{nftStatus.topBidderHandle}</Text>
You removed the `you` functionality here

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/components/_overlays/Dialog/Dialog.tsx
> +              <StyledPrimaryButton variant={primaryButton.variant || 'primary'} {...primaryButton} size={buttonSize}>
Let's destruct `primaryButton` at the end so that consumer is able to override if needed and so we're consistent with the secondary button

2022-05-10 12:51 UTC, kdembler commented on packages/atlas/src/utils/types.d.ts
> +}
This should go into `src/types`

2022-05-10 17:10 UTC, eldiegod commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.tsx
> +                        <Text variant="t100">{nftStatus.topBidderHandle}</Text>
ah fak

2022-05-10 17:13 UTC, eldiegod commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.styles.ts
> +export const OwnerHandle = styled(TextButton)`
hmm i'm not sure rn but I think it was a button in design

2022-05-10 17:32 UTC, eldiegod commented
> ons have the same height (24px) regardless of the size:

@kdembler yeah, it looks like that but it's because of the flex parent component.

2022-05-10 20:15 UTC, kdembler commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.styles.ts
> +export const OwnerHandle = styled(TextButton)`
I don't think it is, at least in some cases, just a text here:
![Screenshot 2022-05-10 at 22 15 10](https://user-images.githubusercontent.com/12646744/167714277-1b8d11a6-fec7-43ef-8ee1-aa9eb0f632d6.jpg)

2022-05-11 08:45 UTC, toiletgranny commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.styles.ts
> +export const OwnerHandle = styled(TextButton)`
I can confirm it is just a text in here. If it were a button, it would be marked as such in the layers panel.

2022-05-11 09:46 UTC, toiletgranny requested changes
Overall, it's very nice! Here are the things I found:
1. When hovering over any button now, I can feel severe stuttering in the transition animation, no matter which CSS property is being animated. At the same time, in the "Actions" tab on Storybook, I can see quite a lot of onMouseMove events being recorded every time my cursor moves, even by 1px. Could it be connected?
2. The height of the last row of Text Only buttons (Tertiary) is off by 1px in all three sizes, eg. instead of `24px`, it's `23px`. I can see you apply a negative margin vertically on both sides (`margin-top: -0.5px; margin-bottom: -0.5px;`), and I assume it's to accommodate for the 1px bottom border in all other Text Only buttons, which brings me to my next point, which is that...
3. In my opinion, the current specification for CSS borders is just wrong. As far as I know, the `box-sizing: border-box property would only do its job if you specifically set the element's width and height, which rarely ever happens in the context of UI components such as buttons. Therefore, in Figma, I used absolute positioning for rendering bottom borders. Perhaps you'll find this approach (or something else, eg. `:before`/ `:after` pseudo-elements) more suitable in this case? I'm leaving this as a loose suggestion.

2022-05-11 10:36 UTC, drillprop commented
> When hovering over any button now, I can feel severe stuttering in the transition animation, no matter which CSS property is being animated. At the same time, in the "Actions" tab on Storybook, I can see quite a lot of onMouseMove events being recorded every time my cursor moves, even by 1px. Could it be connected?

@eldiegod I used `onMouseMove` and `onMouseOut` in the ChannelCard(check the FollowButton), but I made a mistake with selecting the right handler. We should use `onMouseEnter` and `onMouseLeave` here instead, which is much more performant(it's triggered basically only once when you hover and unhover on the button). Could you replace it and remove `onMouseMove` and `onMouseOut` props?

2022-05-11 15:56 UTC, eldiegod commented
> 3\. context of UI components such as buttons. Therefore, in Figma, I used absolute positioning for rendering bottom borders. Perhaps you'll find this approach (or something else, eg. `:before`/ `:after` pseudo-elements) more suitable in this case? I'm leaving this as a loose suggestion.

@toiletgranny I think the issues should be solved now, point 2 was a really easy fix so I didn't wanna go about changing much of the border now but I agree with you nowadays I build this type of thing using :before/ :after

2022-05-11 15:57 UTC, eldiegod commented
> > When hovering over any button now, I can feel severe stuttering in the transition animation, no matter which CSS property is being animated. At the same time, in the "Actions" tab on Storybook, I can see quite a lot of onMouseMove events being recorded every time my cursor moves, even by 1px. Could it be connected?
> 
> @eldiegod I used `onMouseMove` and `onMouseOut` in the ChannelCard(check the FollowButton), but I made a mistake with selecting the right handler. We should use `onMouseEnter` and `onMouseLeave` here instead, which is much more performant(it's triggered basically only once when you hover and unhover on the button). Could you replace it and remove `onMouseMove` and `onMouseOut` props?

@drillprop yep fixed 👍

2022-05-12 09:49 UTC, eldiegod commented on packages/atlas/src/components/_nft/NftWidget/NftWidget.styles.ts
> +export const OwnerHandle = styled(TextButton)`
replaced it with a normal Link + Text

2022-05-12 10:47 UTC, kdembler approved these changes
The hamburger button is no longer rounded:
![Screenshot 2022-05-12 at 12 42 00](https://user-images.githubusercontent.com/12646744/168053190-3510207b-cb95-4d12-b0fd-8010f6d24773.jpg)

Haven't found any other issues though, LGTM once 👆 if fixed, let's get an approval from Adam as well

2022-05-12 11:58 UTC, toiletgranny approved these changes

2022-05-16 08:48 UTC, merged