Set correct avatar on comment input
Joystream/atlas pull request #2654
Opened 2022-05-11 07:05 UTC by drillprop

This is just a minor fix. We were missing the member avatar on comment input.

![image](https://user-images.githubusercontent.com/51168865/167789313-dc7f1530-7b4b-4c45-9cef-f678ccfea4ae.png)

2022-05-12 09:35 UTC, eldiegod requested changes
Looks like when the user is logged out the avatar is loading indefinitely.

Also for the selecting issue: it's much better, now we can select from the start of a sentence but we still can't start selecting from the middle of a sentence or double click on a word to select it.

 not part of the scope of this PR anyways but pointing it out

2022-05-12 09:53 UTC, kdembler commented
@drillprop Please make sure to create a followup issue if you decide to not include this part in this PR:
> Also for the selecting issue: it's much better, now we can select from the start of a sentence but we still can't start selecting from the middle of a sentence or double click on a word to select it.

2022-05-12 12:16 UTC, drillprop commented
> Looks like when the user is logged out the avatar is loading indefinitely.

fixed

> Also for the selecting issue: it's much better, now we can select from the start of a sentence but we still can't start selecting from the middle of a sentence or double click on a word to select it.

I can't reproduce this. Works for me on firefox and chrome. Can someone confirm this? @kdembler how does it work for you?

2022-05-12 12:41 UTC, kdembler commented
Yep, works for me as expected as well

2022-05-16 08:55 UTC, eldiegod commented
@drillprop can confirm it works perfect now

2022-05-16 08:55 UTC, eldiegod approved these changes

2022-05-16 08:58 UTC, merged