linking to comments
Joystream/atlas pull request #2721
Opened 2022-05-18 13:33 UTC by rafalpawlow

Closes #2391 

**Design**
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2550%3A230287

2022-05-19 07:03 UTC, drillprop requested changes

2022-05-19 07:03 UTC, drillprop commented on packages/atlas/src/api/hooks/comments.ts
> +  variables?: GetCommentQueryVariables,
I guess we could safely take only id as a parameter. No need to pass `variables`. That's how it works at least in `useChannel` and `useVideo`

2022-05-19 07:03 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/CommentsSection.tsx
> +    }, SCROLL_TO_COMMENT_TIMEOUT)
Hmm this does work well when you click on the notification and the link leads you to another video, but it's really confusing what's going on when you click several times on comments in the comments section. 
Take a look at this video: 

https://user-images.githubusercontent.com/51168865/169229444-8d2d2e85-21e4-4435-ac7b-0361383f1a12.mov

2022-05-19 07:03 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/CommentsSection.tsx
> +        <HightLightedComment
typo here

2022-05-19 07:03 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/HightLightedComment.tsx
> +type HightLightedCommentProps = {
typo

2022-05-19 07:03 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/HightLightedComment.tsx
> +export const HightLightedComment: React.FC<HightLightedCommentProps> = ({
typo

2022-05-19 07:08 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/CommentsSection.tsx
> +    }, SCROLL_TO_COMMENT_TIMEOUT)
I think you'll need to talk about this with the designer. Correct me if I'm wrong but I didn't find any stories, that explain how it should work. Youtube for example reloads the page when you click someone's comment in the comment section.  

I'm also fine if we do this as a follow-up.

2022-05-19 08:19 UTC, rafalpawlow commented on packages/atlas/src/views/viewer/VideoView/CommentsSection.tsx
> +    }, SCROLL_TO_COMMENT_TIMEOUT)
I improved it a bit, let me know what u think

2022-05-20 07:58 UTC, drillprop requested changes

2022-05-20 07:58 UTC, drillprop commented on packages/atlas/src/api/hooks/comments.ts
> +  const userCommentReactionsLookup =
We do this twice, maybe we could create a function which takes comment reactions and convert them into lookup?

2022-05-20 07:58 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/HighlightedComment.tsx
> +    </>
let's refactor this a bit and use `if statements`

2022-05-24 07:08 UTC, drillprop requested changes
Looks good, but I've noticed one thing. When you click the comment in the comment section, all the comments disappear for a split second sometimes. I think this happens pretty consistently when you click the comment that has a parent comment(a comment which is a reply). Can we improve that?

2022-05-24 10:10 UTC, drillprop approved these changes

2022-05-24 10:19 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/CommentsSection.tsx
> +      : comments
This is super hard to read, I have no idea what's going on. Maybe we could:
1. Split this into more intermediary steps with named variables or use `if/else`? Not sure, but what we have currently doesn't work great 
2. Extract part of this comments logic to some local hook to encapsulate? (just an idea, up to you)

2022-05-24 10:21 UTC, kdembler reviewed
One observation: when I click a comment to mark it as highlighted, the entire comments section is reloading. Why is that happening? I would expect we could do this without fetching any new data. Maybe something like this in `cache.ts` would help to avoid fetching the comment again?
```tsx
commentByUniqueInput: (existing, { toReference, args }) => {
  return (
    existing ||
    toReference({
      __typename: 'Comment',
      id: args?.where.id,
    })
  )
},
```

2022-05-25 08:55 UTC, kdembler approved these changes

2022-05-25 08:55 UTC, merged