Comments infinite scroll
Joystream/atlas pull request #2746
Opened 2022-05-25 12:26 UTC by rafalpawlow

Closes #2454

2022-05-27 08:38 UTC, drillprop requested changes
This could be tricky to do, but you didn't handle infinite scrolling for replies. There could be a comment that has 200 replies, we don't want to fetch them all at once.

2022-05-27 08:38 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/CommentsSection.tsx
> +  // increase number of comments when user scrolls to the end of page
Unfortunately, this won't work well on smaller viewports, the comment section isn't last section on mobile: 
![image](https://user-images.githubusercontent.com/51168865/170662599-a154327e-95f7-45de-9a58-4096388c6fc5.png)
We would have to scroll down to CTA buttons and then scroll up to see new comments.

2022-05-27 11:41 UTC, rafalpawlow commented
@drillprop replies fetching will be resolved [here](https://github.com/Joystream/atlas/issues/2757)

2022-05-31 11:20 UTC, drillprop requested changes
We had a short call about current issues. Here's what we found:
- When you're on the video page and you switch users, the app breaks
- if you switch to another video and then switch back to the previous video, the number of comments is not correct, and infinite scrolling not working. This is probably cache problem
- The space is awkwardly small below the comments section on mobile
- Sometimes placeholders are blinking(they appear for a split second and disappear and then appear again) when you scroll fast - needs reproduction, I'm not sure how to trigger that. I'm also fine if we ignore this problem or fix it as a followup

2022-05-31 12:35 UTC, drillprop approved these changes

2022-06-01 08:15 UTC, merged