NumberFormat component with tooltip
Joystream/atlas pull request #2762
Opened 2022-05-30 09:42 UTC by eldiegod

fixes: #2678

2022-05-30 14:01 UTC, rafalpawlow requested changes
1. Tooltip should work on hover, currently it works on click
2. I'm not sure if this is specified somewhere but I noticed that for dollars you show full value without decimals. Can you confirm if this is a mistake?

2022-05-30 14:01 UTC, rafalpawlow commented on packages/atlas/src/components/NumberFormat/NumberFormat.stories.tsx
> +} as Meta
```suggestion
} as Meta<NumberFormatProps>
```

2022-05-30 14:01 UTC, rafalpawlow commented on packages/atlas/src/components/NumberFormat/NumberFormat.tsx
> +  children?: never
Shouldn't it be `number | string`?

2022-05-30 14:47 UTC, toiletgranny commented
Hey Diego! I was lucky enough to stumble upon this PR.

The implementation now addresses the main problems, which is great, but I have found a few things you might want to know about:
1. The tooltip component displaying full numbers doesn't seem to be the one we have in our component library. For example, the tooltip we know has no tail, it has slightly rounded corners and a subtle shadow underneath it. [Here's the link to the most up-to-date designs for the Tooltip component.](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6215%3A139642) Can we double-check it?
2. Not all numbers seem to have a tooltip attached to them, like in this example (make sure to switch to the Main Testnet), the Buy now price of 2M has no tooltip. https://atlas-o2aayrzjz-joystream.vercel.app/video/26775
3. While, in fact, we abbreviate large numbers over there, since most of the videos on production have under 99 views right now, it's just quite surprising to see a tooltip for a number such as `14`. Can we set up some threshold for displaying tooltips? Eg. for numbers that are above 999?
   - On the other hand, there are numbers such as `$1.26`, which also come with unnecessary tooltips:
   ![CleanShot 2022-05-30 at 16 46 15](https://user-images.githubusercontent.com/35307309/171016317-4abbaae7-a617-4a42-9b4c-4e5594ce020f.png)
5. I also noticed a few other, smaller issues, such as unexpected changes to number colors, alignment, or line-height. When combined together, they do make a difference. Below is a short video I recorded when comparing the same page between your deployment and production. Capturing all of those little nuances manually might be cumbersome, even if we were to compare views apples to apples, so I'm thinking if we had any chance to play with some automated visual regression tests here in Atlas, in the past? 

https://user-images.githubusercontent.com/35307309/171014519-adabde99-ea6b-4dfa-aafa-eb4275e3d7ae.mp4

Ps. Next time I'd really appreciate it if you could add me as a reviewer! 🙏

2022-05-30 14:59 UTC, rafalpawlow commented
@toiletgranny Diego created this branch from `dev` branch where we don't have new tooltips yet. They will be deployed together with reactions https://atlas-storybook-git-reactions-joystream.vercel.app/?path=/story/other-tooltip--default

2022-05-30 17:09 UTC, eldiegod commented on packages/atlas/src/components/NumberFormat/NumberFormat.tsx
> +  children?: never
I don't think so, since this is meant to replace the number formatting functions we always pass numbers in there.

2022-05-30 18:17 UTC, eldiegod commented
@toiletgranny 

1. as Rafal mentioned above, we don't have the tooltip changes in this branch yet, but we will eventually.
2. There is a tooltip there; it's just an issue with that particular part of the component that gets rebuilt as we poll the token price very often, and that makes the tooltip not show or show very briefly; I will have to find a patch to fix that
3. I would say we will need to define a bit more clearly the rules for showing or not showing the tooltip. Also, for things like decimals, I think we should show all available decimals in the tooltip even if it's `1.26$` like in the example because in the end is money we are talking about; I think it's worth the info for the user and I have a sense this is common in web3 apps in general, wdyt?
4. I will make some fixes for that and maybe that helps with a good amount but no we don't have any sort of testing atm that I'm aware off

2022-05-30 18:19 UTC, rafalpawlow commented on packages/atlas/src/components/NumberFormat/NumberFormat.tsx
> +  children?: never
So it should be `children?: number`, right?

2022-05-30 18:24 UTC, eldiegod commented on packages/atlas/src/components/NumberFormat/NumberFormat.tsx
> +  children?: never
there is `value: number` instead

2022-05-30 18:25 UTC, eldiegod commented
> I'm not sure if this is specified somewhere but I noticed that for dollars you show full value without decimals. Can you confirm if this is a mistake?

1. It works on hover you just have to hover it long enough
2. do you have an example for the dollar thing?

2022-05-30 18:28 UTC, rafalpawlow commented
@eldiegod 
1. Right, we seem to have agreed on that. I forgot about that
2.
![Zrzut ekranu 2022-05-30 o 20 26 53](https://user-images.githubusercontent.com/13706246/171044768-67a3edf0-a6a3-4c9b-b176-5352f4ee2b61.png)
![Zrzut ekranu 2022-05-30 o 20 27 05](https://user-images.githubusercontent.com/13706246/171044774-098863fe-1011-4e30-8b1c-77045feb82d7.png)

2022-05-30 18:32 UTC, rafalpawlow commented on packages/atlas/src/components/NumberFormat/NumberFormat.tsx
> +  children?: never
So why do we even declare `children` prop?

2022-05-30 18:51 UTC, eldiegod commented
not sure I understood 100% but yes that looks right, we don't 'short' format dollar amounts, at least until now

2022-05-30 19:19 UTC, rafalpawlow commented
That's what I meant 👍

2022-05-31 07:59 UTC, rafalpawlow requested changes
One more thing, when you type in storybook `100.5`, you get `100`. I think this is not correct

2022-06-02 11:11 UTC, eldiegod commented on packages/atlas/src/components/NumberFormat/NumberFormat.tsx
> +  children?: never
because we expand on `TextProps` and we expect `children` there but I overwrite it so it's not passed by mistake.

2022-06-03 08:49 UTC, rafalpawlow requested changes
Looks good, two small things
1. Do we need tooltip for full variant?
![Zrzut ekranu 2022-06-3 o 10 46 47](https://user-images.githubusercontent.com/13706246/171821278-d4b5d070-6fc1-499e-bdba-98c884753553.png)

2. Can we improve storybook a little bit? I need to write variant manually, radio would be more convenient
![Zrzut ekranu 2022-06-3 o 10 48 52](https://user-images.githubusercontent.com/13706246/171821508-b1051c61-3f1d-4e8d-8642-d2950ca9dc75.png)

2022-06-03 10:48 UTC, toiletgranny requested changes
As per your ask, Diego, I won't be looking at the number tooltip behavior within the NFT widget. And as such, things look much better already! ❤️ The two things I have are:
1. In the Video tile component, the number of views should be kept together with the `views` label, when it comes to line breaks. After the number change, it's no longer happening. Can we fix that?
![CleanShot 2022-06-03 at 12 36 25](https://user-images.githubusercontent.com/35307309/171838370-5a504f1b-911e-4463-b392-b2635242b325.png)
2. In regards to in which case scenarios should we be displaying tooltips, I'd be still advocating for doing it only with numbers that are either rounded or have decimal places.
   - In terms of how I, a simple & non-technical person, imagine this could be done, using conditional logic, would be something like this: show tooltips only for numbers that are rounded AND (numbers larger than `999` OR numbers that come with 3 or more decimal places).

2022-06-07 15:49 UTC, eldiegod commented
> Looks good, two small things
> 
>     1. Do we need tooltip for full variant?
>        ![Zrzut ekranu 2022-06-3 o 10 46 47](https://user-images.githubusercontent.com/13706246/171821278-d4b5d070-6fc1-499e-bdba-98c884753553.png)
> 
>     2. Can we improve storybook a little bit? I need to write variant manually, radio would be more convenient
>        ![Zrzut ekranu 2022-06-3 o 10 48 52](https://user-images.githubusercontent.com/13706246/171821508-b1051c61-3f1d-4e8d-8642-d2950ca9dc75.png)

@rafalpawlow fixed that and improved storybook

2022-06-08 13:41 UTC, kdembler requested changes
It seems we show too many fractional digits here:

![Screenshot 2022-06-08 at 15 27 24](https://user-images.githubusercontent.com/12646744/172631183-c2b54df4-3994-481d-a3b0-48f0d5af0ab6.jpg)

2022-06-09 08:32 UTC, toiletgranny approved these changes

2022-06-09 08:47 UTC, rafalpawlow approved these changes

2022-06-10 12:05 UTC, kdembler approved these changes

2022-06-10 12:05 UTC, merged