Remove oldColors
Joystream/atlas pull request #2763
Opened 2022-05-30 10:55 UTC by eldiegod

fixes: #2704

2022-05-30 11:49 UTC, drillprop requested changes

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/Carousel/Carousel.stories.tsx
> +  color: white;
we have `colorCoreBaseWhite` and we should use that

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/Tabs/Tabs.styles.ts
> +  color: ${({ selected }) => (selected ? 'white' : cVar('colorCoreNeutral300'))};
we have colorCoreBaseWhite and we should use that

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/_buttons/CallToActionButton/CallToActionButton.styles.ts
> +  color: white;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/_inputs/Checkbox/Checkbox.styles.ts
> +  color: white;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/_inputs/RadioInput/RadioInput.styles.ts
> +    color: ${(props) => (props.checked ? 'white' : '')};
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/_inputs/Select/Select.styles.ts
> +  color: white;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/_inputs/Slider/Slider.styles.ts
> +    background-color: white;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/_inputs/TitleArea/TitleArea.styles.ts
>    color: white;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/_navigation/BottomNav/BottomNav.styles.ts
> +  color: white;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/styles/GlobalStyles.tsx
> +    color: white;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/_navigation/TopbarViewer/TopbarViewer.styles.ts
> +        background-color: black;
We have `colorCoreBaseBlack` and we should use that

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/_video/VideoCategoryCard/FeaturedVideoCategoryCard.style.ts
> +    fill: black;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/styles/GlobalStyles.tsx
> +    background: black;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/views/viewer/CategoryView/CategoryVideos.styles.ts
> +  background-color: black;
same as above

2022-05-30 11:49 UTC, drillprop commented on packages/atlas/src/components/FiltersBar/FiltersBar.stories.tsx
>    background-color: black;
same as above

2022-06-01 09:41 UTC, kdembler commented on packages/atlas/src/components/_video/VideoHero/VideoHero.styles.ts
> +  background: linear-gradient(180deg, transparent 50%, black 93.23%, black 100%),
Should we use token for black here as well, for consistency?

2022-06-01 10:32 UTC, kdembler approved these changes

2022-06-01 10:32 UTC, merged