Update Checkbox component
Joystream/atlas pull request #2789
Opened 2022-06-02 17:55 UTC by rafalpawlow

Closes #2711

**Design**
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7382%3A142509

2022-06-03 11:20 UTC, toiletgranny requested changes
Great, thanks! All good, except for:
1. The helper text is still `var(--color-core-neutral-300)`, should be `var(--color-text)`,
2. This changelog item seems to not be implemented: "Added Focus state, which inherits its styling from the Hover state".  The goal here is to do the same thing that @drillprop has done with the Switch component recently. Ideally, we use the the `:focus-visible`, instead of `:focus`, if that's okay with you.

2022-06-06 06:55 UTC, drillprop requested changes
Same issue
https://github.com/Joystream/atlas/pull/2786#pullrequestreview-996212641
Basically, when someone clicks input with a mouse we don't want to show regular focus state.

2022-06-06 07:25 UTC, toiletgranny approved these changes

2022-06-08 08:56 UTC, rafalpawlow commented on packages/atlas/src/components/_inputs/Checkbox/Checkbox.styles.ts
> -import styled from '@emotion/styled/'
**FYI** this caused me a lot of trouble. I had weird errors from babel in storybook and it turned out this was the reason...

2022-06-09 08:27 UTC, toiletgranny approved these changes

2022-06-09 14:01 UTC, drillprop requested changes

2022-06-09 14:01 UTC, drillprop commented on packages/atlas/src/components/_inputs/Checkbox/Checkbox.styles.ts
> +export const Input = styled.input<InputProps>`
Let's rename this component. Maybe `CheckboxInput`?

2022-06-09 14:01 UTC, drillprop commented on packages/atlas/src/components/_inputs/Checkbox/Checkbox.styles.ts
> +type InputProps = {
same as above

2022-06-09 14:01 UTC, drillprop commented on packages/atlas/src/components/_inputs/Checkbox/Checkbox.styles.ts
> +  z-index: 999;
same comment https://github.com/Joystream/atlas/pull/2786#discussion_r893522142

2022-06-09 14:01 UTC, drillprop commented on packages/atlas/src/components/_inputs/Checkbox/Checkbox.styles.ts
> +  height: 16px;
we could use `square` here, right?

2022-06-09 14:01 UTC, drillprop commented on packages/atlas/src/components/_inputs/CheckboxGroup/CheckboxGroup.stories.tsx
> +    helperText: 't100',
Can we rename `helperText`  to `caption`? That's what it's called in Figma.  I think we should use the same names as much as we can.

2022-06-10 06:45 UTC, drillprop requested changes

2022-06-10 06:45 UTC, drillprop commented on packages/atlas/src/components/_inputs/CheckboxGroup/CheckboxGroup.stories.tsx
> +      helperText: args.helperText,
You still used `helperText` here. Why does typescript think that everything is fine here?

2022-06-10 08:33 UTC, kdembler commented
Needs to target `dev` (and optionally rebase)

2022-06-12 20:01 UTC, eldiegod requested changes
Looks pretty good just found a couple details

2022-06-12 20:01 UTC, eldiegod commented on packages/atlas/src/components/_inputs/CheckboxGroup/CheckboxGroup.tsx
> +          label="test"
This is wrong right?

2022-06-12 20:01 UTC, eldiegod commented on packages/atlas/src/components/_inputs/CheckboxGroup/CheckboxGroup.tsx
> +  value: number[]
I don't think `value` is a very clear name when the type is `number[]` on a checkboxGroup, what about something on the lines of `checkedIds`

2022-06-13 06:52 UTC, drillprop approved these changes
as for me, looks good

2022-06-13 10:48 UTC, eldiegod approved these changes

2022-06-13 10:48 UTC, merged