update tooltip component, fix comment timestamp
Joystream/atlas pull request #2813
Opened 2022-06-03 16:10 UTC by kdembler

Fixes #2794

2022-06-03 16:43 UTC, rafalpawlow requested changes
It seems like `multiline` doesn't do anything except padding. In previous implementation `oneLine` had `max-width: 400px` and it was approved by @toiletgranny 

![Zrzut ekranu 2022-06-3 o 18 37 41](https://user-images.githubusercontent.com/13706246/171908330-aff1b70f-92bf-43d1-95e7-5edeecd7c82e.png)
![Zrzut ekranu 2022-06-3 o 18 37 47](https://user-images.githubusercontent.com/13706246/171908333-8a7640fb-f513-434e-a444-1c6c52a1fffc.png)

2022-06-03 16:43 UTC, rafalpawlow commented on packages/atlas/src/components/Tooltip/Tooltip.stories.tsx
> +    customContent={args.customContent && <div style={{ border: '1px solid red' }}>Cusom content</div>}
typo
```suggestion
    customContent={args.customContent && <div style={{ border: '1px solid red' }}>Custom content</div>}
```

2022-06-03 17:18 UTC, rafalpawlow requested changes

2022-06-03 17:18 UTC, rafalpawlow commented on packages/atlas/src/components/Tooltip/Tooltip.tsx
> +  const content = customContent ? (
Wouldn't this to the job?
```suggestion
const content = customContent || (
    <TooltipContent headerText={!!headerText}>
      <TooltipHeader headerText={!!headerText}>
        {icon && (
          <IconWrapper>
            <StyledSvgAlertsInformative24 />
          </IconWrapper>
        )}
        {headerText && <TooltipText variant="h100">{headerText}</TooltipText>}
      </TooltipHeader>
      {text && text.length && (
        <TooltipText withIcon={!!icon} headerText={!!headerText} variant="t100">
          {text}
        </TooltipText>
      )}
    </TooltipContent>
  )
```

2022-06-03 19:12 UTC, kdembler commented on packages/atlas/src/components/Tooltip/Tooltip.tsx
> +  const content = customContent ? (
It's the same thing really

2022-06-03 19:14 UTC, kdembler commented
> It seems like multiline doesn't do anything except padding. In previous implementation oneLine had max-width: 400px and it was approved by @toiletgranny

Well that seems wrong, there is a section about sizes in Figma and it outlines what max-width the component should have based on variant: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6215%3A144771

2022-06-06 08:58 UTC, toiletgranny commented
> In previous implementation `oneLine` had `max-width: 400px` and it was approved by @toiletgranny
Yes, I remember discussing this together, but frankly, I can't recall what was the reason for that. @rafalpawlow, unless you remember it better than I do (in which case let me know), I would say that in the documentation I trust, and therefore, the implementation in this PR is fine by me.

2022-06-06 11:02 UTC, rafalpawlow commented
@toiletgranny TBH I don't remember why we decided it...

2022-06-06 11:02 UTC, rafalpawlow approved these changes

2022-06-06 11:17 UTC, merged