Select component
Joystream/atlas pull request #2848
Opened 2022-06-09 12:05 UTC by drillprop

Fix #2708

2022-06-09 12:10 UTC, kdembler requested changes
It doesn't seem the first point from AC has been completed?

> Extract List component from the ContextMenu. This would be just a styled list of ListItem components. It needs to support passing arbitrary props to both the container and items, so it can be used with downshift inside the Select. It should have a size prop. Then the ContextMenu is just a List wrapped in Popover

2022-06-10 08:34 UTC, kdembler commented
Needs to target `dev` (and optionally rebase)

2022-06-14 06:50 UTC, toiletgranny requested changes
Nice! ❤️

1. **As is:** Distance between the icon and the value is set to `4px`.
**To be:** `8px` in both size variants (just like in the Input component).
2. **As is:** The width of the bottom border is set to `2px` on the default state, and `1px` on focus.
**To be:**  It should be the other way around.
3. **As is:** `ListItem` component size variant is set to `Large`.
**To be:** [As per Figma documentation:](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7479%3A154979) a medium-sized `ListItem` component should be used for the large-sized `Select` component, and a small-sized `ListItem` component should be used for the medium-sized `Select` component.
4. Note, that I was not able to test[ a multi-select variant of the `Select` component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7483%3A149489). Did we drop it from the scope?

2022-06-14 06:57 UTC, drillprop commented
> 4. Note, that I was not able to test[ a multi-select variant of the `Select` component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7483%3A149489). Did we drop it from the scope?

Yeah: 
> Support for selecting multiple values is out of the scope of this PR

We will tackle this some other time.

2022-06-14 08:36 UTC, drillprop commented
> Nice! ❤️
> 
> 1. **As is:** Distance between the icon and the value is set to `4px`.
>    **To be:** `8px` in both size variants (just like in the Input component).
> 2. **As is:** The width of the bottom border is set to `2px` on the default state, and `1px` on focus.
>    **To be:**  It should be the other way around.
> 3. **As is:** `ListItem` component size variant is set to `Large`.
>    **To be:** [As per Figma documentation:](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7479%3A154979) a medium-sized `ListItem` component should be used for the large-sized `Select` component, and a small-sized `ListItem` component should be used for the medium-sized `Select` component.

Everything should be fixed. I also fixed the border issue that you mentioned here: https://github.com/Joystream/atlas/pull/2858#pullrequestreview-1004335298 (point 2)

Just for clarification, we use shared styles for all form components, but I have to update borders also here, since this is a different PR, and the text area PR isn't merged yet.

2022-06-14 09:09 UTC, kdembler requested changes
![Screenshot 2022-06-14 at 11 08 35](https://user-images.githubusercontent.com/12646744/173539921-236b6113-2be6-4b41-9ce3-64bd1c112d3e.jpg)

2022-06-14 09:51 UTC, toiletgranny requested changes
Perfect, thanks, we're almost there! Two more things I found:

1. Now it seems like the placeholder/value is too far away from the left edge of the component when the icon is not present. ![CleanShot 2022-06-14 at 11 47 29](https://user-images.githubusercontent.com/35307309/173548350-29ccc0a7-c2f2-4a07-af2e-a04158a91d65.png)
2. The red bottom border disappears upon hovering when the `error` styling is applied. Worth double-checking with `Input` and `Textarea` components, too, I think.

Once the two above issues are resolved, this is good to go to me! <3 Looks stunning!

2022-06-15 20:17 UTC, eldiegod approved these changes
Looks good, shame Storybook build is still broken

2022-06-15 20:17 UTC, eldiegod commented on packages/atlas/src/components/_inputs/Select/Select.tsx
> +    ConsoleLogger.warn('Select: inlineLabel and icon are mutually exclusive. icon will be ignored.')
good idea, maybe even worth to log as an error

2022-06-16 08:00 UTC, kdembler reviewed
Also, shouldn't we use pointer cursor when the user hovers over the select?

2022-06-16 08:00 UTC, kdembler commented on packages/atlas/src/components/List/List.styles.ts
> +import { ListItemSizes } from '../ListItem/ListItem.styles'
Could we re-export this type in `ListItem/index.ts`? We should avoid multiple imports from "internal" styles files

2022-06-20 11:02 UTC, drillprop commented on packages/atlas/src/components/_inputs/Select/Select.tsx
> +    ConsoleLogger.warn('Select: inlineLabel and icon are mutually exclusive. icon will be ignored.')
Hmm, yeah - good idea. Error is much more prominent

2022-06-20 11:37 UTC, drillprop commented on packages/atlas/src/components/List/List.styles.ts
> +import { ListItemSizes } from '../ListItem/ListItem.styles'
fixed

2022-06-20 11:49 UTC, drillprop commented
> Also, shouldn't we use pointer cursor when the user hovers over the select?

I asked Adam about cursors and I'm waiting for a response.

2022-06-20 12:40 UTC, toiletgranny approved these changes
> Also, shouldn't we use pointer cursor when the user hovers over the select?

Following the behavior of the [native, unstyled `<select>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select), I'd recommend not to use the pointer on hover. For select options, I'm fine with using the pointer.

@drillprop To me, it's great! The very last thing, a cherry on top, would be changing the "Select option" placeholder to just say "Select", as per the designs. And that's it! 🚀

2022-06-20 15:17 UTC, kdembler approved these changes

2022-06-20 15:23 UTC, merged