Option card
Joystream/atlas pull request #2864
Opened 2022-06-14 15:25 UTC by eldiegod

fixes: #2713

2022-06-15 09:07 UTC, drillprop requested changes

2022-06-15 09:07 UTC, drillprop commented on packages/atlas/src/views/studio/VideoWorkspace/VideoForm/VideoForm.tsx
> +                caption="Visible to all"
Since you created OptionCardGroup we could use it in form and see this component in action.

2022-06-15 09:07 UTC, drillprop commented on packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/SetUp/SetUp.tsx
> +                    caption="Pick the winning bid or cancel anytime"
Same as above

2022-06-15 09:07 UTC, drillprop commented on packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/ListingType/ListingType.tsx
> +          caption="Sell it for a fixed price only. No bids."
Same as above, I guess

2022-06-15 09:07 UTC, drillprop commented on packages/atlas/src/components/_inputs/OptionCard/OptionCard.styles.ts
> +        box-shadow: inset 0 -1px 0 0 ${getOptionCardBorderColorHover({ checked, error, disabled })};
border thickness for the checked option card is 2px.

2022-06-20 12:33 UTC, drillprop commented on packages/atlas/src/components/_inputs/OptionCard/OptionCard.styles.ts
> +        box-shadow: inset 0 -1px 0 0 ${getOptionCardBorderColorHover({ checked, error, disabled })};
This is still wrong. Maybe I left a comment in the wrong place, so sorry for the confusion. 

When I hover on the unchecked option card the box-shadow changes to 2px: 
![image](https://user-images.githubusercontent.com/51168865/174602172-fea0812e-7f2f-4569-b516-33d71c9fefe6.png)
In the design it's 1px 
![image](https://user-images.githubusercontent.com/51168865/174602325-bad3f9fb-fa75-476f-90be-4b7cc3e919d7.png)

2022-06-20 12:48 UTC, drillprop requested changes
Also, when you click on the option card, we should change the background of the OptionCard

![image](https://user-images.githubusercontent.com/51168865/174605074-ac4b1373-243a-446b-98ec-229fd02343b9.png)

2022-06-20 12:48 UTC, drillprop commented on packages/atlas/src/components/_inputs/OptionCardGroup/OptionCardGroup.stories.tsx
> +    helperText: 'Radio helper text',
```suggestion
```
not needed

2022-06-20 12:48 UTC, drillprop commented on packages/atlas/src/views/studio/VideoWorkspace/VideoForm/VideoForm.tsx
> +            <OptionCardGroupRadio
Not working for me. I tried to edit my video and set it to unlisted and nothing happened once the transaction was done.

2022-06-21 10:08 UTC, eldiegod commented
Fixed video unlisting and the rest of feedback

2022-06-21 14:13 UTC, drillprop approved these changes
LGTM!

2022-06-22 10:46 UTC, toiletgranny reviewed
All changes listed in the changelog are implemented beautifully, thanks! 

The one little detail I'd consider is replacing the `<h6>` tag used for rendering the option card's label with a ` <label>` tag, if that's possible in our case. Would that be possible, @drillprop?

2022-06-22 10:56 UTC, drillprop commented
> All changes listed in the changelog are implemented beautifully, thanks!
> 
> The one little detail I'd consider is replacing the `<h6>` tag used for rendering the option card's label with a ` <label>` tag, if that's possible in our case. Would that be possible, @drillprop?

But there is a label already on this option card: 
![image](https://user-images.githubusercontent.com/51168865/175011802-0a5dad4b-1639-40dd-9abe-38fdd9da8858.png)
Wrapping input in the label is much more comfortable because you don't need to set `for` for label and `id` for inputs. I'd opt not to change that.

But I also agree that we shouldn't use the h6 tag, I guess this could be just `span`.

2022-06-22 10:59 UTC, toiletgranny approved these changes
Oh, haven't noticed that, but — of course — I trust your judgment. And yes, dropping the `<h6>` tag feels like a good idea!

2022-06-22 11:58 UTC, merged