Use BigNumbers for all token values
Joystream/atlas pull request #2983
Opened 2022-07-08 10:33 UTC by eldiegod

2022-07-12 11:13 UTC, rafalpawlow requested changes
Something is wrong with NFT widget (`video/38`)

Also I see worker error in console
![Zrzut ekranu 2022-07-12 o 13 13 02](https://user-images.githubusercontent.com/13706246/178477293-1fca0e35-df48-4ec1-b76d-c15400118eb2.png)

This error is on `cartage` I don't think I should fix this in this PR.

2022-07-12 12:48 UTC, drillprop commented
> Also I see worker error in console ![Zrzut ekranu 2022-07-12 o 13 13 02](https://user-images.githubusercontent.com/13706246/178477293-1fca0e35-df48-4ec1-b76d-c15400118eb2.png)

This is on `cartage`. I don't think I should fix this in this PR

As for the NFT Widget, I fixed token names - but you'll still see 0 as a price. This is because BN only supports integers. I'm not sure yet if I should change the library, asked @kdembler about it. 

As for the infinite loading - this is happening only on deployment - locally I see the button, I think this is also connected to the error you mentioned(?).

2022-07-12 13:13 UTC, drillprop commented
> As for the infinite loading - this is happening only on deployment - locally I see the button, I think this is also connected to the error you mentioned(?).

Yeah, I can confirm that I see skeleton loaders in deployments in this PR https://github.com/Joystream/atlas/pull/2963

2022-07-15 08:32 UTC, rafalpawlow requested changes
When I try to start sale I see this when I select Auction

![Zrzut ekranu 2022-07-15 o 10 29 11](https://user-images.githubusercontent.com/13706246/179185454-35c881e4-a8c1-46ed-8bc6-bb41b76189bc.png)

2022-07-15 13:25 UTC, kdembler commented on packages/atlas/src/joystream-lib/lib.ts
> +      callback(availableBalance)
Could you also update `getAccountBalance` above? Or just delete it since I don't think it's used?

2022-07-15 13:28 UTC, kdembler commented on packages/atlas/src/utils/number.ts
> +    return new BN(number * TEN_BILLIONS)
This will potentially overflow, we need a different approach

2022-07-15 13:28 UTC, kdembler commented on packages/atlas/src/utils/number.ts
> +export const HapiBNToTokenNumber = (bn: BN) => {
This and the function below shouldn't be capitalized I think

2022-07-15 13:28 UTC, kdembler commented on packages/atlas/src/utils/number.ts
> +const TEN_BILLIONS = 10 ** 10
Let's move this to `@/config/joystream` and call `HAPI_TO_JOY_RATE` or something along the lines

2022-07-15 15:07 UTC, kdembler approved these changes

2022-07-18 12:09 UTC, rafalpawlow requested changes

2022-07-18 12:09 UTC, rafalpawlow commented on packages/atlas/src/providers/joystream/joystream.hooks.ts
> +import BN from 'bn.js'
Sometimes we use default import of `bn.js` and sometimes named. Can we standardize it?

2022-07-18 12:12 UTC, rafalpawlow requested changes

2022-07-18 12:12 UTC, rafalpawlow commented on packages/atlas/src/components/_nft/NftWidget/NftHistory.tsx
> +              <span>
Do we need this span?

2022-07-18 13:08 UTC, rafalpawlow approved these changes

2022-07-18 13:09 UTC, merged