Fix action bar in video form
Joystream/atlas pull request #2987
Opened 2022-07-11 14:33 UTC by rafalpawlow

Fixes #2950

2022-07-11 14:44 UTC, drillprop requested changes
It doesn't solve the issue entirely. I still need to click twice when I edit only the description.

2022-07-11 14:44 UTC, drillprop commented on packages/atlas/src/components/ActionBar/ActionBar.styles.ts
> +  z-index: 9999999;
do we actually need to update `z-index` here?

2022-07-12 11:10 UTC, drillprop approved these changes
I went through all the pages and everything seems to work fine. The video form works as it should as well. LGTM!

2022-07-13 12:57 UTC, kdembler requested changes
It seems all tooltips are broken?

https://user-images.githubusercontent.com/12646744/178738762-9507219e-9b56-4f95-aa7a-f76dcbd011d7.mp4

I also don't see anything if I hover over the description field in video form

2022-07-14 09:00 UTC, rafalpawlow commented
@kdembler I'm affraid we need that span inside tooltip component.

> I also don't see anything if I hover over the description field in video form

You mean title, right?

2022-07-14 10:03 UTC, kdembler approved these changes

2022-07-14 10:03 UTC, merged