Make NFT options in the context menu more consistent
Joystream/atlas pull request #3003
Opened 2022-07-18 17:07 UTC by rafalpawlow

Closes #2593

2022-07-20 09:01 UTC, toiletgranny requested changes
Thanks a lot, @rafalpawlow, for unpacking this uneasy task. It's already so much better, as I can finally perform the same operations on my NFTs without depending on the context. Naturally, there a few bugs that I found:

1. Let's get rid of the "Play in Joysteam" option. 
![CleanShot 2022-07-20 at 10 54 12](https://user-images.githubusercontent.com/35307309/179940888-744dbdeb-a85f-43cd-92f4-88db172df94d.png)
2. Both min bid and fixed price information are missing from the "Buy now" and "Place bid" options in the Publisher experience.
![CleanShot 2022-07-20 at 10 55 01](https://user-images.githubusercontent.com/35307309/179941168-16586f34-ef9a-485a-b51c-39f0cba1353d.png)
2. The current price value is wrong in this options. Also, please note that the color of all prices mentioned in ListItem component should be inherited from this component. Currently, they're all white. ![CleanShot 2022-07-20 at 09 28 33@2x](https://user-images.githubusercontent.com/35307309/179922892-8e653cb9-985b-42b5-afaa-d918d1464aa6.png)
3. I should not be able to place a new bid in an open auction if I have already placed one. I can either change it, or withdraw it (once the bid lock duration elapses).
![CleanShot 2022-07-20 at 10 28 49](https://user-images.githubusercontent.com/35307309/179935340-26889143-97f9-4c19-880b-83ef572dd708.png)
4. Having removed my NFT from sale, without refreshing the page, options in the dropdown are displayed as if my NFT was still on sale.
5. If no bids have been placed yet, the "Place bid" option [should include the "Min bid" value](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7583%3A149735).
![CleanShot 2022-07-20 at 10 36 38](https://user-images.githubusercontent.com/35307309/179937082-f40afb57-75b9-42b5-91c6-3cce36057ee5.png)
6. As a non-whitelisted member, I should not be able to bid nor buy an NFT for a fixed price. Currently, the dropdown displays the "Buy now" option, even though it should not be there for me. Please note that the "Place bid" option is indeed hidden.
![CleanShot 2022-07-20 at 10 43 05](https://user-images.githubusercontent.com/35307309/179938583-102f699b-2f13-4ea1-8517-9d904637f9d6.png)
7. As an NFT owner, having put my NFT on an open auction and having received offers,[ I should be able to review them.](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7583%3A149858) Currently this option is not displayed there. 
![CleanShot 2022-07-20 at 10 45 16](https://user-images.githubusercontent.com/35307309/179939733-4881e513-5c7f-4b3f-a8ac-0e8c79ba2373.png)

2022-07-25 17:43 UTC, rafalpawlow commented
@toiletgranny for point 5 I created separate issue https://github.com/Joystream/atlas/issues/3016

2022-07-26 07:15 UTC, toiletgranny requested changes
@rafalpawlow Thanks for reviewing it! Actually, when I was going through my list again right now, it seemed like 5) was already fixed, but perhaps there's some additional complexity to it. 

All of the things I found appeared to be fixed or addressed now, so thank you very much! ❤️ 

There is, however, one new thing that I noticed, which is that now the "Review bids" option seems to be displayed for me under all NFTs, including the ones which I have nothing in common with. This, of course, should not be the case; I should be able to access this option only under the NFTs I own.

![CleanShot 2022-07-26 at 08 44 45@2x](https://user-images.githubusercontent.com/35307309/180941088-2c6358ba-6004-401e-9bfc-cc6c414d5007.png)

2022-07-26 08:57 UTC, toiletgranny approved these changes

2022-07-26 10:46 UTC, drillprop requested changes

2022-07-26 10:46 UTC, drillprop commented on packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/NftForm.tsx
> +    contextMenuItems: [],
I've noticed a small bug: 

https://user-images.githubusercontent.com/51168865/180988300-7249507f-fce4-4375-b992-d7b92ef56b1c.mov

2022-07-26 12:12 UTC, drillprop approved these changes

2022-07-26 12:19 UTC, merged