Withdraw/Send funds extrinsics integration
Joystream/atlas pull request #3008
Opened 2022-07-19 20:38 UTC by rafalpawlow

Closes #2942 

Two things
* Transfer founds doesn't work properly because QN doesn't return success status for some reason
* Withdraw doesn't work because we don't have `rewardAccount` on Channel

2022-07-20 07:44 UTC, drillprop requested changes
The app does not work in production, once you connect the wallet.

2022-07-20 10:59 UTC, drillprop requested changes
When I'm trying to transfer the funds, the transaction dialog is stuck on `processing transaction` even if transaction is done.

2022-07-20 10:59 UTC, drillprop commented on packages/atlas/src/components/_overlays/SendTransferDialogs/SendFundsDialog.tsx
>    const handleSendFounds = async () => {
```suggestion
  const handleSendFunds = async () => {
```

2022-07-20 10:59 UTC, drillprop commented on packages/atlas/src/components/_overlays/SendTransferDialogs/SendFundsDialog.tsx
> +          (await joystream.extrinsics).sendFunds(data.account || '', amount, proxyCallback(updateStatus)),
we should use `data.amount` here. Also, this should be multiplied by 10_000_000_000. We're sending tokens and each token is `10_000_000_000` hapi.

2022-07-20 10:59 UTC, drillprop commented on packages/atlas/src/joystream-lib/extrinsics.ts
> +  async sendFunds(destinationAccount: MemberId, value: BN, cb?: ExtrinsicStatusCallbackFn) {
I didn't manage to transfer funds to another account. When I checked transactions in https://polkadot.js.org/apps the value is always 0. Something isn't working with passing BN here probably.

2022-07-22 09:05 UTC, drillprop requested changes
A couple of things: 
- Withdraw balance should be possible now. 
- I just had a call with Adam, and with Send dialog we should be able to send funds to _**_any_**_ account. This means that we could send funds also to the channel account. So, we shouldn't validate if a member exists in `Destination account` input(but we should show the avatar for the member if address points to member account)

2022-07-22 09:05 UTC, drillprop commented on packages/atlas/src/components/_overlays/MemberDropdown/MemberDropdown.tsx
>      const channelBalance = /* useSubscribeAccountBalance(selectedChannel?.rewardAccount) || */ new BN(0) // TODO: fix for Carthage
We have rewardAccount now. We should be able to use it.

2022-07-22 09:13 UTC, drillprop requested changes
Also, sending funds doesn't seem to work right now - we always send 0 to a destination account:
![image](https://user-images.githubusercontent.com/51168865/180406410-0bb19686-210a-4558-8160-f90386fed553.png)

This is probably a BN issue, let's pass the number to `sendFundsTx`(in tokens) and convert them to Hapi. Check for example `makeNftBidTx` or another method which has a price in parameters.

2022-07-26 12:06 UTC, drillprop requested changes

2022-07-26 12:06 UTC, drillprop commented on packages/atlas/codegen.config.yml
> +schema: https://atlas-next.joystream.org/orion/graphql
Let's remove this change. This is being fixed here https://github.com/Joystream/atlas/pull/3029/files

2022-07-27 09:25 UTC, drillprop approved these changes

2022-07-27 14:20 UTC, kdembler approved these changes

2022-07-27 14:20 UTC, merged