carthage refactor and tweaks
Joystream/atlas pull request #3069
Opened 2022-08-03 17:52 UTC by kdembler

2022-08-03 20:12 UTC, drillprop requested changes
I'll look at the code and do more testing tomorrow, but I found already that you reintroduced this [bug](https://github.com/Joystream/atlas/issues/3018)
Check the video. 

https://user-images.githubusercontent.com/51168865/182700071-171ba8a4-1733-45c9-8a0c-ed9d94aae40e.mov

2022-08-04 07:51 UTC, drillprop reviewed
Besides the above, it works well and the code looks good 👍🏻

2022-08-04 07:51 UTC, drillprop commented on packages/atlas/src/components/Fee/Fee.stories.tsx
>  const Template: Story<FeeProps> = (args) => (
```suggestion
const Template: Story<FeeProps & { amountToken: number }> = (args) => (
```

2022-08-04 07:51 UTC, drillprop commented on packages/atlas/src/components/Fee/Fee.stories.tsx
> +    <Fee {...args} amount={tokenNumberToHapiBn((args as any).amountToken)} />
```suggestion
   <Fee {...args} amount={tokenNumberToHapiBn(args.amountToken)} />
```
I guess this should do the job.

2022-08-04 10:12 UTC, drillprop approved these changes
That's a massive improvement, looks good to me! 🎉

2022-08-04 10:15 UTC, rafalpawlow approved these changes
Didn't find any issues 🙌

2022-08-04 10:15 UTC, merged