UI for adding subtitles
Joystream/atlas pull request #3094
Opened 2022-08-08 12:56 UTC by drillprop

#2490 
I'm still waiting for two icons in the context menu(cc and download). 👇🏻  Once Kuba adds them I update my code as well.
![image](https://user-images.githubusercontent.com/51168865/183423150-4c269549-f78d-4d2c-b600-1eed38ffd68a.png)

2022-08-09 10:32 UTC, rafalpawlow requested changes
I think we should add description here
![Zrzut ekranu 2022-08-9 o 10 43 08](https://user-images.githubusercontent.com/13706246/183627412-6e47ac4e-7eec-4e5e-8f14-99fdd533f7d7.png)

2022-08-10 09:19 UTC, drillprop commented
Draft for now. I need to do some changes regarding closed captions

2022-08-10 13:34 UTC, drillprop commented
After some discussions with Kuba, we decided to make some tweaks to the flow. All the changes are listed here: https://github.com/Joystream/atlas/issues/3101.

2022-08-11 08:00 UTC, rafalpawlow requested changes

2022-08-11 08:00 UTC, rafalpawlow commented on packages/atlas/src/components/_overlays/ContextMenu/ContextMenu.tsx
> +  customWidth = 192,
I think we don't need this anymore

2022-08-11 11:25 UTC, rafalpawlow approved these changes

2022-08-12 07:23 UTC, kdembler requested changes

2022-08-12 07:23 UTC, kdembler commented on packages/atlas/src/components/_inputs/ComboBox/ComboBox.tsx
> -      if (!inputValue) {
After changes to this file, whitelisting in NFT sale form doesn't work. No requests are fired after I type in member name

2022-08-12 07:23 UTC, kdembler commented on packages/atlas/src/components/_inputs/SubtitleBox/SubtitleBox.tsx
> +          'It looks like you selected a file format which is not supported. Reselect file and choose .webvtt file to proceed.',
```suggestion
          'It looks like you selected a file format which is not supported. Reselect file and choose .vtt file to proceed.',
```

2022-08-12 07:23 UTC, kdembler commented on packages/atlas/src/components/_inputs/SubtitlesComboBox/SubtitlesCombobox.tsx
> +      .flat(1)
I think `1` is a default

2022-08-12 14:14 UTC, kdembler approved these changes

2022-08-12 14:14 UTC, merged