Fix crashing embedded player
Joystream/atlas pull request #3103
Opened 2022-08-10 15:17 UTC by rafalpawlow

@drillprop found out that when ending overlay shows up in embedded player, app crashes. It was caused by `ChannelLink` which uses `useConfirmationModal`. I added `ConfirmationModalProvider` to `CommonProviders`.

2022-08-11 06:17 UTC, drillprop requested changes
Still crashes when I switch to mobile view and click play. iI looks like we're missing the Overlay provider as well? 
![image](https://user-images.githubusercontent.com/51168865/184074590-d2b51650-a6d8-43e9-a181-90bb27463478.png)

2022-08-11 14:22 UTC, rafalpawlow commented
@drillprop This is fixed on dev branch 
https://github.com/Joystream/atlas/blob/dev/packages/atlas/src/CommonProviders.tsx#L20

2022-08-12 09:27 UTC, kdembler commented
Let's change base to `dev`

2022-08-12 10:15 UTC, rafalpawlow commented
@kdembler done

2022-08-12 10:50 UTC, kdembler approved these changes
LGTM, let's get approval from @drillprop as well

2022-08-12 10:50 UTC, drillprop approved these changes

2022-08-12 11:52 UTC, merged