NFT purchase improvements
Joystream/atlas pull request #3143
Opened 2022-08-18 14:12 UTC by rafalpawlow

Closes #3070 

**Design**
https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=1036%3A102823

2022-08-18 14:36 UTC, kdembler requested changes
There's a split second after you input the bid that the bid in summary is shown before the loading triggers:

https://user-images.githubusercontent.com/12646744/185422009-d5b99f07-de12-492c-be6a-8718f8971b39.mp4

2022-08-19 06:58 UTC, drillprop requested changes
I still don't like the flow and how validation works there, but not sure if the designs are up to date. 
1. When I click buy now and I don't have money. I still see the big call to action button "buy nft", which encourages me as a user to click: 
![image](https://user-images.githubusercontent.com/51168865/185560109-24ed7b9e-7c0f-4054-86e6-739bb72e8a1e.png)
2.  In the inputs I know that at some point we decided that we will do validation on blur.  But should we actually do it that way in this case? Maybe we could use `onChange` mode in this case.  I'm still confused about what's happening to be honest

Can you consult this with a designer? I mean, I'm fine if we leave it as it is and if we decide to change that we could do this as a follow-up.

2022-08-19 06:58 UTC, drillprop commented on packages/atlas/src/views/global/NftPurchaseBottomDrawer/NftPurchaseBottomDrawer.tsx
>                    </Text>
In the design there is a short text: "You need to fill out the amount first" when the input is empty. You didn't include that. 
https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=1036%3A102849

2022-08-19 10:31 UTC, toiletgranny commented
@drillprop That's a fair point. The UX here is far from ideal, and the designs did not really provide a solid solution for that case. That's why I created [this issue](https://github.com/Joystream/atlas/issues/3084#issue-1329710328), and now that I think of it, @kdembler, I think we should reopen it and let me take a closer look and think about it. I'd love to give you guys some ideas right now, but I really have to get back to Pioneer (cc @dmtrjsg)...

If you agree, I'd leave this implementation in its current state (in the PR) and open up a new PR once we know how to handle this case properly.

2022-08-19 13:56 UTC, drillprop commented
> @drillprop That's a fair point. The UX here is far from ideal, and the designs did not really provide a solid solution for that case. That's why I created [this issue](https://github.com/Joystream/atlas/issues/3084#issue-1329710328), and now that I think of it, @kdembler, I think we should reopen it and let me take a closer look and think about it. I'd love to give you guys some ideas right now, but I really have to get back to Pioneer (cc @dmtrjsg)...
> 
> If you agree, I'd leave this implementation in its current state (in the PR) and open up a new PR once we know how to handle this case properly.

Thanks for your input, I'd opt not to reopen your issue. Perhaps we could create another issue (third one😅) and rethink validation strategies in these particular cases - `buy now nft` and `placing bid`. And yeah, I'm also fine with doing this some other time. @kdembler wdyt?

2022-08-19 14:02 UTC, drillprop approved these changes
LGTM

2022-08-22 08:42 UTC, kdembler approved these changes

2022-08-22 08:51 UTC, merged