Pagination
Joystream/atlas pull request #315
Opened 2021-02-11 12:40 UTC by drillprop

Fix #253

2021-02-15 07:18 UTC, mikkio-j commented on src/shared/components/Pagination/Pagination.tsx
> +            {i + startingIdx}
First displayed page is 0 - I know it feels natural but I believe we should display 1 as a first page in the component

2021-02-15 07:18 UTC, mikkio-j commented on src/shared/components/Pagination/Pagination.stories.tsx
> +import { MemoryRouter, Route, useLocation } from 'react-router-dom'
```suggestion
import { MemoryRouter } from 'react-router-dom'
```

2021-02-15 07:18 UTC, mikkio-j commented on src/shared/components/Pagination/Pagination.stories.tsx
> +const Router: React.FC = (children) => {
We don't need that since you are using decorator

2021-02-17 10:20 UTC, mikkio-j approved these changes

2021-02-17 10:39 UTC, kdembler requested changes
I'll get to the code later, looked at the storybook so far:
1) I'm not sure we should involve routing in page change. I don't see that as a benefit and it certainly complicates the data flow from this component to the consumer. I'd rather see that as a simple `value/onChange` component. What do you think?
2) The right arrow doesn't seem to work, whenever I click it, the 2nd page is chosen, regardless of what is currently selected
3) If I click the last element, the items should "scroll" to reveal the next items. For example, if there are 10 pages, 5 are visible at the beginning and I select the 5th page, the list should probably show pages 2-6 so I'm able to select the next one

2021-02-17 17:42 UTC, kdembler commented on src/shared/components/Pagination/Pagination.stories.tsx
> +    take: {
This wasn't updated

2021-02-17 17:42 UTC, kdembler commented on src/shared/components/Pagination/Pagination.tsx
> +  itemsForPage?: number
Let's use `itemsPerPage` or `itemsOnPage`, `for` doesn't seem correct to me

2021-02-18 10:33 UTC, kdembler commented on src/shared/components/Pagination/Pagination.tsx
> +  const [page, setPage] = useState(currentPage)
Let's just rely on value from outside, we probably don't need internal state here

2021-02-18 10:33 UTC, kdembler commented on src/shared/components/Pagination/Pagination.tsx
> +  currentPage = 1,
Let's use 1-based indexing only for display, the values should be 0-based

2021-02-18 10:33 UTC, kdembler commented on src/shared/components/Pagination/Pagination.tsx
> +  onClick?: (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void
Let's make this `onChange` / `onPageChange` and pass the new page number to the consumer

2021-02-18 13:31 UTC, kdembler approved these changes

2021-02-18 13:31 UTC, merged