Video settings indicator animation
Joystream/atlas pull request #3163
Opened 2022-08-22 17:00 UTC by rafalpawlow

Closes #2385 

https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2127%3A135540

2022-08-23 11:35 UTC, drillprop requested changes
The indicator doesn't show when you press `C` on the keyboard and I think it should.

2022-08-23 11:35 UTC, drillprop commented on packages/atlas/src/components/_video/VideoPlayer/ControlsIndicator.tsx
> +        )
I'm thinking, maybe we could just pass `player` here? Function with 5 parameters feels awkward

2022-08-23 11:35 UTC, drillprop commented on packages/atlas/src/components/_video/VideoPlayer/VideoPlayer.styles.ts
> +
As I said in our meeting - let's consult this with a designer first. Maybe there is a better solution

2022-08-24 07:32 UTC, drillprop requested changes
Unfortunately, it's still a little bit buggy :/ 

https://user-images.githubusercontent.com/51168865/186358085-5567a07e-ce62-4434-9327-38fe726c0e14.mov

2022-08-29 12:08 UTC, drillprop approved these changes
LGTM

2022-08-29 13:43 UTC, kdembler requested changes
1. The animation for changing animation speed still mentions the old speed in "Speed set to ___" message. For example, I change from 1x to 1.5x and it says "Speed set to 1x"
2. When I click the "CC" button (outside of settings), no animation is applied. Is that desired?

2022-08-29 13:49 UTC, rafalpawlow commented
1. This bug doesn't appear in Chrome and Safari, I'll investigate it
2. I'll ask @toiletgranny

2022-08-29 13:57 UTC, kdembler commented
1. Oh yeah, that was on Firefox

2022-08-30 11:02 UTC, kdembler approved these changes

2022-08-30 11:02 UTC, merged