Fix unsupported file type dialog
Joystream/atlas pull request #3185
Opened 2022-08-29 18:34 UTC by rafalpawlow

Fixes #2910

2022-08-31 13:13 UTC, drillprop requested changes
This PR fixes the problem but I found another issue. When I pick a video that has some incorrect metadata the warning dialog I showing to me twice. I can send you the file to test it out if you want. 

https://user-images.githubusercontent.com/51168865/187686591-5e0b8b86-2d3a-432d-8ed9-4df4f487968c.mov

I'm fine if you do this as followup

2022-08-31 13:13 UTC, drillprop commented on packages/atlas/src/components/_inputs/FileSelect/FileSelect.tsx
> +  setError: Dispatch<SetStateAction<string | null>>
I would keep the `onError` name. Also `Dispatch<SetStateAction<string | null>>` pretty much the same as `(error: string | null) => void`, and the latter is more readable to me to be honest.

2022-09-02 05:38 UTC, kdembler commented
> I'm fine if you do this as followup

Let's fix it here

2022-09-06 11:37 UTC, drillprop approved these changes
LGTM

2022-09-06 12:23 UTC, merged