Update member dropdown
Joystream/atlas pull request #3187
Opened 2022-08-31 07:58 UTC by drillprop

Fix #2556 
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3201%3A111990

2022-09-01 08:28 UTC, kdembler commented
Can't test right now because of a failed build but when checking it out yesterday I wasn't able to initialize funds transfer, the link would always open dialog for withdrawing funds from channel, even if I was in the "member mode"

2022-09-01 09:34 UTC, drillprop commented
> Can't test right now because of a failed build but when checking it out yesterday I wasn't able to initialize funds transfer, the link would always open dialog for withdrawing funds from channel, even if I was in the "member mode"

fixed

2022-09-01 10:59 UTC, rafalpawlow requested changes
Works pretty well, few small issues

- [x] this icon seems to have wrong size
![Zrzut ekranu 2022-09-1 o 12 23 26](https://user-images.githubusercontent.com/13706246/187897364-361dc1e9-b25b-4872-b904-bbb0d721189c.png)
![Zrzut ekranu 2022-09-1 o 12 23 43](https://user-images.githubusercontent.com/13706246/187897371-19ea44e0-f642-4804-a2bf-f589fbf2c880.png)

- [x] tooltip has wrong width
![Zrzut ekranu 2022-09-1 o 12 39 29](https://user-images.githubusercontent.com/13706246/187897541-6952fa59-7861-45eb-8b41-b1ec40039855.png)
![Zrzut ekranu 2022-09-1 o 12 40 31](https://user-images.githubusercontent.com/13706246/187897544-a72dc8e8-0744-4733-9908-64eea33cba15.png)

- [ ] we agreed to add `interactive` flag to the tooltip I mentioned above
- [ ] when I touch tooltip on mobile, it fires links and buttons beneath (not sure if we can do something about it)
- [ ] do you think we could add some offset to this tooltip like it's on the design? Currently, it's a bit of a meld with dropdown for me

![Zrzut ekranu 2022-09-1 o 12 56 29](https://user-images.githubusercontent.com/13706246/187898053-e53f20f2-0c91-48bf-8d16-bb0a0642b940.png)

2022-09-01 10:59 UTC, rafalpawlow commented on packages/atlas/src/components/_overlays/MemberDropdown/MemberDropdownNav.styles.ts
> +  right: -8px;
I think we should use `sizes` here

2022-09-01 10:59 UTC, rafalpawlow commented on packages/atlas/src/components/_overlays/MemberDropdown/MemberDropdownNav.styles.ts
> +  gap: 5px;
I know this is not your change, but it should be `4px`, let's also change it to `sizes`

2022-09-01 13:18 UTC, drillprop commented
> * [ ]  do you think we could add some offset to this tooltip like it's on the design? Currently, it's a bit of a meld with dropdown for me

What do you mean? The offset is set to 8px by default

2022-09-01 13:45 UTC, rafalpawlow commented
@drillprop Now it is ok, but before the tooltip was exactly in the middle of the dropdown. Have you changed anything in this regard?

2022-09-01 13:46 UTC, rafalpawlow commented
@drillprop One more question. Shouldn't we show channel variant as default in studio?

2022-09-02 08:56 UTC, drillprop commented
> @drillprop Now it is ok, but before the tooltip was exactly in the middle of the dropdown. Have you changed anything in this regard?

We had this offset set previously as well, but yeah I did a small change.
The tooltip is appended to MemberDropdown container now, not the HTML element which keeps the account balance inside https://github.com/Joystream/atlas/pull/3187/commits/1df6e12b99c2e1fe7156dd0475d03d1539fb9efd
(check the `containerRef` prop)
> @drillprop One more question. Shouldn't we show channel variant as default in studio?

Yeah, I guess you're right. I'll change that.

2022-09-02 09:21 UTC, toiletgranny requested changes
@drillprop It felt soo good to take this component for a spin! The animations you implemented are buttery smooth! 🥰

1. **As is:** Account balance tooltip appears upon hovering over this entire area. This causes accidental tooltip triggers. 
    <img src="https://user-images.githubusercontent.com/35307309/188082889-8ac98032-dbd4-4f2a-ae00-dd3803ae3400.png" width="256">
**To be:** Ideally, the tooltip is triggered when hovering specifically over the numerical value and the JOY icon.

2. **As is:** In the total balance tooltip, JOY token amounts are displayed using the `--typography-desktop-t200` CSS variable. Also, the the contents of each row in the breakdown is not centered vertically.
**To be:** JOY token amounts should be displayed using the `--typography-desktop-t200-strong` CSS variable, and there should be `align-items: center` applied on all rows in the breakdown (make sure the "[lock-icon] Invitation lock" label remains centered vertically after applying this change).

4. **As is:** I can't seem to be able to scroll down the contents of the member dropdown.
    <img src="https://user-images.githubusercontent.com/35307309/188083640-8e27024c-863c-435f-b47f-7c9de62202b5.gif" width="256">
**To be:** I should be able to do so.

5. **As is:** When in Studio, the Member dropdown component opens up in the Member mode by default.
**To be:** When in Studio, the Member dropdown component should open up in the Channel mode by default.

6. **As is:** Having just one channel created, I see the "Switch channel" list item in the Channel mode of the Member dropdown component. 
    <img src="https://user-images.githubusercontent.com/35307309/188101752-12d5cec4-4c32-4b46-9420-df79743584e5.png" width="256">
**To be:** As long as I have just one channel, I should see the "Add new channel" list item instead of the "Switch channel" [(documentation reference)](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3201%3A114961).

7. All transition animations seem to fire with a slight delay, and rather than animating from 0% to 100%, they go from ~25% to 100% only. This is best inspected if recorded on the screen and then played in slow motion. Happy to jump on a call to discuss details. 

8. **As is:** Hovering over the little icon indicators in the "Member dropdown switcher" component triggers tooltip visibility but does not lighten up the avatar and does nothing upon pressing.
   <img src="https://user-images.githubusercontent.com/35307309/188103700-7c25528a-880d-4020-9cb4-63f0cfb7d7d1.png" width="256">
   **To be:** Ideally, hover interactions should always reflect what can be clicked on. In this case, I'd opt for either not displaying the tooltip at all when hovering over the little icon in the corner, OR letting the user click on the entire area of the "Member dropdown switcher" instead of just the Avatar component itself, as it's implemented now. In the latter case, the Avatar should lighten up upon hovering over the little icon in the corner too.

9. **As is:** Having created a new channel from the "Switch channel" -> "Add new channel" menu (which I already pointed out is not correct if I have only one channel), opening the Member dropdown again I can see it still in the "Switch channel" mode (it should be in the "home" mode), and its height doesn't reflect the new list contents.
   <img src="https://user-images.githubusercontent.com/35307309/188105078-a26a39b8-911f-4cb3-be46-a58cbaea43eb.png" width="256">
   **To be:** Opening the Member dropdown component should always default to the "home" screen of either the Channel mode or Member mode, depending on the experience. 

10. **As is:** Changing channel in the Viewer experience doesn't do anything. 
    **To be:** It should set the active channel to the one I clicked on. This will be important once we implement the YouTube Partner Program landing page.
   <img src="https://user-images.githubusercontent.com/35307309/188106097-4aeda9a2-0cb4-40a9-899e-2bfafb6fd6fe.gif" width="256">

2022-09-02 13:59 UTC, toiletgranny commented
@drillprop Thanks a lot! I can see that points 2 and 4 are not 100% addressed yet, so let me clarify:
- For the 2nd point, I meant applying this bolder text style token to all JOY token values on the right-hand side. Oh, and since we're here, is there a way to disable the above tooltip now that we have a richer one below? It feels very odd to have two tooltips for the same thing. 😅 
![CleanShot 2022-09-02 at 15 52 04](https://user-images.githubusercontent.com/35307309/188162941-c2c8bc6b-4969-487b-a068-d27b592fd19d.png)
   - Can we also make sure the lock icon and the "Invitation lock" label remain vertically centered in their surrounding container? 🙏
- For the 4th point, we're halfway there, but what I meant is that the Member dropdown should _always_ default to either the Member or Channel mode, based on the experience. This means that if I open up the Member dropdown in the Viewer experience, change its mode to Channel, close it and then reopen — ideally, I see it in the Member mode again because of the fact I'm still in the Viewer experience. Hope it makes sense! :D

2022-09-05 06:53 UTC, drillprop commented
> Can we also make sure the lock icon and the "Invitation lock" label remain vertically centered in their surrounding container?

It's already centered. I don't think I can center this lock more :P 

Besides that, everything should be fixed.

2022-09-06 13:49 UTC, rafalpawlow approved these changes

2022-09-07 10:27 UTC, merged