Fix issue with not being able to remove the member avatar
Joystream/atlas pull request #3193
Opened 2022-08-31 12:55 UTC by drillprop

Also:
- fix an issue with changing form to dirty, when you focus and blur on about text area
- improve calculating fees. Now, when the form is not dirty you'll see 0 fees. 

Fix #3192

2022-09-01 11:59 UTC, rafalpawlow commented on packages/atlas/src/providers/assets/assets.hooks.ts
> +  // if avatar is `undefined` it means that avatar is not loaded yes, If it's `null` it means that it's not set
typo 🙂
```suggestion
  // if avatar is `undefined` it means that avatar is not loaded yet, If it's `null` it means that it's not set
```

2022-09-01 13:55 UTC, rafalpawlow approved these changes

2022-09-02 05:33 UTC, kdembler requested changes

2022-09-02 05:33 UTC, kdembler commented on packages/atlas/src/providers/joystream/joystream.hooks.ts
> +          setLoading(false)
Why was this change needed? I did a quick test with commenting and this changes the fee display behavior:

https://user-images.githubusercontent.com/12646744/188065724-96084c9b-26b4-400b-a143-95dc98cd8269.mp4

Previously the fee would stay the same when signing the tx. Maybe this actually a problem in the CommentInput, I'm not sure, but we should check.

2022-09-02 05:34 UTC, kdembler commented on packages/atlas/src/providers/joystream/joystream.hooks.ts
> +          setLoading(false)
Also if I reject the signature, the fee stays 0

2022-09-05 11:59 UTC, kdembler approved these changes

2022-09-05 12:00 UTC, merged