fix and improve NftTile storybook
Joystream/atlas pull request #3250
Opened 2022-09-13 16:25 UTC by rafalpawlow

Closes #3151 

**Design**
https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=1805%3A133265

2022-09-14 09:19 UTC, drillprop requested changes
Found a few minor issues, besides those, look really solid 👍🏻

2022-09-14 09:19 UTC, drillprop commented on packages/atlas/src/views/global/YppDashboard/YppDashboard.tsx
> +      {/* TODO: add tooltip once it will show up on design */}
![image](https://user-images.githubusercontent.com/51168865/190108051-85deaf1b-784f-4bec-9f86-cf559268b0bd.png)

this icon is not for tooltips(check other banners in the app). It is just an icon and you didn't add this.

2022-09-14 09:19 UTC, drillprop commented on packages/atlas/src/components/WidgetTile/WidgetTile.tsx
> +        {tooltip && <Information {...tooltip} />}
This is probably the Information component issue, but the gap between the label and the header is too big, when the Information component is present: 
![image](https://user-images.githubusercontent.com/51168865/190109748-5a555839-1b40-4457-87f5-9f6e70b16e93.png)
![image](https://user-images.githubusercontent.com/51168865/190109822-e652170c-3894-43d1-bf33-9f284cff5909.png)

2022-09-14 09:19 UTC, drillprop commented on packages/atlas/src/views/global/YppDashboard/YppDashboard.styled.ts
> +import { css } from '@emotion/react'
You have a typo in the file name `YppDashboard.styled.ts` - should be `YppDashboard.styles.ts`

2022-09-14 09:19 UTC, drillprop commented on packages/atlas/src/components/WidgetTile/WidgetTile.tsx
> +  caption?: string | number
I'm not sure if we should put here string/number. What if we want to use here our NumberFormat component?

2022-09-14 09:19 UTC, drillprop commented on packages/atlas/src/views/global/YppDashboard/YppDashboard.styled.ts
> +  gap: ${sizes(1)};
I think we still should avoid using gap property with flex

2022-09-14 09:19 UTC, drillprop commented on packages/atlas/src/views/global/YppDashboard/YppDashboard.tsx
> +const TIERS = {
We could use an array here, right?

2022-09-14 12:39 UTC, drillprop approved these changes

2022-09-14 14:24 UTC, kdembler requested changes

2022-09-14 14:24 UTC, kdembler commented on packages/atlas/src/views/global/YppDashboard/YppDashboard.tsx
> +    actionButton: { text: 'Publish new video' },
This should open video workspace

2022-09-14 14:24 UTC, kdembler commented on packages/atlas/src/views/global/YppDashboard/YppDashboard.tsx
> +    actionButton: { text: 'Go to My videos' },
This should navigate to my videos

2022-09-14 14:24 UTC, kdembler commented on packages/atlas/src/views/global/YppDashboard/YppDashboard.tsx
> +import BN from 'bn.js'
Dashboard shouldn't be global, it should be only available in studio. For now, let's have YPP in viewer link to landing page and in studio, let's have it link to the dashboard, we'll update later

2022-09-14 14:24 UTC, kdembler commented on packages/atlas/src/views/global/YppDashboard/YppDashboard.tsx
> +} from '@/views/global/YppDashboard/YppDashboard.styles'
This should be relative import

2022-09-14 14:24 UTC, kdembler commented on packages/atlas/src/views/global/YppDashboard/YppDashboard.tsx
> +const REWARDS = [
Could we maybe move this and `TIERS` to a separate file to improve component's readability? Can be called `YppDashboard.config.ts`

2022-09-15 19:02 UTC, kdembler commented on packages/atlas/src/views/viewer/ViewerLayout.tsx
> +import { YppDashboard } from '@/views/studio/YppDashboard'
```suggestion
```

2022-09-15 19:02 UTC, kdembler commented on packages/atlas/src/views/viewer/ViewerLayout.tsx
> +  { path: relativeRoutes.viewer.yppDashboard(), element: <YppDashboard /> },
```suggestion
```

2022-09-15 19:44 UTC, kdembler approved these changes

2022-09-15 19:45 UTC, merged