Referral link
Joystream/atlas pull request #3259
Opened 2022-09-16 06:59 UTC by drillprop

Fix #3148 
I didn't do `Referral data added to storage (pre-populates referred field in the YP auth flow)`, because we don't have proper integration yet.

2022-09-19 13:46 UTC, rafalpawlow requested changes
Looks good, however there is a problem on mobile when channel name is too long. We probably should trim this

![Zrzut ekranu 2022-09-19 o 15 43 28](https://user-images.githubusercontent.com/13706246/191032092-025be6db-f1a3-4968-8f2b-da71561952e5.png)

2022-09-21 12:36 UTC, kdembler approved these changes

2022-09-21 12:51 UTC, toiletgranny requested changes
Looks nice! One last thing is changing the side padding from the `SM` breakpoint and lower so that it's `16px` instead of `24px`.

2022-09-21 14:26 UTC, kdembler commented
> Looks nice! One last thing is changing the side padding from the SM breakpoint and lower so that it's 16px instead of 24px.

Done!

2022-09-21 14:30 UTC, merged