Fix issues with updating channel
Joystream/atlas pull request #3300
Opened 2022-10-04 11:09 UTC by drillprop

Fix #3224 
While working on this task I found that updating a channel is pretty buggy right now. When testing, make sure that you manage: 
- create a new channel and set an avatar and cover
- update an existing channel without an avatar and cover
- update an existing channel with an avatar and cover
- update only one asset on an existing channel
- switch between channels while the edit channel form is open(check if the content in the form is updated correctly)
- update only one asset on an existing channel - either avatar or cover, and once this asset is uploaded and processed, try to update the channel again.

Just FYI, deleting assets won't be covered in this PR. It's still not working fully and we have a separate issue for this.

2022-10-11 11:49 UTC, rafalpawlow requested changes
1. All scenarios work pretty solid however, I have one doubt. After I upload an avatar I cannot update another one, first I need to delete the previously updated one. Not sure if this is expected behavior. Check the video below: 

https://user-images.githubusercontent.com/13706246/195081777-db276fe1-4e3d-46cb-b6d2-9a1fbfaf1100.mov

2. Do you think we could try to get rid of this as part of this PR? It appears after the channel is created and looks worrying
![Zrzut ekranu 2022-10-11 o 13 34 22](https://user-images.githubusercontent.com/13706246/195081954-d361d3ca-7436-4805-8e9b-651cb023f673.png)

2022-10-11 11:49 UTC, rafalpawlow commented on packages/atlas/src/providers/assets/assets.hooks.ts
> +    return contentId ? state.assets[contentId] : null
Why did you make this change?

2022-10-11 12:37 UTC, rafalpawlow commented
After a discussion with @drillprop we agreed that 1st point is expected behavior.

2022-10-12 12:17 UTC, drillprop commented
> 2. Do you think we could try to get rid of this as part of this PR? It appears after the channel is created and looks worrying
>    ![Zrzut ekranu 2022-10-11 o 13 34 22](https://user-images.githubusercontent.com/13706246/195081954-d361d3ca-7436-4805-8e9b-651cb023f673.png)

Fixed, I don't think we should worry about this warning.  The `NewAccount` event
is marked as a system event for some reason, I updated the if statement in `parseExtrinsicEvents`

2022-10-13 08:53 UTC, rafalpawlow approved these changes

2022-10-14 06:52 UTC, merged