Better error handling on filtered out videos
Joystream/atlas pull request #3301
Opened 2022-10-04 12:55 UTC by rafalpawlow

Closes #3213 

I blocked video `5` for tests, will remove it before merge

**Design**
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=6176%3A332457

2022-10-04 13:26 UTC, toiletgranny requested changes
Looking great, as always! As finishing touches, for the "Video unavailable", I have a few suggestions that I hope would not break the Video player component:
1. Remove `padding: 0px 12px` altogether,
2. Don't set `height`,
3. Don't set `overflow`,
4. Set `aspect-ratio` to `16 / 9`,
5. Changing the color of the body copy from `var(--color-core-neutral-300)` to `var(--color-text-default)` (this one was a mistake in designs, apologies).

For the secondary column:
1. I'd suggest dropping the `<div>` that's direct child of `.css-d7meg8`,
2. I'd suggest setting the `height` parameter on the `.css-o7pm0s` to `calc(100% - 160px)`.

Here's the end result:

https://user-images.githubusercontent.com/35307309/193830968-ef95e814-9875-4db7-87cc-5398169aa06c.mp4

2022-10-04 13:33 UTC, rafalpawlow commented
@toiletgranny we decided to not use `aspect-ratio` (even for video it's percentage padding) due to poor browsers coverage.

2022-10-04 14:03 UTC, toiletgranny commented
Ah, sure, of course! Hopefully, the things I suggested still work with the padding hack. If not, or if it requires a significant amount of tweaking and writing spaghetti code, then my only suggestion would be to set `512px` of `max-height` on the player component so that it doesn't grow into a square on wider viewports.

2022-10-05 06:49 UTC, kdembler requested changes

2022-10-05 06:49 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/VideoView.tsx
> +  const videoIsBlocked = !!(id && filteredVideoIds.includes(id))
This was mentioned in the original issue (https://github.com/Joystream/atlas/issues/3213), this new screen should be shown whenever the video in unavailable, for whatever reason. With your current code this new screen will be shown only if the video ID is blocked, but following cases would be ignored:
- Video is outside of app's category list
- Video was marked as censored by curators
- Video just doesn't exist
This new view should be used in place of `EmptyFallback` used previously

2022-10-05 06:59 UTC, toiletgranny approved these changes

2022-10-05 08:42 UTC, kdembler commented on packages/atlas/src/views/viewer/VideoView/VideoView.tsx
> +  const videoNotAvailable = !!(id && filteredVideoIds.includes(id)) || (!loading && !video)
What's the point of `!!(id && filteredVideoIds.includes(id))`? If the video is blocked, the second clause will still capture that?

2022-10-05 09:08 UTC, kdembler approved these changes

2022-10-05 09:17 UTC, drillprop approved these changes

2022-10-05 09:32 UTC, merged