Better handling of failed uploads
Joystream/atlas pull request #3383
Opened 2022-10-31 16:27 UTC by rafalpawlow

Closes #3130 

**Design**
https://www.figma.com/file/Pe1Y0nrl4mpHWs7AkuQOk5/My-uploads-page?node-id=1133%3A11900

2022-11-02 12:20 UTC, drillprop requested changes
I didn't look at the code, but I see some issues when I was trying to re-upload a cover image file. Everything seems to be fine with a video file. Did you test this as well on images?

So when I re-uploaded the new image in my uploads view I see: 
![image](https://user-images.githubusercontent.com/51168865/199487374-57981e41-db30-4ec5-8913-c54464b8780e.png)
As you may see, there is no title, and when I click "Try again" I'm getting an error

In addition to the above, when I go to "My videos" I see two tiles with information about broken assets: 
![image](https://user-images.githubusercontent.com/51168865/199487724-0b9f741b-1308-4de0-8f7c-3c0bf73da381.png)
Again, one doesn't have a title and it shouldn't be here. We should have only one with the name `sdsdsa`

2022-11-02 13:31 UTC, kdembler commented
@rafalpawlow @drillprop Since I won't be available till Monday, let's make @drillprop the primary reviewer here. However, I will want to take a look on Monday before we merge as well

2022-11-04 09:00 UTC, drillprop requested changes
I see some layout shift, when there are two files in the upload status.  
![image](https://user-images.githubusercontent.com/51168865/199933290-a27d2a57-9918-4294-b30d-c1dcb2b3d5c0.png)
Could be caused by the long name, but not sure

2022-11-04 09:00 UTC, drillprop commented on packages/atlas/src/components/_overlays/ImageCropModal/ImageCropModal.tsx
> +  const { fullFee, loading } = useFee(fee?.methodName, fee?.args && showModal ? fee.args : undefined)
I don't like the fact that we're getting fees inside ImageCropModalComponent. Can we just pass the fee to the component via props? Is it possible?  Why do we actually need this here in the first place?

2022-11-04 09:00 UTC, drillprop commented on packages/atlas/src/views/studio/CreateEditChannelView/CreateEditChannelView.hooks.ts
> +type FormMethods = {
I don't like that we need to pass these methods like this. Maybe we could pass some methods like `onUploadAvatar` or `onUploadCover`(maybe you could do something like `onUploadAssets` instead of these two) and then `onTxSync` instead? And all the react-hook-form calls do on the component level? Wdyt?

2022-11-04 09:00 UTC, drillprop commented on packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx
>  export const UploadStatus: FC<UploadStatusProps> = ({ isLast = false, asset, size }) => {
Ok, this file is super hard to read, every function has at least 100 lines and nested ifs. I'm a little worried that this will be very bug-prone, and hard to manage. Is there any room for improvement here? Could we make some effort to clean this up a bit?

2022-11-04 09:00 UTC, drillprop commented on packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx
>          startFileUpload(
What will happen if we pass just `asset` here?

2022-11-04 09:00 UTC, drillprop commented on packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx
> +        name: asset.name,
same here

2022-11-04 09:00 UTC, drillprop commented on packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx
>        startFileUpload(
same here

2022-11-04 09:20 UTC, rafalpawlow commented on packages/atlas/src/components/_overlays/ImageCropModal/ImageCropModal.tsx
> +  const { fullFee, loading } = useFee(fee?.methodName, fee?.args && showModal ? fee.args : undefined)
It's related to this view https://www.figma.com/file/Pe1Y0nrl4mpHWs7AkuQOk5/My-uploads-page?node-id=1115%3A7968

2022-11-07 12:03 UTC, kdembler commented
Just did a quick test of this and after selecting different video file and uploading it, my old video wasn't modified but actually a new empty video was created with the new video file. That's not desired, we should only update the existing videos from my uploads

2022-11-07 12:16 UTC, kdembler commented
Also if my thumbnail upload fails and then I select the same file, I still get the "Different file was selected". Seems the crop isn't automatic for files that we have crop data saved for, so it produces a different image

2022-11-07 21:38 UTC, kdembler commented
Needs rebase and change of target to `dev`

2022-11-14 08:17 UTC, drillprop requested changes
Unfortunately found another issue. 
1. Have two failed assets(thumbnail and video). 
![image](https://user-images.githubusercontent.com/51168865/201608910-a4e4bf31-89aa-4915-8a02-ed449d1f4b6e.png)
2. Click select and select a video
3. Cancel transaction in polkadot
4. Video file disappear from upload status 
![image](https://user-images.githubusercontent.com/51168865/201609202-516642f0-39f2-4693-80d9-6d897e9e266a.png)

2022-11-14 08:34 UTC, drillprop requested changes

2022-11-14 08:34 UTC, drillprop commented on packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.hooks.ts
> +            await cb()
Is this `async/await` redundant here?

2022-11-14 08:34 UTC, drillprop commented on packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.hooks.ts
> +          onClick: async () => {
same here?

2022-11-14 08:34 UTC, drillprop commented on packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.styles.ts
> +  row-gap: ${sizes(1)};
Does this row-gap work here? You removed `display: grid`

2022-11-14 08:41 UTC, drillprop commented
Another unexpected thing happened to me: 
![image](https://user-images.githubusercontent.com/51168865/201613769-03cf29d2-2b3b-4fc6-b533-c0b4fddab814.png)
I was re-uploading the video file for `Sample-5s`, and a new file jumped to another upload group.

2022-11-15 14:34 UTC, drillprop approved these changes
LGTM!

2022-11-15 15:59 UTC, kdembler approved these changes
Seems to work like a charm. Great job @rafalpawlow!

2022-11-15 15:59 UTC, merged