🤑  My payments ➡️ Transactions
Joystream/atlas pull request #3471
Opened 2022-12-01 16:44 UTC by WRadoslaw

fixes #3056 #3055

2022-12-02 09:21 UTC, drillprop requested changes
Works great! Found only a few minor things

2022-12-02 09:21 UTC, drillprop commented on packages/atlas/src/views/studio/MyPaymentsView/PaymentsTransactionTab/PaymentTransactionsTab.styles.ts
> +  margin-bottom: ${sizes(4)};
I just noticed that the margin and the gap are different on `md`. It should be 24px not `16 px`.  I did the same mistake in `Overview tab`. Could you fix it there as well? 
https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments-page?node-id=1505%3A17428&t=gGHo1JzBlZspPmLd-4

2022-12-02 09:21 UTC, drillprop commented on packages/atlas/src/views/studio/MyPaymentsView/PaymentsTransactionTab/PaymentTransactionsTab.tsx
> +            />
As far as I know, we won't be supporting converting joy to USD for some time. The designs are quite old for these views. Let's remove the caption for now.

2022-12-02 09:21 UTC, drillprop commented on packages/atlas/src/views/studio/MyPaymentsView/PaymentsTransactionTab/PaymentTransactionsTab.tsx
> +            />
same here

2022-12-02 09:21 UTC, drillprop commented on packages/atlas/src/views/studio/MyPaymentsView/PaymentsTransactionTab/PaymentTransactionsTab.tsx
> +      <TablePaymentsHistory data={paymentData} />
The same applies to table

2022-12-02 09:21 UTC, drillprop commented on packages/atlas/src/views/studio/MyPaymentsView/PaymentsTransactionTab/utils.ts
> +import BN from 'bn.js'
I would name this file `PaymentTransactionTab.utils.ts`. I know that we still have some files called just `utils`, but we decided one day, that if something is "component specific" we're naming this `ComponentName.utils`. We already have `Comment.utils` or `NftForm.utils`

2022-12-05 07:41 UTC, kdembler commented on packages/atlas/src/components/TablePaymentsHistory/TablePaymentsHistory.tsx
> +export interface PaymentHistory {
We're using `type`s instead of `interface`s

2022-12-05 07:41 UTC, kdembler commented on packages/atlas/src/components/TablePaymentsHistory/TablePaymentsHistory.tsx
> +  return <Table title="History" columns={COLUMNS} data={mappedData} minWidth="750px" />
Why do we need to pass width as a prop?
1. Table should probably just take full width and the rest should be handled by  the layout
2. If point above is not true for some reason, we probably should allow passing `className` to `Table` and just provide this style via styled components

2022-12-05 07:41 UTC, kdembler commented on packages/atlas/src/views/studio/MyPaymentsView/MyPaymentsView.tsx
> +import { PaymentTransactionsTab } from '@/views/studio/MyPaymentsView/PaymentsTransactionTab'
This should be relative import

2022-12-05 07:41 UTC, kdembler commented on packages/atlas/src/views/studio/MyPaymentsView/PaymentsTransactionTab/PaymentTransactionsTab.hooks.ts
> +import { mapEventToPaymentHistoryFactory } from '@/views/studio/MyPaymentsView/PaymentsTransactionTab/PaymentTransactionsTab.utils'
This should be relative import

2022-12-05 08:48 UTC, WRadoslaw commented on packages/atlas/src/components/TablePaymentsHistory/TablePaymentsHistory.tsx
> +  return <Table title="History" columns={COLUMNS} data={mappedData} minWidth="750px" />
Good point, thanks!

2022-12-07 10:03 UTC, drillprop requested changes
Unfortunately, found another issue. 
![image](https://user-images.githubusercontent.com/51168865/206143045-ac380e22-d945-4916-a305-efcb055d7750.png)
These sales were done on a different channel(that belongs to the same member), so those shouldn't be displayed on my channel. 

The problem is, that due to query node limitations, we can't pass channel id to for example `nftBoughtEvents`. Maybe we should get the channel id from the query: 
```
query {
    nftBoughtEvents(where: {ownerMember: {id_eq: $ownerMemberId} }) {
    inBlock
    video {
      channelId
    }
    createdAt
    price
  }
}
```
 and filter this on the client? I don't know, I don't see a clean solution for this.

2022-12-07 10:26 UTC, WRadoslaw commented
> Unfortunately, found another issue. ![image](https://user-images.githubusercontent.com/51168865/206143045-ac380e22-d945-4916-a305-efcb055d7750.png) These sales were done on a different channel(that belongs to the same member), so those shouldn't be displayed on my channel.
> 
> The problem is, that due to query node limitations, we can't pass channel id to for example `nftBoughtEvents`. Maybe we should get the channel id from the query:
> 
> ```
> query {
>     nftBoughtEvents(where: {ownerMember: {id_eq: $ownerMemberId} }) {
>     inBlock
>     video {
>       channelId
>     }
>     createdAt
>     price
>   }
> }
> ```
> 
> and filter this on the client? I don't know, I don't see a clean solution for this.

Nice catch! I don't see another solution either, since Hydra doesn't allow that deeply nested parameter.

2022-12-07 10:48 UTC, WRadoslaw commented
@drillprop Should be good now 🤞

2022-12-07 14:35 UTC, WRadoslaw commented
@drillprop I've reverted the changes as discussed on planning call, so this should be good to go

2022-12-08 08:45 UTC, drillprop approved these changes

2022-12-08 09:27 UTC, drillprop commented
Created #3505 #3504 as followup

2022-12-08 09:27 UTC, merged