🦅  Expose privacy policy to config
Joystream/atlas pull request #3472
Opened 2022-12-01 17:06 UTC by WRadoslaw

partially fixes #3470 

⚠️ Still requires changes on gleev fork ⚠️

2022-12-02 08:10 UTC, drillprop requested changes
Looks good, but after a quick chat on the discord, we decided to add markdown support.

2022-12-05 08:05 UTC, kdembler commented
@WRadoslaw Let's mention this change in `CHANGELOG.md` 🙏

2022-12-05 12:09 UTC, kdembler requested changes
There's still an open question on what we do with markdown styling. I see 2 ways forward:

1. We resolve this in this PR, so make sure that rendered styles are matching the designs
2. We use default styling for now and create a followup issue to update styling later in the future

Since this styling is only about those legal views, it's not the biggest priority. Leaving the choice up to you though

2022-12-05 12:09 UTC, kdembler commented on packages/atlas/src/views/legal/PrivacyPolicy.tsx
> +      <ReactMarkdown>{atlasConfig.legal.privacyPolicy}</ReactMarkdown>
Let's add some wrapper component for `ReactMarkdown` to use within the app

2022-12-05 14:49 UTC, kdembler requested changes

2022-12-05 14:49 UTC, kdembler commented on packages/atlas/src/components/MarkdownPreview/MarkdownPreview.tsx
> +import { MarkdownGlobalStyles } from '@/components/MarkdownPreview/MarkdownPreview.styles'
Let's make this import relative 🙏

2022-12-05 14:49 UTC, kdembler commented on packages/atlas/src/components/MarkdownPreview/MarkdownPreview.tsx
> +      <Global styles={MarkdownGlobalStyles} />
I think we could just do this instead?

```tsx
const StyledReactMarkdown = styled(ReactMarkdown)`
& h1 {
  // ...
}
`
```

This has 2 benefits:
1. We don't need to keep track of `markdown-preview` class name (we could make typo for example), since it will be handled by emotion
2. We don't need to inject global styles

2022-12-05 15:36 UTC, WRadoslaw commented on packages/atlas/src/components/MarkdownPreview/MarkdownPreview.tsx
> +      <Global styles={MarkdownGlobalStyles} />
Unfortunately, `emotion` doesn't accept `ReactMarkdown` in `styled`

2022-12-05 15:39 UTC, WRadoslaw commented on packages/atlas/src/components/MarkdownPreview/MarkdownPreview.tsx
> +      <Global styles={MarkdownGlobalStyles} />
To elaborate it works but requires `@ts-ignore` comment

2022-12-05 21:21 UTC, drillprop reviewed
I did some testing and I think we could use react-markdown in a different way. Instead of creating some global styles, which could be bug-prone, we could make use of react-markdown prop called components: 

```tsx
  <ReactMarkdown
        components={{
          h1: ({ children }) => (
            <Text as="h1" variant="h400" margin={{ bottom: 4 }}>
              {children}
            </Text>
          ),
          p: ({ children }) => {
            return (
              <Text as="p" variant="t300" color="colorText" margin={{ bottom: 4 }}>
                {children}
              </Text>
            )
          },
        }}
      >
        {markdown}
      </ReactMarkdown>
```
The advantage of this approach would be 
- we will always use our predefined `Text` component.
- no need to create global styles
- we could replace the HTML tag of the element(for example h1 to h2, to not have multiple h1 tags on the site)
- in the designs, we're applying different margins based on if the element is last or first in the document.  Check [here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=10059%3A184916&t=AmtBK4WmcUpfoLtL-4). We could actually figure out which tag element is last or first, by reading `index` and `sibilingCount` parameter like this:
```tsx 
  <ReactMarkdown
        includeElementIndex
        components={{
          p: ({ children, siblingCount, index }) => {
            const isLastElement = siblingCount === index + 1
            return (
              <Text as="p" variant="t300" color="colorText" margin={{ bottom: 4 }}>
                {children}
              </Text>
            )
          },
        }}
      >
        {markdown}
      </ReactMarkdown>
```

Wdyt @kdembler @WRadoslaw ? 
I will also be fine if we keep what we have now. We could create an issue and refactor this later. As far as I know, we will need this `Markdown container` later when we start implementing CRT tokens, so we will need to update this anyway.

2022-12-05 21:33 UTC, WRadoslaw commented
I have no preference tbh. It can be styled by emotion to avoid using global styles and margins can be added there as well. About bug prone, I can't think of any danger here (Pioneers markdown is styled by CSS since the beginning and I think there wasn't any problem with it).

2022-12-06 10:15 UTC, kdembler commented
I like @drillprop approach more tbh, let's go with that

2022-12-06 12:15 UTC, kdembler approved these changes
LGTM, wanna take a look as well @drillprop

2022-12-06 12:39 UTC, drillprop approved these changes

2022-12-06 12:40 UTC, drillprop approved these changes
Looks good to me as well, thanks for refactoring this 👍🏻

2022-12-06 12:40 UTC, merged