⏪ Claim reward flow
Joystream/atlas pull request #3476
Opened 2022-12-03 08:01 UTC by WRadoslaw

fixes #3053

2022-12-05 15:28 UTC, drillprop requested changes

2022-12-05 15:28 UTC, drillprop commented on packages/atlas/src/components/_overlays/ClaimChannelPaymentsDialog/ClaimChannelPaymentsDialog.tsx
> +          />
Let's hide information about the price in USD until we support it

2022-12-05 15:28 UTC, drillprop commented on packages/atlas/src/components/_overlays/ClaimChannelPaymentsDialog/ClaimChannelPaymentsDialog.tsx
> +  const { fullFee, loading: feeLoading } = useFee('claimRewardTx', txParams)
I'm pretty sure that fee isn't correctly calculated. When I logged txParams I got `undefined`

2022-12-06 08:57 UTC, drillprop requested changes

2022-12-06 08:57 UTC, drillprop commented on packages/atlas/src/components/_overlays/ClaimChannelPaymentsDialog/ClaimChannelPaymentsDialog.tsx
> +          {formatNumber(channelBalance ? hapiBnToTokenNumber(channelBalance) : 0)} tJOY
Sorry, I missed one thing. This value should be **the member balance**, not **channel balance**. The purpose of displaying that is to make sure, that the user has money to pay the transaction fee. So, let's use here `totalBalance`, ie. `lockedBalance + accountBalance`. 
Like we have here: https://github.com/Joystream/atlas/pull/3454/files#diff-15493a7d81d14bc68ede4728b4b6f1bb65ce118111dc95f7e8fd1c4bace1ff63(we don't have this fix on payments branch, just FYI)

2022-12-06 08:57 UTC, drillprop commented on packages/atlas/src/components/_overlays/ClaimChannelPaymentsDialog/ClaimChannelPaymentsDialog.tsx
> +        <Text variant="t100" as="p" color="colorText" margin={{ top: 1 }}>
We should use here NumberFormat component instead

2022-12-06 08:57 UTC, drillprop commented on packages/atlas/src/components/_overlays/ClaimChannelPaymentsDialog/ClaimChannelPaymentsDialog.tsx
> +          <Text variant={mdMatch ? 'h500' : 'h400'} as="p">
Same as above, I think

2022-12-06 10:13 UTC, WRadoslaw commented
I noticed that there is an error from PR implementing the`useChannelPayout` hook. In `handleTransaction` `cumulativeRewardClaimed` was passed instead of `cumulativeRewardEarned`.

After the fix, the error occurred in OverviewTab, it looks like we have to validate the amount before displaying Claim button (or disable it with a tooltip informing what's going on).

![image](https://user-images.githubusercontent.com/92513933/205882431-30ba5732-30e9-4e66-911b-4d05c65089db.png)

2022-12-07 10:20 UTC, drillprop approved these changes
> I noticed that there is an error from PR implementing the`useChannelPayout` hook. In `handleTransaction` `cumulativeRewardClaimed` was passed instead of `cumulativeRewardEarned`.
> 
> After the fix, the error occurred in OverviewTab, it looks like we have to validate the amount before displaying Claim button (or disable it with a tooltip informing what's going on).
> 
> ![image](https://user-images.githubusercontent.com/92513933/205882431-30ba5732-30e9-4e66-911b-4d05c65089db.png)

I created #3495 to fix this in the future.

Besides that, looks good to me!

2022-12-07 12:45 UTC, merged