🥇 Make ypp widget customable
Joystream/atlas pull request #3521
Opened 2022-12-12 17:13 UTC by WRadoslaw

fixes #3494

2022-12-13 09:32 UTC, kdembler commented
Let's add icon to widget config - just allow one of 3 icons we already have

2022-12-16 09:23 UTC, drillprop requested changes

2022-12-16 09:23 UTC, drillprop commented on packages/atlas/atlas.config.yml
> +      - title: Discord
I think this should be "Support".
https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=1607%3A87168&t=gOOCh3G4LcWCgR2H-4

2022-12-16 09:23 UTC, drillprop commented on packages/atlas/atlas.config.yml
> +        vendor: Discord # Used for YPP Dashboard to inform user which vendor given feature uses - if empty defaults to title
I'm not sure if I understand what's a vendor. Is it a label? This thing? 👇🏻 
![image](https://user-images.githubusercontent.com/51168865/208065764-4123920b-3dad-40dc-8747-906706459cbe.png)
 If yes, can we just rename this to label?

2022-12-19 16:33 UTC, drillprop approved these changes

2022-12-19 16:33 UTC, merged