📃 Payments claim errors
Joystream/atlas pull request #3578
Opened 2022-12-23 14:01 UTC by WRadoslaw

#3495

2022-12-23 14:10 UTC, WRadoslaw commented
@dmtrjsg I need clarification on whether snackbar should be displayed when user tries to claim reward or on claim modal open? RN it's implemented on claim try.

2022-12-28 09:12 UTC, drillprop requested changes
Needs rebase. Payments don't work at all for me in this PR. I'm not sure what change caused that but I'm getting an error in the console: 
![image](https://user-images.githubusercontent.com/51168865/209787854-4873909d-9e25-45b9-9e6a-3c2bcdc94c40.png)

I thought that it was some previous change, but everything seems to be fine on `ypp` branch.

2023-01-02 09:12 UTC, drillprop commented on packages/atlas/src/views/studio/MyPaymentsView/PaymentsOverview/PaymentsOverview.hooks.ts
> +              : `Minimum claimable amount must be more than ${minCashoutAllowed.toString()} ${TOKEN_TICKER}. Accumulate more rewards before claiming again.`
The value is in `hapi` we need to convert this to `joy`. Also, I would use `formatNumber` here: 
`formatNumber(hapiBnToTokenNumber(maxCashoutAllowed))`

2023-01-02 10:35 UTC, drillprop approved these changes

2023-01-02 10:35 UTC, merged