fix: video is not clickable after introducing "add publisher mode to VideoPreview"
Joystream/atlas pull request #361
Opened 2021-03-04 22:45 UTC by nadalfederer

I think it's supposed to be not clickable only on the publisher mode.
![Peek 2021-03-05 01-41](https://user-images.githubusercontent.com/6043510/110040780-60d18200-7d54-11eb-9c9a-35815df065e4.gif)

![Peek 2021-03-05 01-42](https://user-images.githubusercontent.com/6043510/110040782-6202af00-7d54-11eb-9b43-f86da6ac510f.gif)

2021-03-05 10:02 UTC, eldiegod requested changes
Hey great, thanks for fixing the issue, it's just what needed to be done + a tiny suggestion 🏅

2021-03-05 10:02 UTC, eldiegod commented on src/shared/components/VideoPreviewBase/VideoPreviewBase.tsx
> +    if (!href || publisherMode) {
```suggestion
    if (!href || isAnyVideoSelected) {
```

The anchor should still work when in publisher mode, tho we want to prevent it from navigating when any videos are being selected since it enters a "selecting videos" mode, and clicking a video cover means we want to select/deselect it

2021-03-05 13:39 UTC, kdembler commented
There also seems to be some conflict introduced by my latest merge so it will need to get resolved :pray:

2021-03-05 23:27 UTC, nadalfederer commented
This is what I have in the summer branch after the last commit.
![Uploading Screenshot from 2021-03-06 02-26-01.png…]()

2021-03-06 11:31 UTC, kdembler approved these changes

2021-03-06 11:32 UTC, merged

2021-03-06 11:32 UTC, kdembler commented
Great, thanks for you contribution @nadalfederer!