removed payouts dashboard for YPP (#3706)
Joystream/atlas pull request #3716
Opened 2023-02-02 09:28 UTC by attemka

removed payouts dashboard for YPP
closes #3706

2023-02-03 07:26 UTC, drillprop requested changes
Unfortunately, this is not enough. If I switch the environment to atlas-dev, then I connect to the wallet and go to the studio, the app will break.
![image](https://user-images.githubusercontent.com/51168865/216535380-43416cce-f4ff-4300-9f6b-3fa89fb0dd6c.png)

Remember that we want to use the dev environment for testing.

Besides that, we should also change the targetDevEnv inside `packages/atlas/src/providers/environment/store.ts`

2023-02-03 07:26 UTC, drillprop commented on packages/atlas/src/components/_navigation/SidenavStudio/SidenavStudio.tsx
> +      ]),
I don't think we should just hide the payments from the navigation. On gleev we still have payments in navigation, although it's not working - we have a placeholder screen there.
![image](https://user-images.githubusercontent.com/51168865/216537217-ff7d41af-d244-4cb2-be4e-1041b51381c6.png)

Removing the payments nav item together with the placeholder screen could suggest to the users that we abandoned the payments feature when we release YPP.

2023-02-03 09:20 UTC, dmtrjsg commented
+ there's one event that is taken from Ephesus and it needs to be removed from Graph QL

2023-02-06 11:04 UTC, drillprop requested changes
Also, let's update the targetDevEnv inside `packages/atlas/src/providers/environment/store.ts` to 'development'. 

This will set the `development` environment as default(currently is `next`)

2023-02-06 11:04 UTC, drillprop commented on packages/atlas/src/components/_navigation/SidenavStudio/SidenavStudio.tsx
> +      ]),
You brought back the placeholder view but didn't bring back the nav item in the sidebar.

2023-02-07 12:43 UTC, drillprop approved these changes
LGTM

2023-02-08 14:00 UTC, merged