🦩 Clear button overflow fix
Joystream/atlas pull request #3866
Opened 2023-02-17 14:04 UTC by WRadoslaw

#3788

2023-02-20 08:00 UTC, drillprop requested changes
Actually, this is not how it is supposed to work. Maybe I should be more clear on the issue.
Check the designs:
https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=5%3A35603&t=PgJryRQfBH6iI1Zi-4

When the search bar is opened we shouldn't show the member icon and the notification button on the left. 
This should work exactly the same as it works for unregistered users. 

https://user-images.githubusercontent.com/51168865/220046478-d432e77a-d026-4150-aa4c-cd1dc101a99b.mov

2023-02-21 08:49 UTC, drillprop requested changes
This is almost correct, but still, I see one issue 😅 
Now you're hiding buttons every time independently of screen size. We should hide the buttons only when the size is smaller than `1024 px`. 
On the bigger screens, we should keep them since there is plenty of space for the search input and the buttons and it doesn't make sense to hide the latter.

2023-02-21 10:06 UTC, drillprop approved these changes
![japanology-perfect-gif](https://user-images.githubusercontent.com/51168865/220314027-d0448e9e-3d90-47bd-b8fc-e31a95f2e575.gif)

now it's perfect!

2023-02-21 16:44 UTC, attemka approved these changes

2023-02-21 16:44 UTC, merged