🏳️  Nft carousel
Joystream/atlas pull request #3959
Opened 2023-03-21 14:27 UTC by WRadoslaw

2023-03-21 14:29 UTC, WRadoslaw commented on packages/atlas/src/api/hooks/nfts.ts
> +export const useFeaturedNfts = () => {
This is only a placeholder till orion work is merged

2023-03-21 14:29 UTC, WRadoslaw commented on packages/atlas/src/components/Gallery/Gallery.tsx
>    // TODO: this is the only place in the app that requires refs to buttons. Once we refactor this component, we can remove forwardRef from buttons
Remove

2023-03-21 14:29 UTC, WRadoslaw commented on packages/atlas/src/components/Gallery/Gallery.tsx
> +        {/* eslint-disable-next-line @typescript-eslint/ban-ts-comment */}
Fix

2023-03-21 14:29 UTC, WRadoslaw commented on packages/atlas/src/components/NftCarousel/components/MarketplaceCarouselCard/NftCarouselDetails.tsx
> +                <div>{nftDetails.endsAt?.toLocaleString()}</div>
Implement countdown

2023-03-28 14:22 UTC, attemka requested changes
works well, I've just noticed 2 things:
1. keyboard arrow controls doesn't work anymore. I don't think that many users will use that, but lets enable it if its a quick fix.
2. we need to add the callback in the end of the video playback to switch to the next video. Currently video just ends

2023-03-28 14:22 UTC, attemka commented on packages/atlas/src/components/Carousel/Carousel.tsx
> +  // arrowPosition?: number
lets delete it completely if we'll not going to use it?

2023-04-03 11:34 UTC, attemka approved these changes

2023-04-03 11:35 UTC, merged