🆙 Top selling channels
Joystream/atlas pull request #3984
Opened 2023-03-27 07:49 UTC by WRadoslaw

#3779

2023-03-27 18:31 UTC, attemka requested changes

2023-03-27 18:31 UTC, attemka commented on packages/atlas/src/components/TopSellingChannelsTable/TopSellingChannelsTable.stories.tsx
> +const Template = () => <TopSellingChannelsTable />
its missing the apollo provider to fetch the sender data

2023-04-11 07:47 UTC, attemka approved these changes

2023-05-04 10:40 UTC, drillprop requested changes, later dismissed
Currently, this table is only available in the storybook, which is not very useful. Can we add this to the marketplace view? I don't think anything blocks us currently from actually using the table.

2023-05-08 18:51 UTC, attemka commented on packages/atlas/src/components/TopSellingChannelsTable/TopSellingChannelsTable.tsx
> +                <NumberFormat variant="t200-strong" as="p" value={new BN(data.amount)} margin={{ left: 1 }} />
missing `format="short"` here

2023-05-08 18:52 UTC, attemka commented
LGTM after one minor fix

2023-05-09 07:19 UTC, attemka approved these changes

2023-05-09 07:20 UTC, merged