😺 Make video reactions non-blocking
Joystream/atlas pull request #3995
Opened 2023-03-29 14:02 UTC by WRadoslaw

#3752

2023-03-29 15:21 UTC, attemka approved these changes

2023-03-29 17:04 UTC, drillprop requested changes
We should remove the ongoing transaction modal as well. It should be inside `transaction.hooks.ts` I don't think we need it anymore.

2023-03-30 08:13 UTC, WRadoslaw commented
> We should remove the ongoing transaction modal as well. It should be inside `transaction.hooks.ts` I don't think we need it anymore.

I think it's good to have the user sign action before trying to perform the next one. I guess some people might be confused why nothing is processed with having 3 wallet signing modals open on another monitor or workspace. I know we show the snack bar to proceed in extension, but there is always the possibility that one will somehow miss it.

2023-03-30 09:19 UTC, drillprop approved these changes

2023-03-30 13:04 UTC, merged