🎪 Fix showing all videos in category
Joystream/atlas pull request #4023
Opened 2023-04-03 12:57 UTC by WRadoslaw

#4010 
#4019

2023-04-03 13:06 UTC, drillprop requested changes

2023-04-03 13:06 UTC, drillprop commented on packages/atlas/src/config/contentFilter.ts
>  export const createChannelWhereObjectWithFilters = (
I'd remove this function as well, it's not doing anything actually.

2023-04-03 13:06 UTC, drillprop commented on packages/atlas/src/config/contentFilter.ts
> +    ...(atlasConfig.content.showAllContent
I would also remove `showAllContent` from the config. This option is also configurable in Orion. So I don't think we should keep it

2023-04-03 13:06 UTC, drillprop commented on packages/atlas/src/config/contentFilter.ts
> +    ...(atlasConfig.content.showAllContent
Also, let's remove `createVideoWhereObjectWithFilters` as well.

2023-04-04 10:03 UTC, drillprop approved these changes
Thanks for cleaning this up, looks good to me!

2023-04-04 12:13 UTC, attemka approved these changes

2023-04-04 12:13 UTC, merged