Section component
Joystream/atlas pull request #4038
Opened 2023-04-06 07:57 UTC by drillprop

Fix #3808, #3793

2023-04-07 11:50 UTC, WRadoslaw requested changes
First of all, nice job. That's a lot of details to cover. After the first click through:

1. On stories I cannot deselect checkboxes inside the filter button - not sure if it's just the problem with story implementation or smth in component
![image](https://user-images.githubusercontent.com/92513933/230580085-32670319-32ed-4e13-aa01-cc48cc1abff2.png)

2. On `With title` story (between 800-950px viewport width) toggle button group is useless and doesn't make much sense, maybe we should hide it when search is open and we are below MD and still in one column
![image](https://user-images.githubusercontent.com/92513933/230581314-833fd4b3-fbf1-4b7a-8d4f-cb58c977dff6.png)

2023-04-07 11:50 UTC, WRadoslaw commented on packages/atlas/src/components/FilterButton/FilterButton.tsx
> +        return { ...option, selected: true }
```suggestion
        return { ...option, selected: !option.selected}
```

2023-04-07 11:50 UTC, WRadoslaw commented on packages/atlas/src/components/MobileFilterButton/MobileFilterButton.tsx
> +              return { ...option, selected: true }
Same as in `FilterButton`

2023-04-07 11:50 UTC, WRadoslaw commented on packages/atlas/src/components/MobileFilterButton/index.ts
> +export * from './MobileFilterButton'
Could we add a story for this?

2023-04-07 11:50 UTC, WRadoslaw commented on packages/atlas/src/hooks/useHorizonthalFade.ts
> +        new ResizeObserver(trigger).observe(ref.current)
Shouldn't we cleanup on unmount?

2023-04-12 11:40 UTC, drillprop commented
> First of all, nice job. That's a lot of details to cover. After the first click through:
> 
> 1. On stories I cannot deselect checkboxes inside the filter button - not sure if it's just the problem with story implementation or smth in component
>    ![image](https://user-images.githubusercontent.com/92513933/230580085-32670319-32ed-4e13-aa01-cc48cc1abff2.png)
> 2. On `With title` story (between 800-950px viewport width) toggle button group is useless and doesn't make much sense, maybe we should hide it when search is open and we are below MD and still in one column
>    ![image](https://user-images.githubusercontent.com/92513933/230581314-833fd4b3-fbf1-4b7a-8d4f-cb58c977dff6.png)

fixed

2023-04-13 11:13 UTC, WRadoslaw approved these changes

2023-04-13 11:15 UTC, WRadoslaw requested changes
Just noticed that on checkbox group on the mobile filter behaves as a radio group

2023-04-13 11:34 UTC, drillprop commented
> Just noticed that on checkbox group on the mobile filter behaves as a radio group

fixed as well

2023-04-13 11:40 UTC, WRadoslaw approved these changes

2023-04-14 11:07 UTC, merged