🍼 Google button on YPP
Joystream/atlas pull request #4096
Opened 2023-04-18 14:21 UTC by WRadoslaw

#4088

2023-04-19 12:00 UTC, drillprop requested changes

2023-04-19 12:00 UTC, drillprop commented on package.json
> +  }
why didn't you install it only for the `atlas` package? Why do we need it here?

2023-04-19 12:00 UTC, drillprop commented on packages/atlas/src/assets/google/googleLogo.webp
Like I said in the standup. I think we could use SVG here. You can add it either by yourself in the codebase or ask Kuba to add them to Figma - somewhere here https://www.figma.com/file/1uxugLps6oooI38PGmdrn9/Figma-API--%3E-Storybook?node-id=637-379&t=29guQf48Bguay3R0-4 or in illustrations.

The latter would be better, but I'm fine if you just add this to assets.

2023-04-19 12:00 UTC, drillprop commented on packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx
> +      // onChangeStep('select-channel')
to remove or to keep it?

2023-04-19 12:00 UTC, drillprop commented on packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx
> +            return <Spinner />
why do we use the Spinner now? Previously we had the button with the text `'Please wait...'` and this is what we have in other places in the app, so for the sake of consistency, I would use regular button

2023-04-19 12:00 UTC, drillprop commented on packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationSteps/YppAuthorizationRequirementsStep/YppAuthorizationRequirementsStep.tsx
> +      <Banner description="Gleev uses Google OAuth to get access to your public profile and account email address as part of sign up flow, and integrates with YouTube API to obtain details about your
we should use here appName

2023-04-19 17:35 UTC, WRadoslaw commented on packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx
> +            return <Spinner />
The problem is that we used to display "please wait", cause only the text changed back then. Imho using button as a loading state when in the end button can be switched to Google one is weird. I would go either with a spinner, skeleton or disabled textbutton

2023-04-21 08:06 UTC, drillprop requested changes, later dismissed

2023-04-21 08:06 UTC, drillprop commented on packages/atlas/src/components/_buttons/GoogleButton/GoogleButton.tsx
> +    <Container as="button" {...rest}>
This is a button, we don't need `as` here
```suggestion
    <Container {...rest}>
```

2023-04-21 08:06 UTC, drillprop commented on packages/atlas/src/components/_buttons/GoogleButton/GoogleButton.tsx
> +const Container = styled.button`
I would name this StyledGoogleButton or something similar with a name that contains the word `button`. It's not a container

2023-04-21 08:06 UTC, drillprop commented on packages/atlas/src/components/_buttons/GoogleButton/GoogleButton.tsx
> +  font-family: Roboto, arial, sans-serif;
We don't have available Roboto font in the app, so the rendered font will be Arial: 
![image](https://user-images.githubusercontent.com/51168865/233578461-a53df36d-61eb-416e-8627-6d93f5b76479.png)
I'm a little worried that Google team could not accept this

2023-04-21 10:29 UTC, attemka approved these changes

2023-04-21 13:51 UTC, merged