🚡 Fetching notifications
Joystream/atlas pull request #4123
Opened 2023-04-25 12:53 UTC by WRadoslaw

#3914

2023-04-26 10:00 UTC, drillprop requested changes
There are issues with the mobile view. You told us in the call, that you're aware of them,  but not sure if you know about all of them, so I list them here: 
1. Notifications view - horizontal scrollbar
![image](https://user-images.githubusercontent.com/51168865/234541408-ae52663c-d56b-405a-83a9-f87c8b833b56.png)
2. Widget: 
![image](https://user-images.githubusercontent.com/51168865/234541681-6c072069-baa3-466d-a782-6b2b81ff3c79.png)

2023-04-26 10:00 UTC, drillprop commented on packages/atlas/src/api/hooks/notifications.ts
> -    fetchPolicy: 'no-cache',
huh, so it's working? What did you change to make this possible? Is this because you change the query to the connection one?  if this actually working remove the comment above `fetchPolicy`

2023-04-26 10:00 UTC, drillprop commented on packages/atlas/src/api/queries/notifications.graphql
> +        # CHANGE: The actual `event` is now nested as a property of `Notification`
let's maybe don't copy these comments anymore

2023-04-26 10:00 UTC, drillprop commented on packages/atlas/src/api/queries/notifications.graphql
> +          timestamp # CHANGE: `timestamp` now used instead of `createdAt` (which is no longer available)
same as above

2023-04-26 10:00 UTC, drillprop commented on packages/atlas/src/components/_notifications/NotificationsWidget/NotificationsWidget.tsx
> +                        <StyledCompactNotificationLoader key={idx} />
These skeletons look pretty bad IMO it's just a gray shiny block with awkward gaps. It doesn't resemble single notification at all. I would either:
- create a more complex skeleton loader with a placeholder for the avatar and every line in the notification
- not add them at all

2023-04-26 10:00 UTC, drillprop commented on packages/atlas/src/providers/user/user.helpers.ts
> +      ])
uhm? To remove?

2023-04-26 10:02 UTC, drillprop commented
also, you'll need to resolve conflicts because I merged https://github.com/Joystream/atlas/pull/4095

2023-04-26 13:35 UTC, WRadoslaw commented
Seems like notifications are broken on Gleev as well 
![image](https://user-images.githubusercontent.com/92513933/234592594-c0879f05-774b-4846-a970-a54b6409c671.png)

2023-04-27 11:11 UTC, drillprop requested changes
There is still an issue with notifications on mobile view:

https://user-images.githubusercontent.com/51168865/234845058-2b9ac6e8-f2cf-4478-b26f-51378a964d8b.mov

I can't scroll inside of the widget.

2023-04-28 11:35 UTC, drillprop approved these changes
Just a small suggestion, you need to resolve conflicts as well. 
Besides that looks good! 👍🏻

2023-04-28 11:35 UTC, drillprop commented on packages/atlas/src/components/_notifications/NotificationsWidget/NotificationsWidget.tsx
> +      {!smMatch && isOpen && <MobileBackdrop onClick={() => handleHide()} />}
```suggestion
      {!smMatch && isOpen && <MobileBackdrop  />}
```
Worth to double check this, but I'm pretty sure that we don't need this onClick handler. Popover should handle this

2023-05-09 08:04 UTC, merged