Sign up flow
Joystream/atlas pull request #4210
Opened 2023-05-18 13:16 UTC by drillprop

Fix #4134

2023-05-26 13:18 UTC, WRadoslaw requested changes
1. Should we show password on input focus when it's hidden?

![image](https://github.com/Joystream/atlas/assets/92513933/e4bc8d31-d7ff-482c-a9d6-697f333cbc8f)

2. In designs, password screen don't have scrollbar and divider

![image](https://github.com/Joystream/atlas/assets/92513933/34100504-7f41-4346-a31e-fe0b1222cc54)

3. Not sure why I cannot create a membership (request to the faucet is not triggered)

![image](https://github.com/Joystream/atlas/assets/92513933/41e9ebbb-bb40-4181-b9ad-e119710a10d2)

2023-05-26 13:18 UTC, WRadoslaw commented on packages/atlas/src/components/_overlays/Modal/Modal.styles.ts
> +  /* overflow: hidden; */
Comment

2023-05-26 13:27 UTC, drillprop commented
> 2. In designs, password screen don't have scrollbar and divider

I don't think that's true. https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2939-77080&t=AcDsClQRTl3N7XH9-4

Check the instructions for RWD 
![image](https://github.com/Joystream/atlas/assets/51168865/da21950e-673e-4bd5-a38c-e265604df2ba)

2023-05-26 13:58 UTC, WRadoslaw commented
> > 2. In designs, password screen don't have scrollbar and divider
> 
> I don't think that's true. https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2939-77080&t=AcDsClQRTl3N7XH9-4
> 
> Check the instructions for RWD ![image](https://user-images.githubusercontent.com/51168865/241231029-da21950e-673e-4bd5-a38c-e265604df2ba.png)

If so I'd add some spacing on the bottom, rn it looks kind of awkward.

![image](https://github.com/Joystream/atlas/assets/92513933/ff67160e-97c0-4a64-848c-c9a3acb070e3)

2023-05-29 07:27 UTC, drillprop commented
> 3. Not sure why I cannot create a membership (request to the faucet is not triggered)

For some reason, it's happening only on production. Investigating...

2023-05-29 09:03 UTC, drillprop commented
> > 3. Not sure why I cannot create a membership (request to the faucet is not triggered)
> 
> For some reason, it's happening only on production. Investigating...
 
Fixed. I also introduced some adjustments in your Login Modal because I spotted some styling inconsistencies

2023-05-29 15:49 UTC, WRadoslaw approved these changes

2023-05-31 14:30 UTC, merged