🍡 Marketplace style fixes v2
Joystream/atlas pull request #4215
Opened 2023-05-19 13:14 UTC by WRadoslaw

2023-05-19 13:43 UTC, drillprop commented on packages/atlas/src/components/_video/BackgroundVideoPlayer/BackgroundVideoPlayer.styles.ts
Did you apply the shadow to the buttons? Point 3. I don't see it in dev Chrome.

2023-05-19 14:11 UTC, attemka commented
@WRadoslaw 
<img width="107" alt="image" src="https://github.com/Joystream/atlas/assets/13239251/e73a92e5-e38d-41c0-bde0-d8b33e734085">

please check the hovers of the avatars

2023-05-19 14:13 UTC, drillprop requested changes
Found another issue. One of the icons has a different size for some reason
![image](https://github.com/Joystream/atlas/assets/51168865/ea478b96-0ea8-4fcb-8d74-5ef0fa1f7cf8)

2023-05-19 14:29 UTC, drillprop approved these changes
only this small thing left, besides that looks good to me

2023-05-19 14:29 UTC, drillprop commented on packages/atlas/src/components/_video/BackgroundVideoPlayer/BackgroundVideoPlayer.styles.ts
> +  filter: ${cVar('filterEffectElevation1Layer1')};
filter needs to be applied on the svgs, not on the wrapper of the buttons

2023-05-19 14:37 UTC, attemka requested changes

2023-05-19 14:37 UTC, attemka commented on packages/atlas/src/components/NftCarousel/components/MarketplaceCarouselCard/NftCarouselDetails.tsx
> +              <AvatarGroup spreadAvatars avatarStrokeColor="transparent" avatars={avatars} />
see screenshot above

2023-05-22 19:53 UTC, attemka commented
@WRadoslaw final notes from @KubaMikolajczyk:
> The minor thing - in the timer on hero slider where auction ends in - the colons (:) between hour and minutes and between minutes and seconds should be in color text/default/default - not strong - look at the designs here: https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=464-152611&t=PwKLXqy2LOhqvyRU-4

2023-05-23 07:43 UTC, attemka approved these changes

2023-05-23 07:43 UTC, merged