🥊 Glue auth components
Joystream/atlas pull request #4282
Opened 2023-06-05 12:26 UTC by WRadoslaw

#4263

2023-06-06 07:59 UTC, drillprop requested changes
Amazing work with gluing this together. I managed to create a channel and post a video without using any extension 🤯 . Some things that I found when I was testing this:

1. I already told you about this on discord, but I'll post this here as well. Deployment preview is not working because we're getting error from polkadot
![image](https://github.com/Joystream/atlas/assets/51168865/7e14a56e-ed0f-4982-8c3e-b75243e51cb9)

2. I think I broke this, but there are dividers in a few modal, and they shouldn't be here
![image](https://github.com/Joystream/atlas/assets/51168865/1b563118-ce98-4f6d-86fc-c0f02e7ee464)
![image](https://github.com/Joystream/atlas/assets/51168865/b45545e3-5547-4746-bd9e-40f3d32501e8)

3. I didn't go any errors when I used email that is already used in this step: 
![image](https://github.com/Joystream/atlas/assets/51168865/3d797395-8f99-47d2-b176-f3489d355b8d)
4. I don't think we should show the error-type snackbar. 
![image](https://github.com/Joystream/atlas/assets/51168865/b359ea33-e26c-4528-aa98-e409cad86870)
Please check what we have currently: 
![image](https://github.com/Joystream/atlas/assets/51168865/2574c584-7fe7-4456-b81d-121912c298dc)

5. Once I created a video without extension and transaction modal disappeared I didn't have a new video in my videos. It seems that we didn't refetch user videos.

6. I'm experiencing multiple redirects when I refresh the studio(signed user with extension)

https://github.com/Joystream/atlas/assets/51168865/dadd4e79-2669-43d0-a9a8-98bbc2261cce


7. Once you switch the channel to a member there is a weird gap in the member dropdown

![image](https://github.com/Joystream/atlas/assets/51168865/6a0e04db-7995-49ee-853b-95bb87e10ede)

**EDIT** - Actually I can't reproduce this anymore, so possibly this can be ignored.

8. Once I signed up I wasn't automatically logged in. 


I'm fine if we do these fixes in follow-up PRs, please create issues on GH if you feel that we should tackle these separately.

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/providers/auth/auth.store.ts
> +  authModalOpen?: AuthModals
Possibly I'm exaggerating here, but I would rename this to something different. The name `authModalOpen` suggests that this is a boolean, not a literal type. It could be confusing to use.

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/components/_auth/AuthModals/AuthModals.tsx
> +  }
Because of this switch statement once you close the modal there is no ending transition animation. The modal closes immediately.

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/components/_auth/ExternalSignInModal/ExternalSignInModal.tsx
> +          <ExternalSignInModalStepTemplate
Correct me if I'm wrong, but `ExternalSignInModalStepTemplate` is the same component as `AuthenticationModalStepTemplate`, can we use one and get rid of the other one?

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/VideoView.tsx
> +                  text={`${formatDate(new Date(video.createdAt))} at ${format(new Date(video.createdAt), 'HH:mm')}`}
why do we need this change? I'm pretty sure that date is formatted correctly in video view.

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/VideoView.tsx
> +                  {formatDate(new Date(video.createdAt))}
same as above

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/views/studio/CreateEditChannelView/CreateEditChannelView.hooks.ts
> +    // eslint-disable-next-line no-sparse-arrays
We don't break the rule here, do we? Should we remove this ignore?

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/providers/auth/auth.provider.tsx
> +      setEncodedSeed(null)
should we await the refetch? Did you do this deliberately? I mean, did you want to set the current user and seed to null regardless?

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/providers/auth/auth.provider.tsx
> +        } catch (_) {
```suggestion
        } catch {
```
As far as I remember you can omit parentheses.

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/providers/auth/auth.provider.tsx
> +          }
Are you sure that this will always throw `SignatureCancelled` error?

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/providers/auth/auth.provider.tsx
> +// import { ViewErrorFallback } from '@/components/ViewErrorFallback'
to remove?

2023-06-06 07:59 UTC, drillprop commented on packages/atlas/src/components/_overlays/MemberDropdown/MemberDropdownNav.tsx
> +                    onClick: onCloseDropdown ?? (() => undefined),
```suggestion
                    onClick: onCloseDropdown,
```
redundant?

2023-06-06 10:33 UTC, WRadoslaw commented on packages/atlas/src/views/viewer/VideoView/VideoView.tsx
> +                  text={`${formatDate(new Date(video.createdAt))} at ${format(new Date(video.createdAt), 'HH:mm')}`}
Not sure why, but sometimes on VideoView, on initial load date is returned as a string instead of the date

2023-06-06 10:38 UTC, drillprop commented on packages/atlas/src/views/viewer/VideoView/VideoView.tsx
> +                  text={`${formatDate(new Date(video.createdAt))} at ${format(new Date(video.createdAt), 'HH:mm')}`}
We're transforming it to the desired format in the cache.tsx(`createDateHandler`). So it should work, but I'm fine with your changes, if you found some edge cases.

2023-06-06 11:02 UTC, WRadoslaw commented on packages/atlas/src/views/studio/CreateEditChannelView/CreateEditChannelView.hooks.ts
> +    // eslint-disable-next-line no-sparse-arrays
Not sure :D Looks like IDE added it by itself

2023-06-07 09:24 UTC, drillprop requested changes
There is another issue. If someone doesn't have a wallet installed he'll see this: 
![image](https://github.com/Joystream/atlas/assets/51168865/fa54fc3d-e866-4b9e-b802-c8952ba9a8a3)

2023-06-07 10:19 UTC, drillprop requested changes
Few bugs:
- If a user provides an email that already exists, and then corrects the email and signs up again, he won’t be logged in automatically after signing up a second time


- found another redirecting bug. Steps to reproduce:
1. log into your account using your wallet. The account needs to have a channel
2. Go to the studio
3. Logout
4. Click login CTA 
5. Use a different account that doesn’t have a channel
6. The app is constantly redirecting from studio to sign-in, and I’m ending up in an infinite loop of redirecting 

I think we don’t clear the channelId from local storage after logging out. This could be a reason

- You forgot to add a handler to this button 
![image](https://github.com/Joystream/atlas/assets/51168865/85bcd162-e987-41a5-8751-c2cc906f72a4)

2023-06-07 13:12 UTC, drillprop approved these changes
Looks good to me, nice 🎉 !

2023-06-09 14:27 UTC, merged