Simplified ypp sign up
Joystream/atlas pull request #4351
Opened 2023-06-23 14:07 UTC by drillprop

Fix #4283

2023-06-28 11:53 UTC, attemka requested changes

2023-06-28 11:53 UTC, attemka commented on packages/atlas/src/.env
> -VITE_GOOGLE_CONSOLE_CLIENT_ID=
missed values could be inserted as `null` or `undefined`, which can break our ternary logic

2023-06-28 11:53 UTC, attemka commented on packages/atlas/src/hooks/useUniqueMemberHandle.ts
> +function removeSpecialCharacters(input: string): string {
my suggestion will be to have this as a util func in some utils file and rewrite it as `export const` just to maintain the  codestyle

2023-06-28 11:53 UTC, attemka commented on packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx
> +            'Please wait while the server is processing the request. It may take up to 15 seconds on slow a slow network.',
```suggestion
            'Please wait while the server is processing the request. It may take up to 15 seconds on a slow network.',
```

2023-06-28 12:37 UTC, WRadoslaw requested changes
1. There is a sign in button on first step, but after logging in first nothing happens (i'd expect flow to continue), second after reopening the modal I have only option to `Create account`
![image](https://github.com/Joystream/atlas/assets/92513933/493f4f29-452b-4c44-a20d-27eb8d7b0dcf)

2.  Why do I see a seed after I've logged in on already created account?
![image](https://github.com/Joystream/atlas/assets/92513933/c7fb24e7-5653-480a-b3a5-56535efbb575)
3. After flow continuation I received an error on final submit
![image](https://github.com/Joystream/atlas/assets/92513933/2bbe5d6f-f426-4920-bc58-07926755411f)

2023-06-28 12:37 UTC, WRadoslaw commented on packages/atlas/src/hooks/useUniqueMemberHandle.ts
> +          attempt === 1 ? `${sanitizedHandle}${attempt}` : `${sanitizedHandle.slice(0, lastDigitIndex)}${attempt}`
```suggestion
          attempt === 1 ? `${sanitizedHandle}${attempt}` : `${sanitizedHandle.slice(-1)}${attempt}`
```
And lastDigitIndex can be deleted

2023-06-28 12:37 UTC, WRadoslaw commented on packages/atlas/src/providers/ypp/ypp.types.ts
> +export type YppModal =
Isn't this more like `YppModalStep`?

2023-06-28 12:37 UTC, WRadoslaw commented on packages/atlas/src/utils/image.ts
> +            resolve(blob)
Should we clean up `img` after resolving/rejecting?

2023-06-28 12:37 UTC, WRadoslaw commented on packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/useYppGoogleAuth.tsx
> +  const { ytStateParam: oldYppAuthState, selectedChannelId } = useYppStore((state) => state)
Cant, we add here variables from the line `46`?

2023-06-28 12:37 UTC, WRadoslaw commented on packages/atlas/src/views/global/YppLandingView/useGetYppLastVerifiedChannels.ts
> +  const getRecentChannels = useCallback(async (): Promise<string[] | void> => {
I believe we can just extract this above the hook

2023-06-28 12:58 UTC, drillprop commented on packages/atlas/src/.env
> -VITE_GOOGLE_CONSOLE_CLIENT_ID=
I think I didn't get that. They are not missed, they are below, we doubled them in `.env` file. Check variables below `# YPP configuration`
![image](https://github.com/Joystream/atlas/assets/51168865/95b50774-0778-41f3-85f1-d66bf74de498)

2023-06-29 11:37 UTC, drillprop commented
> 1. There is a sign in button on first step, but after logging in first nothing happens (i'd expect flow to continue), second after reopening the modal I have only option to `Create account`

> 2. Why do I see a seed after I've logged in on already created account?

> 3. After flow continuation I received an error on final submit


all the issues should be fixed

2023-06-29 16:42 UTC, attemka approved these changes

2023-06-29 16:55 UTC, WRadoslaw approved these changes

2023-06-30 13:05 UTC, merged