Update meta-server user agent rule
Joystream/atlas pull request #4357
Opened 2023-06-24 13:25 UTC by traumschule

based on https://github.com/Joystream/atlas/blob/master/packages/atlas-proxy-worker/src/handler.ts#L2C4-L2C222

2023-06-26 17:16 UTC, attemka commented
@traumschule thx for the PR. please target the `dev` env at first in such PRs so it can be released properly.

2023-06-27 08:45 UTC, dmtrjsg commented
@traumschule please kindly add some description in terms of context and desired outcome to the PRs in the future otherwise it makes it harder to prioritise and execute in the duly manner. 

Thank you in advance.

2023-06-28 11:53 UTC, attemka requested changes
see above

2023-06-29 16:38 UTC, attemka approved these changes

2023-06-29 16:38 UTC, merged