NFT minting rework
Joystream/atlas pull request #4403
Opened 2023-07-07 13:32 UTC by WRadoslaw

#4102

2023-07-10 10:03 UTC, attemka requested changes

2023-07-10 10:03 UTC, attemka commented on packages/atlas/src/components/_overlays/MintNftFirstTimeModal/MintNftFirstTimeModal.tsx
> +          You can mint your videos and sell them on the market for JOY. To do that select mint NFT option in context
```suggestion
          You can mint your videos and sell them on the market for ${atlasConfig.joystream.tokenTicker}. To do that select mint NFT option in context
```

2023-07-10 10:03 UTC, attemka commented on packages/atlas/src/components/_overlays/MintNftModal/MintNftModal.tsx
> +    defaultValues: { ...tabData, mintNft: true } ?? undefined,
can't see the option when this object will have falsy value

2023-07-10 10:03 UTC, attemka commented on packages/atlas/src/hooks/useVideoForm.ts
> +        ...((isNew || dirtyFields.isExplicit) && data.isExplicit != null ? { isExplicit: data.isExplicit } : {}),
packages/atlas/src/providers/videoWorkspace/types.ts:46
 ` isExplicit: boolean`
so it wont be null

2023-07-10 10:03 UTC, attemka commented on packages/atlas/src/hooks/useVideoForm.ts
> +        ...((isNew || dirtyFields.language) && data.language != null ? { language: data.language } : {}),
> data.language != null

why not "!==" ? why would we need a type conversion here if language: string | null?

2023-07-10 10:03 UTC, attemka commented on packages/atlas/src/hooks/useVideoForm.ts
> +        data.publishedBeforeJoystream != null &&
same as above

2023-07-10 10:03 UTC, attemka commented on packages/atlas/src/hooks/useVideoForm.ts
> +  // console.log('fee', updateVideoFee, updateVideoFeeLoading, isSigned && isEdit && id)
log

2023-07-10 10:03 UTC, attemka commented on packages/atlas/src/views/studio/MyVideosView/MyVideosView.tsx
> +            subtitle="No videos uploaded yet. Start publishing by adding your first video to Joystream."
@dmtrjsg should it be "Joystream" or the app name here?

2023-07-10 15:59 UTC, thesan reviewed
It took me a while to get around this PR but it does demonstrate a lot of "the Atlas way". I'll probably go back to it later for reference. However I don't have enough context to make any valuable observation.

2023-07-11 05:04 UTC, WRadoslaw commented on packages/atlas/src/components/_overlays/MintNftModal/MintNftModal.tsx
> +    defaultValues: { ...tabData, mintNft: true } ?? undefined,
I don't understand the question/assumption. Do you mean that `tabData` will always have `mintNft` on true?

2023-07-11 07:36 UTC, attemka commented on packages/atlas/src/components/_overlays/MintNftModal/MintNftModal.tsx
> +    defaultValues: { ...tabData, mintNft: true } ?? undefined,
I mean, it wont go at null coalescing's second part as the object will always contain at least `mintNft: true`

2023-07-13 11:01 UTC, attemka approved these changes

2023-07-13 11:01 UTC, merged