Improve media queries restrictions and enhance usage developer comfort
Joystream/atlas pull request #443
Opened 2021-04-11 17:07 UTC by kosorz

I would like to suggest using the following approach with media queries.

Using this approach helps to preserve consistency across the codebase since it's necessary to introduce some minor changes to the media setup to start using a new breakpoint additionally all breakpoints are 'min' ones therefore app styling integrity is less prone to human error.

Also, it's generally easier to style using such queries since it's more concise and requires less effort to achieve the same goal.

2021-04-11 19:22 UTC, kosorz commented
I've just spotted an emotion specific problem: 
![image](https://user-images.githubusercontent.com/32495390/114318143-f27a9f00-9b0b-11eb-8f37-cc274110b03a.png)
I'll try to resolve it soon!

2021-04-12 09:02 UTC, kdembler requested changes
Hey, thanks for this contribution!

We've discussed this approach internally with the team and we found it problematic to work with. The reason for that is the tooling will not really understand what's going on with this custom `media` function. We tested both VSCode and WebStorm and they both don't understand that CSS is supposed to go inside it and they will not offer any code assistance. Same with Prettier - it will not properly parse and format the CSS enclosed in `media`.

For this reason, we will not be accepting the PR in its current form. However, I believe your general idea of reducing possibility of a human error is a good one. I suggest a different, similar approach. We could have pre-defined string for full media query condition. For example, `media.small` would be `"@media screen and (min-width: ${breakpoints.small})"` and would be used like this:
```js
${media.small} {
  color: red;
}
```

Let me know what you think about that

---

One general point I also want to make is that we're happy you're interested in helping out with the codebase and we will gladly accept any contributions. However, what I'd suggest going forward - if you want to make an app-wide change like this, it will be a good idea to first create an issue describing the problem and the solution you have in mind. This way, we all have a chance to discuss things before getting to work. This will surely reduce a chance of any work going to waste.

Thanks

2021-04-12 17:49 UTC, kosorz commented
Have you seen [this](https://spectrum.chat/emotion/general/functions-that-are-interpolated-tagged-template-literal-question~7818175a-e88c-4308-a51a-19547fa09523)?

If you would google the error I was receiving you would end up at this spectrum chat.

This approach will allow the tooling to process the code and resolve the errors thrown.

- - -

Actually, I will have to create at least one issue then. 
:)

2021-04-13 06:37 UTC, kdembler requested changes
Looks mostly good, found some unnecessary changes though

2021-04-13 06:37 UTC, kdembler commented on src/components/Dialogs/BaseDialog/BaseDialog.style.ts
> +  }
Let's move this back up, next to the other var declaration

2021-04-13 06:37 UTC, kdembler commented on src/components/Sidenav/SidenavBase.style.ts
> +      transition: transform ${transitions.timings.regular} ${transitions.easing}
Missing semicolons

2021-04-13 06:37 UTC, kdembler commented on src/components/Sidenav/SidenavBase.style.ts
> +      transform: translateY(${({ expanded }: { expanded?: boolean }) => (expanded ? 0 : -8)}px)
Types of props are already provided in the component definition `styled.li<ExpandableElementProps>`. We don't need to provide them explicitly here

2021-04-13 06:37 UTC, kdembler commented on src/components/Sidenav/SidenavBase.style.ts
> +      transform: translateY(${({ expanded }: { expanded?: boolean }) => (expanded ? 0 : -8)}px);
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/components/Sidenav/SidenavBase.style.ts
> +      content: ${({ content }: { content: string }) => `'${content}'`};
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/components/Sidenav/SidenavBase.style.ts
> +      opacity: ${({ expanded }: { expanded?: boolean }) => (expanded ? 0 : 1)};
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/components/Topbar/TopbarBase.style.tsx
> +    display: ${({ variant }: { variant?: string }) => (variant === 'default' ? 'block' : 'flex')};
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/shared/components/ActionBar/ActionBar.style.ts
> +  transform: translateY(${({ isActive }: { isActive?: boolean }) => (isActive ? '0' : '100%')});
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/shared/components/ChannelCover/ChannelCover.style.ts
> +      url(${({ src }: { src: string }) => src});
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/shared/components/ChannelCover/ChannelCover.style.ts
> +      url(${({ src }: { src: string }) => src});
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/shared/components/ChannelCover/ChannelCover.style.ts
> +      url(${({ src }: { src: string }) => src});
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/shared/components/ChannelCover/ChannelCover.style.ts
> +      url(${({ src }: { src: string }) => src});
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/shared/components/ChannelCover/ChannelCover.style.ts
> +      url(${({ src }: { src: string }) => src});
Unnecessary prop type

2021-04-13 06:37 UTC, kdembler commented on src/shared/components/HeaderTextField/HeaderTextField.style.tsx
> +  }
Let's move those back up

2021-04-13 06:37 UTC, kdembler commented on src/shared/components/VideoPlayer/VideoPlayer.tsx
> -    if (playing != null) {
Changes here are out of scope of this PR, feel free to open a new one with some rationale

2021-04-13 06:37 UTC, kdembler commented on src/components/Dialogs/BaseDialog/BaseDialog.style.ts
> +  ${media.smedium} {
Let's just use regular `medium` here and drop the `smedium` breakpoint

2021-04-14 07:25 UTC, kdembler approved these changes
Looks good, thanks!

Will need a rebase before merging though

2021-04-14 16:51 UTC, kosorz commented
I think it's ready to merge.
No more actions will be made on my end towards merging this PR.

---

Have a nice day! :)

2021-04-14 17:20 UTC, merged

2021-04-14 17:20 UTC, kdembler commented
Merged, thanks!