📇 UI work on notifications
Joystream/atlas pull request #4434
Opened 2023-07-13 15:13 UTC by WRadoslaw

#4407 
#4408 
#4413

2023-07-14 10:15 UTC, attemka requested changes

2023-07-14 10:15 UTC, attemka commented on packages/atlas/src/components/_navigation/TopbarStudio/TopbarStudio.tsx
> +  const unseedMemberNotifications = 1
is it a typo?

2023-07-14 10:15 UTC, attemka commented on packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.tsx
> +            <NotifactionIcon avatarUrls={avatarUrls ?? []} iconType={getNotificationIcon(notification)} />
```suggestion
            <NotificationIcon avatarUrls={avatarUrls ?? []} iconType={getNotificationIcon(notification)} />
```

2023-07-14 10:15 UTC, attemka commented on packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.tsx
> +            <NotifactionIcon avatarUrls={avatarUrls ?? []} iconType={getNotificationIcon(notification)} />
note that it's passing  `[]` as a fallback option, which **might** brake the logic of the `Avatar component` and it's ternaries

2023-07-14 10:15 UTC, attemka commented on packages/atlas/src/components/_notifications/NotificationsViewContent/NotificationsViewContent.tsx
> +
extra line

2023-07-14 10:15 UTC, attemka commented on packages/atlas/src/components/_notifications/NotificationsWidget/NotificationsWidget.tsx
> +                        {notifications.map((notification, idx) => (
probably needs a fallback similar to `NotificationsViewContent.tsx` for the notification with no id?

2023-07-17 11:47 UTC, WRadoslaw commented on packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.tsx
> +            <NotifactionIcon avatarUrls={avatarUrls ?? []} iconType={getNotificationIcon(notification)} />
It shouldn't

2023-07-19 08:45 UTC, attemka requested changes

2023-07-19 08:45 UTC, attemka commented on packages/atlas/src/components/_navigation/TopbarViewer/TopbarViewer.tsx
> +  const unseedChannelNotifications = 2
typo?

2023-07-19 08:45 UTC, attemka commented on packages/atlas/src/components/_navigation/TopbarViewer/TopbarViewer.tsx
> +                          badge={unseedChannelNotifications}
typo?

2023-07-19 08:45 UTC, attemka commented on packages/atlas/src/components/_navigation/TopbarViewer/TopbarViewer.tsx
> +                          badge={unseedChannelNotifications}
typo?

2023-07-19 08:45 UTC, attemka commented on packages/atlas/src/components/_overlays/MemberDropdown/MemberDropdownNav.tsx
> +  const unseedMemberNotifications = 1
typos?

2023-07-19 08:45 UTC, attemka commented on packages/atlas/src/components/_overlays/MemberDropdown/MemberDropdownNav.tsx
> +          nodeEnd={<Badge data-badge={unseedMemberNotifications} />}
typo?

2023-07-19 08:45 UTC, attemka commented on packages/atlas/src/components/_overlays/MemberDropdown/MemberDropdownNav.tsx
> +            nodeEnd={<Badge data-badge={unseedChannelNotifications} />}
typo?

2023-07-19 08:53 UTC, thesan approved these changes

2023-09-14 08:08 UTC, attemka approved these changes

2023-09-14 08:08 UTC, merged