🌳 CRT progress widget
Joystream/atlas pull request #4569
Opened 2023-08-04 14:12 UTC by WRadoslaw

#3389

2023-08-07 18:04 UTC, attemka requested changes

2023-08-07 18:04 UTC, attemka commented on packages/atlas/src/components/ProgressWidget/ProgressWidget.tsx
> +    <div style={{ position: 'relative' }}>
would look better with a styled

2023-08-07 18:04 UTC, attemka commented on packages/atlas/src/components/ProgressWidget/ProgressWidget.tsx
> +      <Header progressWidth={isVisible ? '0%' : `${Math.round((activeStep / steps.length) * 100)}%`}>
you have a `getProgressPercentage` func

2023-08-07 18:04 UTC, attemka commented on packages/atlas/src/components/ProgressWidget/ProgressWidget.stories.tsx
> +      Complete 1 more step to achive
```suggestion
      Complete 1 more step to achieve{' '}
```

2023-08-07 18:04 UTC, attemka commented on packages/atlas/src/components/ProgressWidget/ProgressWidget.stories.tsx
> +    description: 'Createn own token and share it with your viewers!',
```suggestion
    description: 'Create own token and share it with your viewers!',
```

2023-08-07 18:04 UTC, attemka commented on packages/atlas/src/components/ProgressWidget/ProgressWidget.styles.ts
> +  height: 12px;
I think I've asked before (maybe I've asked Bartosz), but why won't use sizes here and in other hardcoded dimensions?

2023-08-08 09:34 UTC, WRadoslaw commented on packages/atlas/src/components/ProgressWidget/ProgressWidget.styles.ts
> +  height: 12px;
The way it was described to me is that we should use `sizes` for spacing purposes, eg. gaps, paddings, and margins.

2023-08-08 13:58 UTC, attemka approved these changes

2023-08-13 16:53 UTC, merged