🦅 Buy token from market modal
Joystream/atlas pull request #4747
Opened 2023-08-25 07:30 UTC by WRadoslaw

#3834

2023-08-25 14:59 UTC, attemka requested changes

2023-08-25 14:59 UTC, attemka commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/steps/BuyMarketTokenForm.tsx
> +            caption="YOUR JOY BALANCE"
lets use the name from the atlas config

2023-08-25 14:59 UTC, attemka commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/steps/BuyMarketTokenForm.tsx
> +                <TextButton>Max</TextButton>
is it out of scope atm?

2023-08-25 14:59 UTC, attemka commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/steps/BuyMarketTokenForm.tsx
> +            value={tokens}
should we limit max value to the current user's token balance?

2023-08-25 14:59 UTC, attemka commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/steps/BuyMarketTokenForm.tsx
> +          <NumberFormat
will go off if large numbers are used:
<img width="448" alt="image" src="https://github.com/Joystream/atlas/assets/13239251/f19cfd77-31c7-42f9-817e-ce365c356ea1">

2023-08-28 09:06 UTC, WRadoslaw commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/steps/BuyMarketTokenForm.tsx
> +            value={tokens}
this will be handled by validation

2023-08-28 11:35 UTC, attemka requested changes

2023-08-28 11:35 UTC, attemka commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/steps/BuyMarketTokenSuccess.tsx
> +          You are now an {tokenName} holder - you can buy, sell, transfer your token. You can also stake when creator
```suggestion
          You are now an ${tokenName} holder - you can buy, sell, transfer your token. You can also stake when creator
```

confirmed with @KubaMikolajczyk

2023-08-28 13:18 UTC, thesan commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/steps/BuyMarketTokenForm.tsx
> +          />
There are missing tooltips here:
![Screenshot from 2023-08-28 15-08-26](https://github.com/Joystream/atlas/assets/6571453/0b4a8edc-7004-423c-9ccb-fe3b6f01a47d)

2023-08-28 13:18 UTC, thesan commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/steps/BuyMarketTokenForm.tsx
> +const currentJoyRate = 0.15
I think this should be `const { tokenPrice } = useJoystream()` in the component

2023-08-28 13:18 UTC, thesan commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/BuyMarketTokenModal.tsx
> +        <BuyMarketTokenSuccess {...commonProps} onClose={onClose} tokenName="JBC" />
```suggestion
        <BuyMarketTokenSuccess {...commonProps} onClose={onClose} tokenName={`$${title}`} />
```

2023-08-29 15:51 UTC, thesan approved these changes

2023-08-30 09:48 UTC, attemka approved these changes

2023-08-30 09:48 UTC, merged