☎️ Query the new notifications from Orion
Joystream/atlas pull request #4868
Opened 2023-09-14 07:14 UTC by thesan

- #4534

Based on  #4434 and #4453

2023-09-14 16:09 UTC, thesan commented
Missing data AFAIK:

- [ ] comment id on `CommentReply` and `ReactionToComment` for [the link to the comment](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2479-90977&mode=design&t=Db8yUUHekfAjVz17-4) (ATM we just link to the video).
- [ ] followed channel id on `VideoPosted`, `NewNftOnSale`, and `NewAuction` to show [the channel avatar](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2479-91068&mode=design&t=Db8yUUHekfAjVz17-4).
- [ ] The notification for: ["NFT bid becomes withdrawable (for bidder)"](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2479-95719&mode=design&t=Db8yUUHekfAjVz17-4).
- [ ] All member payout notification:  [> Figma](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2479-95899&mode=design&t=Db8yUUHekfAjVz17-4).
- [ ] The member handle on `VideoLiked` and `VideoDisliked` to [show the member avatar](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2474-80802&mode=design&t=Db8yUUHekfAjVz17-4).
- [ ] The notifications for: ["YPP sign up successful" and "Someone signed up using your referral link"](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2474-80560&mode=design&t=Db8yUUHekfAjVz17-4).
- [ ] The notifications for ["Channel received transfer from WG" and "New payout is claimable from Council Payout proposal"](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2475-81077&mode=design&t=Db8yUUHekfAjVz17-4).

2023-09-14 17:34 UTC, ignazio-bovo commented
> Missing data AFAIK:
> 
> * [ ]  comment id on `CommentReply` and `ReactionToComment` for [the link to the comment](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2479-90977&mode=design&t=Db8yUUHekfAjVz17-4) (ATM we just link to the video).
👍 
> * [ ]  followed channel id on `VideoPosted`, `NewNftOnSale`, and `NewAuction` to show [the channel avatar]
(https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2479-91068&mode=design&t=Db8yUUHekfAjVz17-4).
👍 
> * [ ]  The notification for: ["NFT bid becomes withdrawable (for bidder)"](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2479-95719&mode=design&t=Db8yUUHekfAjVz17-4).
very complex to implement as it requires polling, since no events for this are there in the runtime, v2 scope
> * [ ]  All member payout notification:  [> Figma](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2479-95899&mode=design&t=Db8yUUHekfAjVz17-4).
no mappings for this, v2 scope
> * [ ]  The member handle on `VideoLiked` and `VideoDisliked` to [show the member avatar](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2474-80802&mode=design&t=Db8yUUHekfAjVz17-4).
👍 
> * [ ]  The notifications for: ["YPP sign up successful" and "Someone signed up using your referral link"](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2474-80560&mode=design&t=Db8yUUHekfAjVz17-4).
> * [ ]  The notifications for ["Channel received transfer from WG" and "New payout is claimable from Council Payout proposal"](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2475-81077&mode=design&t=Db8yUUHekfAjVz17-4).
No mappings for this, v2 scope

All the notification that are missing are either because of lack of mappings/resolvers or they were too complex for the scope of notifications v1 
https://github.com/Joystream/orion/issues/181

2023-09-25 14:49 UTC, thesan commented
To debug/address here:
- [ ] NFT on Auction and on Sale would need to have expanded widget
- [ ] You lost NFT auction. Add "Withdraw your bid". To the notification text.
- [ ] NFT purchased , NFT royalty payment received : Avatars are blank
- [ ] Channel Avatar not showing

2023-09-28 15:55 UTC, ignazio-bovo commented on packages/atlas/src/api/queries/notifications.graphql
> +            ... on VideoFeaturedOnCategoryPage {
this will be deprecated

2023-09-28 15:56 UTC, dobertRowneySr commented on packages/atlas/src/api/queries/notifications.graphql
> +            ... on VideoFeaturedAsCategoryHero {
this will be deprecated

2023-09-28 15:59 UTC, ignazio-bovo commented on packages/atlas/src/api/queries/notifications.graphql
> +            ... on EnglishAuctionSettled {
I believe we should deprecate this.
The design specifies a notification for timed Auction expired, but technically is not this.
Bidders will be notified in any case when an english (= timed) auction is settled with a `AuctionWon` or `AuctionLost` notification

2023-09-28 16:00 UTC, dobertRowneySr commented on packages/atlas/src/api/queries/notifications.graphql
> +            ... on EnglishAuctionWon {
```suggestion
            ... on AuctionWon {
```

2023-09-28 16:01 UTC, dobertRowneySr commented on packages/atlas/src/api/queries/notifications.graphql
> +            ... on EnglishAuctionLost {
```suggestion
            ... on AuctionLost {
```

2023-09-28 16:01 UTC, ignazio-bovo commented on packages/atlas/src/api/queries/notifications.graphql
> +            ... on OpenAuctionWon {
this will be deprecated

2023-09-28 16:01 UTC, ignazio-bovo commented on packages/atlas/src/api/queries/notifications.graphql
> +            ... on OpenAuctionLost {
this will be deprecated

2023-10-25 10:23 UTC, attemka requested changes
Tremendous work! some minor code stuff. I'll do some e2e and will post here if I'll find smth

2023-10-25 10:23 UTC, attemka commented on packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.hooks.tsx
> +        text: <>New channel created: “{channelTitle}“</>,
probably will crash when google translate plugin will be used. I suggest using some element instead of portal here and below in the code.

2023-10-25 10:23 UTC, attemka commented on packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.hooks.tsx
> +        text: <>Your channel got verified in our Youtube Partnership Program</>,
```suggestion
        text: <>Your channel got verified in our YouTube Partnership Program</>,
```

2023-10-25 10:23 UTC, attemka commented on packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.hooks.tsx
> +        text: <>Your channel got suspended in our Youtube Partnership Program</>,
```suggestion
        text: <>Your channel got suspended in our YouTube Partnership Program</>,
```

2023-10-25 10:23 UTC, attemka commented on packages/atlas/src/components/_overlays/MemberDropdown/MemberDropdownList.tsx
> +          const isSelected = type === 'channel' ? channel.id === channelId : false
`const isSelected = type === 'channel' && channel.id === channelId` will work the same way here?

2023-10-25 11:14 UTC, thesan commented on packages/atlas/src/components/_notifications/NotificationTile/NotificationTile.hooks.tsx
> +        text: <>New channel created: “{channelTitle}“</>,
Nice catch!

2023-10-25 16:09 UTC, attemka approved these changes

2023-11-02 10:35 UTC, merged