🌍 YPP Dashboard 2.0
Joystream/atlas pull request #4929
Opened 2023-09-28 15:02 UTC by WRadoslaw

#4826

2023-10-03 10:04 UTC, attemka requested changes

2023-10-03 10:04 UTC, attemka commented on packages/atlas/src/components/_ypp/YppStatusPill/YppStatusDot.styles.ts
> +// export const Container = styled.div`
remove if not needed

2023-10-03 10:04 UTC, attemka commented on packages/atlas/src/views/studio/MyVideosView/MyVideosView.tsx
> +        show={showMintModal && !!currentChannel?.yppStatus.startsWith('Verified') && !mintConfirmationDismissed}
its either boolean value from `startsWith` or undefined from missing currentChannel, which is also falsy, so why would you need to use the double exclamation mark here?

2023-10-03 10:16 UTC, WRadoslaw commented on packages/atlas/src/views/studio/MyVideosView/MyVideosView.tsx
> +        show={showMintModal && !!currentChannel?.yppStatus.startsWith('Verified') && !mintConfirmationDismissed}
For this modal `show` is a required `boolean`

2023-10-04 12:12 UTC, attemka approved these changes

2023-10-04 12:12 UTC, merged