Video sheet draft integration
Joystream/atlas pull request #493
Opened 2021-04-22 09:21 UTC by mikkio-j

Issue: #460

2021-04-23 10:46 UTC, kdembler reviewed
Looking good overall! Will do the code review later in the day, notes for now:
1) Assuming I have 2 drafts open and I close the currently selected one, the other one should get selected. Currently the closed draft's details are still visible in the form
1) If I close the draft that is not currently selected, it gets selected on close 😅 
1) The open in new tab button doesn't have a `pointer`
1) Opening draft in new tab shouldn't mark it as selected, just add it as a tab
1) If the sheet is closed, the open in new tab should make it open (as minimized)
1) The `Delete video` should be visible only when editing an existing video
1) Seems that according to the design the delete video shouldn't span the full width - https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=7389%3A6887
1) When I select a video file, it seems the tab name properly updates to that file's name but the draft name in the form stays `New Draft` and same in drafts tab? I would expect all of them to update
1) I think we don't have this ⬇️ Do you think we should add it?
<img width="1031" alt="Screenshot 2021-04-23 at 12 45 51" src="https://user-images.githubusercontent.com/12646744/115860528-e955d000-a431-11eb-8367-78fb66902a1f.png">

2021-04-23 14:03 UTC, drillprop reviewed
Didn't find anything besides things that were mentioned before. Awesome job! 👍🏻  I Will look at it again after you fix the issues

2021-04-26 07:24 UTC, mikkio-j commented
@kdembler Added fixes. Some things I want to mention regarding the notes:

5. Sheet is now minimized on open tab click, but it also redirects to "All videos" tab. Still looking for reason for that.
7. Design seems to be inconsistent, Delete button takes full width here: [https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=7426%3A19746](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=7426%3A19746) 
9. As I understand it, it should show up when user's trying to make a new transaction? Maybe it's better to implement that in blockchain integration task?

2021-04-26 09:34 UTC, kdembler requested changes

2021-04-26 09:34 UTC, kdembler commented on src/hooks/useEditVideoSheet.tsx
> +    if (sheetState === 'minimized' && cachedSheetState === 'open') {
Why did you remove the other condition? Do you understand why it was there?

2021-04-26 09:34 UTC, kdembler commented on src/hooks/useDrafts/utils.ts
> +export const updateDraft = async (draftId: string, draftProps: Omit<RawDraft, 'channelId'>) => {
Why does draft not have the channel information now? Is this captured in some other way? We wouldn't want the drafts to be global across channels right?

2021-04-26 09:34 UTC, kdembler commented on src/shared/components/Button/Button.tsx
> +export type TextColorVariant = 'default' | 'error'
Let's move this to `Button.style` to not create a two-way dependencies

2021-04-26 09:34 UTC, kdembler commented on src/shared/components/VideoPreviewBase/PullUp.tsx
> +    <Container disabled={disabled}>
Do we even need this?

2021-04-26 09:34 UTC, kdembler commented on src/utils/formValidationOptions.ts
> +  const parsedDate = parseISO(reversedDate)
Is this really needed? I think `date-fns` should be able to parse an arbitrary date format? https://date-fns.org/v2.21.1/docs/parse

2021-04-26 09:34 UTC, kdembler commented on src/utils/formValidationOptions.ts
> +export const dateValidation = (date: string, required = false) => {
Let's call this `pastDateValidation` since that's what it's doing

2021-04-26 09:34 UTC, kdembler commented on src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx
>    { name: 'Public (Anyone can see this video)', value: 'public' },
This could use `true/false` as values, the same as we do in channel edit. Then we don't need to do comparison when saving/loading the draft

2021-04-26 09:34 UTC, kdembler commented on src/views/studio/EditVideoSheet/EditVideoSheet.tsx
> +      const currentDraft = await getDraft(tab.id)
I don't think we need to fetch the draft directly from the local storage here. The hook exposes `drafts` which should be a list of drafts , we can use that.

2021-04-26 11:52 UTC, kdembler approved these changes

2021-04-26 11:52 UTC, merged