📈 Graphql response time logs
Joystream/atlas pull request #5730
Opened 2024-01-04 11:49 UTC by WRadoslaw

#5729

2024-01-08 02:02 UTC, zeeshanakram3 requested changes
Looks good. It appears that this change will only track Graphql response times, do we also want to track the time taken by REST endpoints as well, e.g YT-Synch, or other services that Atlas might be interacting with.

2024-01-08 02:02 UTC, zeeshanakram3 commented on packages/atlas/src/api/client/index.ts
> +        if ((entry as any).initiatorType === 'fetch') {
```suggestion
        if ((entry as PerformanceResourceTiming).initiatorType === 'fetch') {
```

2024-01-08 02:02 UTC, zeeshanakram3 commented on packages/atlas/src/api/client/index.ts
> +          console.log(`Query ${queryType ?? entry.name} took ${entry.duration}ms to complete`, entry)
On the staging env you shared, I am not not able to see specific query types, I see the complete graphql URLs. Is this expected?

<img width="635" alt="image" src="https://github.com/Joystream/atlas/assets/37098720/846273d6-fdd0-4509-8062-48bc8174edc2">

2024-01-08 02:02 UTC, zeeshanakram3 commented on packages/atlas/src/api/client/index.ts
> +          console.log(`Query ${queryType ?? entry.name} took ${entry.duration}ms to complete`, entry)
Also, instead of logging, shouldn't these events be sent to Elasticsearch?

2024-01-17 11:45 UTC, WRadoslaw commented on packages/atlas/src/api/client/index.ts
> +          console.log(`Query ${queryType ?? entry.name} took ${entry.duration}ms to complete`, entry)
Yeah, I just logged them for the POC purpose

2024-02-07 09:35 UTC, zeeshanakram3 approved these changes
LGTM

2024-02-07 10:09 UTC, merged