Segment analytics for CRT
Joystream/atlas pull request #6040
Opened 2024-03-22 09:18 UTC by attemka

#6001 

few things to note @dmtrjsg:

1. Page visit will show 'CRT Dashboard', selected tab will be in params. Same as we did on YPP Dashboard.
2. Can't track 'Tokens sold on AMM' as this can happen while user is away and we're only tracking user events. Although, 'Tokens purchased on AMM' is tracked and should cover it.

2024-03-27 08:50 UTC, WRadoslaw requested changes

2024-03-27 08:50 UTC, WRadoslaw commented on packages/atlas/src/components/_crt/BuyMarketTokenModal/BuyMarketTokenModal.tsx
> +            data?.creatorTokenById?.symbol ?? 'N/A',
We shouldn't use symbol as it is not unique

2024-03-27 08:50 UTC, WRadoslaw commented on packages/atlas/src/components/_crt/CloseMarketModal/CloseMarketModal.tsx
> +          trackAMMClosed(symbol ?? 'N/A', channelId)
Same as above

2024-03-29 11:20 UTC, WRadoslaw approved these changes
lgtm

2024-03-29 14:17 UTC, dmtrjsg commented
> Tokens sold on AMM' as this can happen while user is away and we're only tracking user events. Although, 'Tokens purchased on AMM' is tracked and should cover it.

@attemka user can initiate sale via GUI, that's what I was asking for here. I hope that was implemented? Its the same operation as purchased but user just clicks "sell" instead of "purchase".

2024-03-29 14:49 UTC, dmtrjsg approved these changes
ok

2024-03-29 15:11 UTC, WRadoslaw commented
Looks good

2024-03-29 15:12 UTC, merged