improve JOY token tooltip info
Joystream/atlas pull request #6128
Opened 2024-04-08 12:38 UTC by kdembler

Resolves #6127

2024-04-10 10:05 UTC, attemka requested changes

2024-04-10 10:05 UTC, attemka commented on packages/atlas/src/components/JoyTokenIcon/JoyTokenIcon.tsx
> +            Gleev. It is used for trading Creator Tokens, NFTs and covering blockchain processing fees. It is also used
```suggestion
            ${atlasConfig.general.appName}. It is used for trading Creator Tokens, NFTs and covering blockchain processing fees. It is also used
```

2024-04-10 10:05 UTC, attemka commented on packages/atlas/src/components/JoyTokenIcon/JoyTokenIcon.tsx
> +              Purchase JOY
```suggestion
              Purchase ${atlasConfig.joystream.tokenTicker}
```

2024-04-10 10:05 UTC, attemka commented on packages/atlas/src/views/global/YppLandingView/sections/YppRewardSection.tsx
> +                  powers Gleev. It is used for trading Creator Tokens, NFTs and covering blockchain processing fees. It
same as 2 above

2024-04-10 10:49 UTC, WRadoslaw commented
Could we instead of pointing to the Joystream website just redirect the user to the Portfolio page and show ChangeNow modal?

cc @dmtrjsg

2024-04-10 10:55 UTC, kdembler commented
@WRadoslaw Joystream website gives more purchasing options and lists exchanges, I think it's a better choice

2024-04-16 12:14 UTC, attemka approved these changes

2024-04-16 12:52 UTC, merged