Font imports
Joystream/atlas pull request #755
Opened 2021-06-10 06:49 UTC by mikkio-j

Issue: #329

2021-06-10 10:59 UTC, drillprop commented on src/styles/fonts.css
> +      url(data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAAHnQABMAAAABHZAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAABqAAAABwAAAAcbWcNJUdERUYAAAHEAAAANQAAADgF/wSGR1BPUwAAAfwAAA0LAAA3kDJuLLVHU
why we do this? Can we just add a normal `woff` and `woff2` file? There are plenty of converters out there, right?

2021-06-10 10:59 UTC, drillprop commented on src/styles/fonts.css
> +      url(data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAAHqAABMAAAABH2QAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAABqAAAABwAAAAcbWcE9kdERUYAAAHEAAAANQAAADgF/wSGR1BPUwAAAfwAAA0qAAA13FFvO71HU
same here

2021-06-10 11:21 UTC, kdembler requested changes
Probably should have brought that up before but we actually cannot include `PxGrotesk` files in our repo as it validates the license for that font. I need to clear some things up regarding that, let's put that on hold till then. Could we amend the commit and force push so we don't store the files in our git history?

2021-06-15 12:53 UTC, kdembler approved these changes

2021-06-15 12:53 UTC, merged