Animations playground lottie
Joystream/atlas pull request #855
Opened 2021-06-25 09:18 UTC by eldiegod

Set up Lottie test #845

2021-06-25 09:57 UTC, kdembler reviewed
Those are just beautiful, I can't wait to get those integrated in the app.

However, there's an issue I see currently. The `json` files for animations are quite huge and I wouldn't want to include them in the bundle, that's very costly. We need to either:
a) somehow hot load them, that should put them in their own separate chunks
b) host those statically somewhere outside of the bundle altogether.

I'm not sure how a) would work with caching between deployments but my guess is it'd be easier to do

2021-06-29 17:23 UTC, eldiegod commented
Loading the animations on-demand now, seems to be working and putting them in separate chunks

2021-06-30 07:24 UTC, kdembler requested changes

2021-06-30 07:24 UTC, kdembler commented on src/views/playground/Playgrounds/Animations.tsx
> +  const [XL, setXL] = useState<any>(null)
If we really need `any` for all of those, let's disable the eslint warning

2021-06-30 08:36 UTC, drillprop commented on src/views/playground/Playgrounds/Animations.tsx
> +  const [XS, setXS] = useState<any>(null)
```suggestion
  const [XL, setXL] = useState<Record<string, unknown> | null>(null)
  const [L, setL] = useState<Record<string, unknown> | null>(null)
  const [M, setM] = useState<Record<string, unknown> | null>(null)
  const [S, setS] = useState<Record<string, unknown> | null>(null)
  const [XS, setXS] = useState<Record<string, unknown> | null>(null)
```
should fix it

2021-06-30 08:59 UTC, drillprop commented on src/views/playground/Playgrounds/Animations.tsx
> +  const [XS, setXS] = useState<any>(null)
I overcomplicated this - we can write just `unknown | null` :P

2021-07-19 11:05 UTC, kdembler approved these changes

2021-07-19 11:05 UTC, merged