Text component
Joystream/atlas pull request #87
Opened 2020-11-30 15:57 UTC by Gamaranto

Fixes #37

2020-12-01 11:52 UTC, kdembler commented on src/shared/components/Text/Text.style.ts
> +  color: inherits;
I think that's `inherit`?

2020-12-01 13:15 UTC, kdembler requested changes
Also two other things:

1. The meta text for the `main` `VideoPreview` has wrong styles. Before and after:<br>
<img width="1090" alt="Screenshot 2020-12-01 at 14 06 51" src="https://user-images.githubusercontent.com/12646744/100745361-7941a180-33df-11eb-8cc5-690c831db132.png">
<img width="1083" alt="Screenshot 2020-12-01 at 14 06 46" src="https://user-images.githubusercontent.com/12646744/100745369-7c3c9200-33df-11eb-9c70-256109ee11b7.png">

2. The video title in `VideoView` has different font weight. Before and after (from 700 to 500):<br>
<img width="463" alt="Screenshot 2020-12-01 at 14 12 50" src="https://user-images.githubusercontent.com/12646744/100745449-98d8ca00-33df-11eb-8e26-f8519274a05e.png">
<img width="401" alt="Screenshot 2020-12-01 at 14 12 54" src="https://user-images.githubusercontent.com/12646744/100745458-9b3b2400-33df-11eb-8b07-b07c423b360d.png">

2020-12-01 13:15 UTC, kdembler commented on src/shared/components/Text/Text.style.ts
> +  color: inherits;
I think that's `inherit`?

2020-12-01 13:15 UTC, kdembler commented on src/shared/components/Text/Text.tsx
> +type TextVariant =
I think now this can be `type TextVariant = keyof typeof styledVariants`

2020-12-01 13:15 UTC, kdembler commented on src/shared/components/Text/Text.tsx
> +} & React.DetailedHTMLProps<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>
Out of curiosity, what props does this add?

2020-12-01 13:15 UTC, kdembler commented on src/components/FeaturedVideoHeader/FeaturedVideoHeader.style.ts
> +  font-weight: 700;
```suggestion
```

I think we can remove those now

2020-12-01 13:15 UTC, kdembler commented on src/components/FeaturedVideoHeader/FeaturedVideoHeader.style.ts
> +  margin: 0 0 ${sizes(4)} 0;
```suggestion
  margin-bottom: ${sizes(4)};
```

2020-12-01 13:15 UTC, kdembler commented on src/shared/components/ChannelPreview/ChannelPreview.tsx
>    margin: 0;
```suggestion
```

2020-12-01 13:15 UTC, kdembler commented on src/shared/components/Gallery/Gallery.style.ts
> +export const Heading = styled(Text)`
I don't think any custom style for that at all since we set `margin: 0;` for all the `Text`, right?

2020-12-01 13:15 UTC, kdembler commented on src/shared/components/InfiniteVideoGrid/InfiniteVideoGrid.tsx
>    margin: 0 0 ${sizes(4)};
```suggestion
  margin-bottom: ${sizes(4)};
```

2020-12-01 13:15 UTC, kdembler commented on src/views/VideoView/VideoView.style.tsx
> +export const Title = styled(Text)``
We can remove that I think

2020-12-02 12:51 UTC, Gamaranto commented on src/views/VideoView/VideoView.style.tsx
> +export const Title = styled(Text)``
Thanks, removed.

2020-12-02 12:51 UTC, Gamaranto commented on src/shared/components/InfiniteVideoGrid/InfiniteVideoGrid.tsx
>    margin: 0 0 ${sizes(4)};
Changed thanks

2020-12-02 12:51 UTC, Gamaranto commented on src/shared/components/Gallery/Gallery.style.ts
> +export const Heading = styled(Text)`
Correct, removed.

2020-12-02 12:51 UTC, Gamaranto commented on src/components/FeaturedVideoHeader/FeaturedVideoHeader.style.ts
> +  margin: 0 0 ${sizes(4)} 0;
Changed thank you

2020-12-02 12:51 UTC, Gamaranto commented on src/shared/components/ChannelPreview/ChannelPreview.tsx
>    margin: 0;
Changed thanks

2020-12-02 12:53 UTC, Gamaranto commented on src/shared/components/Text/Text.tsx
> +} & React.DetailedHTMLProps<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>
It adds all props like `onClick`, etc...  to make sure we can those to the `Text` component without TS errors.

2020-12-02 12:53 UTC, Gamaranto commented on src/shared/components/Text/Text.tsx
> +type TextVariant =
Good catch, changed it

2020-12-02 12:54 UTC, Gamaranto commented on src/shared/components/Text/Text.style.ts
> +  color: inherits;
Autosuggestion is not always infallible :P 

It broke text completely all over the app, so I ended up removing it.

2020-12-02 12:55 UTC, Gamaranto commented
> Also two other things:
> 
> 1. The meta text for the `main` `VideoPreview` has wrong styles. Before and after:
> 
> <img alt="Screenshot 2020-12-01 at 14 06 51" width="1090" src="https://user-images.githubusercontent.com/12646744/100745361-7941a180-33df-11eb-8cc5-690c831db132.png">
> 
> <img alt="Screenshot 2020-12-01 at 14 06 46" width="1083" src="https://user-images.githubusercontent.com/12646744/100745369-7c3c9200-33df-11eb-9c70-256109ee11b7.png">
> 
> 1. The video title in `VideoView` has different font weight. Before and after (from 700 to 500):
> 
> <img alt="Screenshot 2020-12-01 at 14 12 50" width="463" src="https://user-images.githubusercontent.com/12646744/100745449-98d8ca00-33df-11eb-8e26-f8519274a05e.png">
> 
> <img alt="Screenshot 2020-12-01 at 14 12 54" width="401" src="https://user-images.githubusercontent.com/12646744/100745458-9b3b2400-33df-11eb-8b07-b07c423b360d.png">

Both of those should be fixed now.

2020-12-02 15:34 UTC, kdembler commented on src/shared/components/Text/Text.tsx
> +} & React.DetailedHTMLProps<React.HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>
:+1:

2020-12-04 09:28 UTC, kdembler commented on src/views/VideoView/VideoView.style.tsx
> +  font-weight: ${typography.weights.bold};
I guess we don't need that anymore?

2020-12-04 09:44 UTC, kdembler approved these changes

2020-12-04 09:44 UTC, merged