Use global store for connection status
Joystream/atlas pull request #916
Opened 2021-06-29 08:25 UTC by mikkio-j

Issue: #913

2021-06-29 10:19 UTC, drillprop reviewed
Works good, but you forgot that we are using `immer`. Added two suggestions

2021-06-29 10:19 UTC, drillprop commented on src/providers/connectionStatus.tsx
> +    }))
```suggestion
    set((state) => {
      state.nodeConnectionStatus = connection
    })
```

2021-06-29 10:19 UTC, drillprop commented on src/providers/connectionStatus.tsx
> +    }))
```suggestion
    set((state) => {
      state.isUserConnectedToInternet = value
    })
```

2021-06-29 13:00 UTC, drillprop approved these changes

2021-06-29 13:00 UTC, drillprop commented on src/providers/connectionStatus.tsx
> +  setInternetConnection: (value: boolean) => void
```suggestion
  setInternetConnection: (isConnected: boolean) => void
```
last small thing - I think we should be more semantic here, let's just rename it

2021-06-29 13:00 UTC, drillprop commented on src/providers/connectionStatus.tsx
> +      state.isUserConnectedToInternet = value
```suggestion
  setInternetConnection: (isConnected) => {
    set((state) => {
      state.isUserConnectedToInternet = isConnected
```

2021-06-30 06:46 UTC, kdembler requested changes

2021-06-30 06:46 UTC, kdembler commented on src/providers/connectionStatus.tsx
> +export const useConnectionStatusStore = create<ConnectionStatusValue>((set) => ({
This is using the default `zustand` `create`, not from out store utilities. We should use the common helper. This one also doesn't have `immer` so my guess is it's not fully working

2021-06-30 12:39 UTC, drillprop commented on src/views/studio/SignInView/SignInView.tsx
> +  const nodeConnectionStatus = useConnectionStatusStore((state) => state.nodeConnectionStatus)
Previously if there was no internet connection all the tiles and sign-in button were disabled. Right now if you disconnect from wifi, you'll still be able to click those.

2021-06-30 13:22 UTC, kdembler approved these changes

2021-06-30 13:22 UTC, merged