Player hotkeys
Joystream/atlas pull request #978
Opened 2021-07-05 08:20 UTC by drillprop

Fix #936 #934 #932 
I definetely overestimate these :P

2021-07-05 08:22 UTC, drillprop commented
You can find all shortcuts here: https://github.com/Joystream/atlas/issues/823

2021-07-05 18:54 UTC, wyrdrender requested changes

2021-07-05 18:54 UTC, wyrdrender commented on src/shared/components/VideoPlayer/videoJsPlayer.ts
> +        hotkeys: (e) => hotkeysHandler(e, playerInstance),
```suggestion
        hotkeys: (event) => hotkeysHandler(event, playerInstance),
```

2021-07-05 18:54 UTC, wyrdrender commented on src/views/viewer/VideoView/VideoView.tsx
> +              autoplay={true}
```suggestion
              autoplay
```

2021-07-05 18:54 UTC, wyrdrender commented on src/shared/components/VideoPlayer/videoJsPlayer.ts
> +const hotkeysHandler = (e: videojs.KeyboardEvent, playerInstance: VideoJsPlayer) => {
```suggestion
const hotkeysHandler = (event: videojs.KeyboardEvent, playerInstance: VideoJsPlayer) => {
```

2021-07-06 09:17 UTC, wyrdrender approved these changes

2021-07-06 09:41 UTC, merged